export const qaSelectors = {
  appRoot: '#app',
  mainMenu: '.menu-screen',
  newGame: '#new',
  continueGame: '#continue',
  settingsButton: '#settings',
  supportButton: '#support',

  settingsScreen: '.settings-panel',
  settingsBack: '#back',
  languageSelect: '[data-language-select]',

  diagnosticsScreen: '.support-panel',
  storyWinQaButton: '#story-win-qa',

  sceneNavigationButton: '#episodes',

  sceneStudioButton: '#scene-studio',
  sceneStudioScreen: '[data-scene-studio-workspace]',
  sceneStudioDraggablePortrait: '.scene-studio-actor-slot[data-editor-draggable="true"] .scene-studio-runtime-portrait',
  sceneStudioPrimaryCalibration: '[data-calibration-slot="primary"]',
  sceneNavigationScreen: '.scene-select',
  sceneButton: '[data-scene]',

  vnRuntimeFrame: '[data-vn-frame="shared"][data-frame-context="runtime"]',
  vnScreen: '.vn-screen',
  vnBackgroundFit: '.vn-background-fit',
  vnStage: '.stage',
  vnDirectionCard: '.direction-card',
  vnDialogue: '.dialogue-text',
  vnLineId: '.line-id',
  vnNext: '#next',
  vnCharacter: '[data-character]',
  vnAuthoredShot: '[data-authored-shot]',
  vnAuthoredActor: '.vn-authored-actor-slot',
  vnChoiceScreen: '.choice-screen',
  vnChoiceButton: '[data-choice]',
  vnChoiceBackgroundFit: '.choice-background-fit',

  matchIntro: '.level-intro',
  matchIntroId: '.level-card .eyebrow',
  matchStart: '#start',

  match3CampaignButton: '#match3-campaign',
  match3CampaignScreen: '.match3-campaign-screen',
  match3CampaignLevelButton: '[data-campaign-level]',

  levelLabButton: '#level-lab',
  levelLabScreen: '.level-lab-screen',
  levelLabLevel: '#lab-level',
  levelLabSeed: '#lab-seed',
  levelLabPreview: '#lab-preview',
  levelLabMoves: '#lab-moves',
  levelLabInitialTiles: '#lab-initial-tiles-json',
  levelLabBlockers: '#lab-blockers-json',
  levelLabIngredients: '#lab-ingredients-json',
  levelLabObjectives: '#lab-objectives-json',
  levelLabApply: '#lab-apply',
  levelLabValidation: '#lab-validation',
  levelLabPlay: '#lab-play',

  match3Screen: '.match-screen',
  match3Board: '.board[role="grid"]',
  match3Cell: '[data-cell]',
  match3Moves: '.moves-left b',
  match3StageId: '.stage-meta b',
  match3Objectives: '.objectives .objective',
  match3ObjectiveValue: '.objectives .objective b',
  match3Hint: '#hint',
  match3HintedCell: '.board-cell.hinted[data-cell]',
  match3SelectedCell: '.board-cell.selected[data-cell]',
  match3Tile: '.tile[data-tile-variant]',
  match3Special: '.special',
  match3Feedback: '#match-feedback',
  match3Bark: '.field-bark',
  match3Quit: '#quit',
  match3TutorialTry: '#tutorial-try',

  evidenceTransition: '.evidence-transition',
  evidenceContinue: '#continue-story',
} as const;
