import type { MessageCatalog } from '../MessageCatalog';

// ANM-029B builds this catalog in reviewable production scopes.
// It is intentionally NOT wired into appCatalogs until the full stable source key set is complete.
export const beCatalog = {
  'localization.language.ru': 'Руская',
  'localization.language.en': 'English',
  'localization.language.label': 'Мова',
  'localization.language.help': 'Мова інтэрфейсу захоўваецца на гэтай прыладзе асобна ад гульнявога прагрэсу.',

  'common.back': 'Назад',
  'common.navigation': 'Навігацыя',
  'common.settings': 'Налады',
  'common.on': 'ON',
  'common.off': 'OFF',
  'common.enabled': 'Уключана',
  'common.disabled': 'Выключана',
  'common.available': 'даступна',
  'common.unavailable': 'недаступна',

  'menu.eyebrow': 'SEIRAN COLLEGE · CASE 001',
  'menu.title': 'Дэтэктывы',
  'menu.titleAccent': 'класа U',
  'menu.tagline': 'Камедыйная візуальная навела × match‑3',
  'menu.heroAria': 'Міку, Оноэ і Аюкі',
  'menu.newGame': 'Новая гульня',
  'menu.continue': 'Працягнуць',
  'menu.settings': 'Налады',
  'menu.sceneNavigation': 'Навігацыя па сцэнах',
  'menu.levelLab': 'Level Lab',
  'menu.sceneStudio': 'Студыя сцэн',
  'menu.match3Campaign': 'Match-3 кампанія',
  'menu.saveDiagnostics': 'Захаванні і дыягностыка',
  'menu.scriptLines': '{count} радкоў сцэнарыя',

  'settings.eyebrow': 'CONFIG · SYSTEM',
  'settings.title': 'Налады',
  'settings.audioHeading': 'Гук і водгук',
  'settings.audioCopy': 'Музыка і SFX ствараюцца лакальна праз Web Audio і не патрабуюць загрузкі аўдыяфайлаў. Налады захоўваюцца асобна ад гульнявога прагрэсу.',
  'settings.languageHeading': 'Мова',
  'settings.installHeading': 'Усталяванне і афлайн',
  'settings.mobileContractTitle': 'Мабільны кантракт',
  'settings.mobileContractCopy': 'Гук актывуецца толькі пасля першага дотыку або націску клавішы. Калі ўкладка пераходзіць у фон, музыка прыпыняецца і бяспечна аднаўляецца пасля вяртання.',
  'settings.navigationLabel': 'НАВІГАЦЫЯ',
  'settings.mainMenu': 'Галоўнае меню',
  'settings.mainMenuMatchWarning': 'Бягучая спроба запатрабуе пацвярджэння',
  'settings.mainMenuSafe': 'Захаваны прагрэс не страціцца',

  'audio.music': 'Музыка',
  'audio.effects': 'Эфекты',
  'audio.musicVolumeAria': 'Гучнасць музыкі',
  'audio.effectsVolumeAria': 'Гучнасць эфектаў',
  'audio.mute': 'Без гуку',
  'audio.haptics': 'Тактыльны водгук',
  'audio.hapticsSupported': 'Падтрымліваецца гэтай прыладай',
  'audio.hapticsUnavailable': 'Недаступна ў гэтым браўзеры',
  'audio.previewMusic': '▶ Праверыць музыку',
  'audio.previewEffects': '✦ Праверыць SFX',
  'audio.webAudio': 'Web Audio',
  'audio.hapticsCapability': 'Тактыльны водгук',
  'audio.hapticsAvailable': 'даступны',
  'audio.hapticsFallback': 'рэжым без вібрацыі',

  'pwa.install.installed': 'Усталявана',
  'pwa.install.available': 'Можна ўсталяваць',
  'pwa.install.browserMenu': 'Праз меню браўзера',
  'pwa.online': 'анлайн',
  'pwa.offline': 'афлайн',
  'pwa.cacheFailures': '{count} памылак кэша',
  'pwa.installAction': 'Усталяваць',
  'pwa.checkUpdate': 'Праверыць абнаўленне',
} as const satisfies MessageCatalog;

export const beCompletedCatalogPrefixes = [
  'localization',
  'common',
  'menu',
  'settings',
  'audio',
  'pwa',
] as const;
