import type { MessageCatalog } from '../MessageCatalog';

// ANM-029B builds this catalog in reviewable production scopes.
// It is intentionally NOT wired into appCatalogs until the full stable source key set is complete.
export const beCatalog = {
  'localization.language.ru': 'Руская',
  'localization.language.en': 'English',
  'localization.language.label': 'Мова',
  'localization.language.help': 'Мова інтэрфейсу захоўваецца на гэтай прыладзе асобна ад гульнявога прагрэсу.',

  'common.back': 'Назад',
  'common.navigation': 'Навігацыя',
  'common.settings': 'Налады',
  'common.on': 'ON',
  'common.off': 'OFF',
  'common.enabled': 'Уключана',
  'common.disabled': 'Выключана',
  'common.available': 'даступна',
  'common.unavailable': 'недаступна',

  'menu.eyebrow': 'SEIRAN COLLEGE · CASE 001',
  'menu.title': 'Дэтэктывы',
  'menu.titleAccent': 'класа U',
  'menu.tagline': 'Камедыйная візуальная навела × match‑3',
  'menu.heroAria': 'Міку, Оноэ і Аюкі',
  'menu.newGame': 'Новая гульня',
  'menu.continue': 'Працягнуць',
  'menu.settings': 'Налады',
  'menu.sceneNavigation': 'Навігацыя па сцэнах',
  'menu.levelLab': 'Level Lab',
  'menu.sceneStudio': 'Студыя сцэн',
  'menu.match3Campaign': 'Match-3 кампанія',
  'menu.saveDiagnostics': 'Захаванні і дыягностыка',
  'menu.scriptLines': '{count} радкоў сцэнарыя',

  'settings.eyebrow': 'CONFIG · SYSTEM',
  'settings.title': 'Налады',
  'settings.audioHeading': 'Гук і водгук',
  'settings.audioCopy': 'Музыка і SFX ствараюцца лакальна праз Web Audio і не патрабуюць загрузкі аўдыяфайлаў. Налады захоўваюцца асобна ад гульнявога прагрэсу.',
  'settings.languageHeading': 'Мова',
  'settings.installHeading': 'Усталяванне і афлайн',
  'settings.mobileContractTitle': 'Мабільны кантракт',
  'settings.mobileContractCopy': 'Гук актывуецца толькі пасля першага дотыку або націску клавішы. Калі ўкладка пераходзіць у фон, музыка прыпыняецца і бяспечна аднаўляецца пасля вяртання.',
  'settings.navigationLabel': 'НАВІГАЦЫЯ',
  'settings.mainMenu': 'Галоўнае меню',
  'settings.mainMenuMatchWarning': 'Бягучая спроба запатрабуе пацвярджэння',
  'settings.mainMenuSafe': 'Захаваны прагрэс не страціцца',

  'audio.music': 'Музыка',
  'audio.effects': 'Эфекты',
  'audio.musicVolumeAria': 'Гучнасць музыкі',
  'audio.effectsVolumeAria': 'Гучнасць эфектаў',
  'audio.mute': 'Без гуку',
  'audio.haptics': 'Тактыльны водгук',
  'audio.hapticsSupported': 'Падтрымліваецца гэтай прыладай',
  'audio.hapticsUnavailable': 'Недаступна ў гэтым браўзеры',
  'audio.previewMusic': '▶ Праверыць музыку',
  'audio.previewEffects': '✦ Праверыць SFX',
  'audio.webAudio': 'Web Audio',
  'audio.hapticsCapability': 'Тактыльны водгук',
  'audio.hapticsAvailable': 'даступны',
  'audio.hapticsFallback': 'рэжым без вібрацыі',

  'pwa.install.installed': 'Усталявана',
  'pwa.install.available': 'Можна ўсталяваць',
  'pwa.install.browserMenu': 'Праз меню браўзера',
  'pwa.online': 'анлайн',
  'pwa.offline': 'афлайн',
  'pwa.cacheFailures': '{count} памылак кэша',
  'pwa.installAction': 'Усталяваць',
  'pwa.checkUpdate': 'Праверыць абнаўленне',

  // ANM-029B2A — Belarusian Match-3 core/campaign scope.
  'match3.investigation': 'РАССЛЕДАВАННЕ {current}/{total}',
  'match3.investigationNavigation': 'Навігацыя расследавання',
  'match3.moves': 'хадоў',
  'match3.start': 'Пачаць пошук',
  'match3.emptyCell': 'Пустая клетка',
  'match3.holeCell': 'Неактыўная клетка поля',
  'match3.backToInvestigation': 'Назад да расследавання',
  'match3.objectivesAria': 'Мэты расследавання',
  'match3.objective': 'МЭТА',
  'match3.movesStageAria': 'Хады і этап',
  'match3.movesUpper': 'ХАДЫ',
  'match3.stage': 'ЭТАП {current}/{total}',
  'match3.boardAria': 'Поле 8 на 8',
  'match3.teamAria': 'Каманда расследавання',
  'match3.hint': 'ПАДКАЗКА',
  'match3.bestMove': 'Найлепшы ход',
  'match3.inputHint': 'Перацягніце фішку, правядзіце пальцам або выберыце дзве суседнія · падказка ўлічвае мэты.',
  'match3.tutorial.label': 'НАВУЧАННЕ',
  'match3.tutorial.basic-swap.title': 'Збірайце аднолькавыя прадметы',
  'match3.tutorial.basic-swap.body': 'Складзіце лінію з трох або больш аднолькавых фішак. Перацягніце фішку на суседнюю клетку або дакраніцеся да дзвюх суседніх фішак па чарзе.',
  'match3.tutorial.clear-blocker.title': 'Прыбірайце перашкоды',
  'match3.tutorial.clear-blocker.body': 'Супадзенні на клетцы з перашкодай або побач з ёй здымаюць адзін слой. Некаторыя перашкоды патрабуюць некалькіх трапленняў — працягвайце складаць камбінацыі побач.',
  'match3.tutorial.drop-ingredient.title': 'Апускайце сюжэтныя прадметы',
  'match3.tutorial.drop-ingredient.body': 'Сюжэтныя прадметы нельга мяняць месцамі. Вызваляйце клеткі пад імі, каб яны падалі ўніз, і давядзіце прадмет да ніжняга краю поля.',
  'match3.tutorial.activate-special.title': 'Актывуйце спецфішку',
  'match3.tutorial.activate-special.body': "Доўгія або фігурныя супадзенні ствараюць спецыяльныя інструменты расследавання. Калі такі інструмент з'явіцца, двойчы дакраніцеся да яго, каб адразу актываваць эфект. Спецфішкі таксама можна мяняць месцамі, а іх камбінацыі разгледзім асобна.",
  'match3.tutorial.combine-specials.title': 'Спалучайце спецфішкі',
  'match3.tutorial.combine-specials.body': "Калі дзве спецфішкі стаяць побач, памяняйце іх месцамі. Іх эфекты аб'яднаюцца ва ўзмоцнены ход расследавання, а розныя пары спецфішак могуць спрацоўваць па-рознаму.",
  'match3.tutorial.try': 'ПАСПРАБАВАЦЬ',
  'match3.evidenceFound': 'ДОКАЗ ЗНОЙДЗЕНЫ',
  'match3.continueStory': 'Працягнуць сцэну',
  'match3.result': 'Вынік',
  'match3.lossHeading': 'Версію трэба праверыць яшчэ раз',
  'match3.retry': 'Паўтарыць узровень',
  'match3.special.flash-row': 'Гарызантальная ўспышка',
  'match3.special.flash-column': 'Вертыкальная ўспышка',
  'match3.special.evidence': 'Доказ',
  'match3.special.lead': 'Зачэпка',
  'match3.special.insight': 'Азаранне',
  'match3.feedback.special': 'НАЗІРАННЕ!',
  'match3.feedback.chain': 'ЛАНЦУЖОК ×{count}',
  'match3.feedback.combo': 'КОМБА!',
  'match3.feedback.match': 'СУПАДЗЕННЕ',
  'match3.feedback.reshuffled': 'ПОЛЕ ПЕРАМЕШАНА',
  'match3.feedback.noMatch': 'НЯМА СУПАДЗЕННЯ',
  'match3.feedback.swapUnavailable': 'АБМЕН НЕДАСТУПНЫ',
  'match3.feedback.clueCollected': 'ДОКАЗ САБРАНЫ',
  'match3.feedback.outOfMoves': 'ХАДЫ СКОНЧЫЛІСЯ',
  'match3.bark.noHint': 'Поле не дае карэктнага абмену. Патрэбна перастаноўка.',
  'match3.bark.hintFound': 'Гэты абмен найлепш прасоўвае бягучыя мэты расследавання.',
  'match3.bark.edge': 'За краем поля абмену няма. Паспрабуем суседнюю клетку.',
  'match3.bark.ingredientInvalid': 'Сюжэтны прадмет трэба апусціць уніз супадзеннямі пад ім.',
  'match3.bark.blockedInvalid': 'Гэтая секцыя зачыненая. Спачатку складзём супадзенне побач.',
  'match3.bark.noMatchInvalid': 'Гэты абмен не ўтварае шэраг. Праверым суседнія катэгорыі.',
  'match3.bark.special': 'Калі паглядзець на ўсё адразу, беспарадак ператвараецца ва ўзор.',
  'match3.bark.cascade': 'Ланцужок назіранняў: {count}. Гэта ўжо амаль дэдукцыя.',
  'match3.tile.camisole': 'Тканіна',
  'match3.tile.laundryTag': 'Бірка',
  'match3.tile.panties': 'Камплект',
  'match3.tile.towel': 'Ручнік',
  'match3.tile.socks': 'Пара',
  'match3.tile.sportsBra': 'Спорт',

  'match3Campaign.eyebrow': 'MATCH-3 КАМПАНІЯ',
  'match3Campaign.title': 'Дошка спраў',
  'match3Campaign.summary': 'Праходзьце расследаванні як асобную match-3 кампанію. Яе прагрэс не звязаны з захаваннем візуальнай навелы.',
  'match3Campaign.progress': 'Пройдзена {completed}/{total}',
  'match3Campaign.complete': 'КАМПАНІЯ ПРОЙДЗЕНА · УСЕ ЎЗРОЎНІ ДАСТУПНЫЯ ДЛЯ ПАЎТОРУ',
  'match3Campaign.locked': 'ЗАЧЫНЕНА',
  'match3Campaign.completed': 'ПРОЙДЗЕНА',
  'match3Campaign.available': 'ДАСТУПНА',
  'match3Campaign.attempts': 'Спроб: {count}',
  'match3Campaign.best': 'Найлепшы вынік: засталося {moves} хадоў',
  'match3Campaign.replay': 'Паўтарыць',
  'match3Campaign.play': 'Пачаць узровень',
  'match3Campaign.backToCampaign': 'Назад у кампанію',
  'match3Campaign.stage': 'КАМПАНІЯ {current}/{total}',
  'match3Campaign.winEyebrow': 'УЗРОВЕНЬ ПРОЙДЗЕНЫ',
  'match3Campaign.lossEyebrow': 'ХАДЫ СКОНЧЫЛІСЯ',
  'match3Campaign.winHeading': 'Дошка расследавання вырашана',
  'match3Campaign.lossHeading': 'Паспрабуйце ўзровень яшчэ раз',
  'match3Campaign.resultDetail': 'Засталося хадоў: {movesLeft}. Прагрэс match-3 кампаніі захоўваецца асобна ад сюжэту.',
  'match3Campaign.nextLevel': 'Наступны ўзровень',
  'match3Campaign.retry': 'Паўтарыць узровень',

  // ANM-029B2B1 — Belarusian Match-3 levels 00–06.
  "match3.level.M3_00_LOCKER_TUTORIAL.clueTitle": "Выбарачная прапажа",
  "match3.level.M3_00_LOCKER_TUTORIAL.clueSummary": "З партыі пральні зніклі не ўсе рэчы; цана і прыкметнасць не тлумачаць выбар.",
  "match3.level.M3_01_PHOTO_PROPS.clueTitle": "Правяральнае алібі",
  "match3.level.M3_01_PHOTO_PROPS.clueSummary": "Таймкоды здымкі пацвярджаюць алібі Кэнтаро; сэрвісная каляска застаецца агульнай сувяззю.",
  "match3.level.M3_02_POOL_LAUNDRY.clueTitle": "Змешаныя мэты",
  "match3.level.M3_02_POOL_LAUNDRY.clueSummary": "Тып, цана, колер і ўладальнік рэчаў не тлумачаць выбар; рэчы змяшалі яшчэ да вяртання.",
  "match3.level.M3_03_ORDERED_APARTMENT.clueTitle": "Серабрыстая нітка",
  "match3.level.M3_03_ORDERED_APARTMENT.clueSummary": "Нічога не скралі, але пад сэрвіснай біркай з'явіўся новы электраправодны шво.",
  "match3.bark.fiveMoves.0": "Яшчэ крыху. Нам патрэбная сувязь з пральняй.",
  "match3.bark.fiveMoves.1": "Калі вы зноў яе страціце, гэта ўжо будзе калектыўнае алібі.",
  "match3.bark.fiveMoves.2": "Патрэбная шафа. Там журнал вяртання.",
  "match3.bark.fiveMoves.3": "Патрэбныя абодва прадметы. Без чэка версію не закрыць.",
  "match3.bark.blockers.0": "Доказ U-1 вызвалены. Не, я не дала яму імя.",
  "match3.bark.blockers.1": "Упакоўка шчыльная. Адзін удар адкрые, другі вызваліць змесціва.",
  "match3.bark.blockers.2": "Пад пенай рэчы з розных секцый. Іх змяшалі яшчэ да шафак.",
  "match3.bark.blockers.3": "Ні схованкі, ні саўдзельніцы. У гэтай кватэры няма пачуцця драмы.",
  "match3.bark.ingredient.0": "Дакумент у верхняй секцыі. Вызвалі шлях да ніжняга краю.",
  "match3.bark.ingredient.1": "Маленькая чорная карта, велізарны шанец на драму.",
  "match3.bark.ingredient.2": "Ключ усплыў. Метафарычна. Літаральна ён рухаецца ўніз.",
  "match3.bark.ingredient.3": "Шукаем абодва прадметы: чэк і ручнік са змененым краем.",
  "match3.ingredient.receipt": "Квітанцыя",
  "match3.ingredient.memoryCard": "Карта памяці",
  "match3.ingredient.serviceKey": "Сэрвісны ключ",
  "match3.ingredient.damagedTowel": "Ручнік са швом",
  "match3.clue.CUE_001": "Квітанцыя пральні",
  "match3.clue.CUE_002": "Карта памяці",
  "match3.clue.CUE_003": "Сэрвісны ключ",
  "match3.clue.CUE_004": "Электраправодны шво",
  "match3.level.M3_00_LOCKER_TUTORIAL.title": "Шафка Эмі",
  "match3.level.M3_00_LOCKER_TUTORIAL.storyAction": "Зафіксаваць змесціва шафкі і знайсці сувязь з пральняй.",
  "match3.level.M3_00_LOCKER_TUTORIAL.objective.0": "Клеткі",
  "match3.level.M3_00_LOCKER_TUTORIAL.objective.1": "Квітанцыя",
  "match3.level.M3_00_LOCKER_TUTORIAL.startBark.speaker": "Оноэ",
  "match3.level.M3_00_LOCKER_TUTORIAL.startBark.text": "Спачатку катэгорыі. Потым высновы.",
  "match3.level.M3_00_LOCKER_TUTORIAL.winBark.speaker": "Эмі",
  "match3.level.M3_00_LOCKER_TUTORIAL.winBark.text": "Знайшлі што-небудзь сапраўднае?",
  "match3.level.M3_01_PHOTO_PROPS.title": "Фотарэквізіт Кэнтаро",
  "match3.level.M3_01_PHOTO_PROPS.storyAction": "Разабраць рэквізіт па нумарах і знайсці карту памяці з таймкодамі.",
  "match3.level.M3_01_PHOTO_PROPS.objective.0": "Скрынкі",
  "match3.level.M3_01_PHOTO_PROPS.objective.1": "Карта памяці",
  "match3.level.M3_01_PHOTO_PROPS.startBark.speaker": "Кэнтаро",
  "match3.level.M3_01_PHOTO_PROPS.startBark.text": "Спачатку нумары. І нічога не апранайце — гэта рэквізіт.",
  "match3.level.M3_01_PHOTO_PROPS.winBark.speaker": "Міку",
  "match3.level.M3_01_PHOTO_PROPS.winBark.text": "Знайшла. Цяпер паглядзім не на пакой, а на час.",
  "match3.level.M3_02_POOL_LAUNDRY.title": "Мокрыя паказанні",
  "match3.level.M3_02_POOL_LAUNDRY.storyAction": "Аднавіць партыю мыцця, прыбраць пену і адкрыць сэрвісную шафу.",
  "match3.level.M3_02_POOL_LAUNDRY.objective.0": "Пена",
  "match3.level.M3_02_POOL_LAUNDRY.objective.1": "Сэрвісны ключ",
  "match3.level.M3_02_POOL_LAUNDRY.startBark.speaker": "Норыхіра",
  "match3.level.M3_02_POOL_LAUNDRY.startBark.text": "Спачатку біркі. Мокрыя здагадкі сохнуць даўжэй за ручнікі.",
  "match3.level.M3_02_POOL_LAUNDRY.winBark.speaker": "Оноэ",
  "match3.level.M3_02_POOL_LAUNDRY.winBark.text": "Партыя адноўлена. Цяпер параўнаем зніклае.",
  "match3.level.M3_03_ORDERED_APARTMENT.title": "Ідэальны парадак",
  "match3.level.M3_03_ORDERED_APARTMENT.storyAction": "Праверыць вернуты мяшок і знайсці прадмет з новым пашкоджаннем.",
  "match3.level.M3_03_ORDERED_APARTMENT.objective.0": "Секцыі",
  "match3.level.M3_03_ORDERED_APARTMENT.objective.1": "Доказы",
  "match3.level.M3_03_ORDERED_APARTMENT.startBark.speaker": "Норыхіра",
  "match3.level.M3_03_ORDERED_APARTMENT.startBark.text": "Злева направа. Калі парушыце парадак, самі яго адновіце.",
  "match3.level.M3_03_ORDERED_APARTMENT.winBark.speaker": "Міку",
  "match3.level.M3_03_ORDERED_APARTMENT.winBark.text": "Тут нічога не скралі. Але сёе-тое дадалі.",
  "match3.level.M3_00_LOCKER_TUTORIAL.loseBark.speaker": "Оноэ",
  "match3.level.M3_00_LOCKER_TUTORIAL.loseBark.text": "Мы парушылі парадак пошуку. Паўторым без страты прагрэсу сцэны.",
  "match3.level.M3_01_PHOTO_PROPS.loseBark.speaker": "Аюкі",
  "match3.level.M3_01_PHOTO_PROPS.loseBark.text": "Пакой перамог. Патрабую рэваншу і вузейшай спецыялізацыі скрынь.",
  "match3.level.M3_02_POOL_LAUNDRY.loseBark.speaker": "Норыхіра",
  "match3.level.M3_02_POOL_LAUNDRY.loseBark.text": "Пена перамагла дэдукцыю. Пачніце з краёў.",
  "match3.level.M3_03_ORDERED_APARTMENT.loseBark.speaker": "Норыхіра",
  "match3.level.M3_03_ORDERED_APARTMENT.loseBark.text": "Вы прайгралі шафе. Яна згодная на паўторную праверку.",
  "match3.ingredient.laundryCalendar": "Каляндар мыцця",
  "match3.ingredient.repairLog": "Журнал рамонту",
  "match3.ingredient.warrantyCard": "Гарантыйная картка",
  "match3.ingredient.silverSpool": "Серабрыстая шпулька",
  "match3.clue.CUE_005": "Рытм пральні",
  "match3.clue.CUE_006": "Сэрвісная строчка",
  "match3.clue.CUE_007": "Шво пасля рамонту",
  "match3.bark.fiveMoves.4": "Пяць хадоў. Каляндар павінен выйсці з шуму зараз.",
  "match3.bark.fiveMoves.5": "Пяць хадоў. Патрэбны журнал рамонту, а не яшчэ адна тэорыя росту.",
  "match3.bark.fiveMoves.6": "Пяць хадоў. Доказ наконт машыны павінен выйсці цалкам.",
  "match3.bark.blockers.4": "Палова чутак знятая. Табліца пачынае быць падобнай да даных.",
  "match3.bark.blockers.5": "Замкі сыходзяць, і склад партыі нарэшце можна параўноўваць.",
  "match3.bark.blockers.6": "Чахлы разабраныя. Цяпер майстэрня перастае хаваць храналогію.",
  "match3.bark.ingredient.4": "Агульны каляндар наверсе. Вызваляем яму шлях уніз.",
  "match3.bark.ingredient.5": "Журнал рамонту — найлепшы спосаб праверыць, што сапраўды праходзіла праз Хінату.",
  "match3.bark.ingredient.6": "Патрэбныя гарантыйная картка і серабрыстая шпулька. Толькі разам яны адказваюць на пытанне пра машыну.",
  "match3.level.M3_04_EMERGENCY_MEETING.title": "Сем клубаў, адзін каляндар",
  "match3.level.M3_04_EMERGENCY_MEETING.storyAction": "Аддзяліць пацверджаныя заявы ад чутак і аднавіць агульны каляндар мыцця.",
  "match3.level.M3_04_EMERGENCY_MEETING.objective.0": "Пацверджаныя біркі",
  "match3.level.M3_04_EMERGENCY_MEETING.objective.1": "Чуткі",
  "match3.level.M3_04_EMERGENCY_MEETING.objective.2": "Каляндар",
  "match3.level.M3_04_EMERGENCY_MEETING.startBark.speaker": "Маю",
  "match3.level.M3_04_EMERGENCY_MEETING.startBark.text": "Факты асобна. Чуткі асобна. І ніякіх скрыншотаў.",
  "match3.level.M3_04_EMERGENCY_MEETING.winBark.speaker": "Міку",
  "match3.level.M3_04_EMERGENCY_MEETING.winBark.text": "Сем клубаў, адзін маршрут, які паўтараецца. Цяпер гэта сістэма.",
  "match3.level.M3_04_EMERGENCY_MEETING.loseBark.speaker": "Оноэ",
  "match3.level.M3_04_EMERGENCY_MEETING.loseBark.text": "Мы змяшалі сведчанні і версіі. Збяром табліцу нанова.",
  "match3.level.M3_04_EMERGENCY_MEETING.clueTitle": "Рытм пральні",
  "match3.level.M3_04_EMERGENCY_MEETING.clueSummary": "Усе пацверджаныя выпадкі праходзяць праз цэнтральную пральню за 24–48 гадзін да прапажы.",
  "match3.level.M3_05_BASKETBALL_LOCKERS.title": "Высокія шафкі",
  "match3.level.M3_05_BASKETBALL_LOCKERS.storyAction": "Адкрыць секцыі, зверыць сэрвісныя біркі і аднавіць журнал рамонту.",
  "match3.level.M3_05_BASKETBALL_LOCKERS.objective.0": "Замкі",
  "match3.level.M3_05_BASKETBALL_LOCKERS.objective.1": "Сэрвісныя біркі",
  "match3.level.M3_05_BASKETBALL_LOCKERS.objective.2": "Журнал рамонту",
  "match3.level.M3_05_BASKETBALL_LOCKERS.startBark.speaker": "Хіната",
  "match3.level.M3_05_BASKETBALL_LOCKERS.startBark.text": "Спачатку журнал і ярлыкі. Потым можаце падазраваць каго заўгодна.",
  "match3.level.M3_05_BASKETBALL_LOCKERS.winBark.speaker": "Оноэ",
  "match3.level.M3_05_BASKETBALL_LOCKERS.winBark.text": "Карэляцыі са знешнім выглядам няма. А строчка паўтараецца.",
  "match3.level.M3_05_BASKETBALL_LOCKERS.loseBark.speaker": "Аюкі",
  "match3.level.M3_05_BASKETBALL_LOCKERS.loseBark.text": "Шафкі вышэйшыя за маю тэорыю. Яшчэ раз, але цяпер па ярлыках.",
  "match3.level.M3_05_BASKETBALL_LOCKERS.clueTitle": "Сэрвісная строчка",
  "match3.level.M3_05_BASKETBALL_LOCKERS.clueSummary": "Памер, стыль і ўладальнік не звязаныя з прапажамі; на спрэчных рэчах паўтараецца аднолькавая сэрвісная строчка.",
  "match3.level.M3_06_TEXTILE_WORKSHOP.title": "Майстэрня Хінаты",
  "match3.level.M3_06_TEXTILE_WORKSHOP.storyAction": "Супаставіць заказы, прыбраць чахлы і знайсці гарантыйную картку разам з серабрыстай шпулькай.",
  "match3.level.M3_06_TEXTILE_WORKSHOP.objective.0": "Чахлы",
  "match3.level.M3_06_TEXTILE_WORKSHOP.objective.1": "Заказы",
  "match3.level.M3_06_TEXTILE_WORKSHOP.objective.2": "Праверка машыны",
  "match3.level.M3_06_TEXTILE_WORKSHOP.startBark.speaker": "Хіната",
  "match3.level.M3_06_TEXTILE_WORKSHOP.startBark.text": "Заказы злева, узоры справа. Не абвінавачвайце машыну без спецыфікацыі.",
  "match3.level.M3_06_TEXTILE_WORKSHOP.winBark.speaker": "Міку",
  "match3.level.M3_06_TEXTILE_WORKSHOP.winBark.text": "Хіната выключаная. Шво з'явілася пасля яе майстэрні — на маршруце пральні.",
  "match3.level.M3_06_TEXTILE_WORKSHOP.loseBark.speaker": "Хіната",
  "match3.level.M3_06_TEXTILE_WORKSHOP.loseBark.text": "Вы змяшалі заказы і ўзоры. У майстэрні гэта горш за кепскую гіпотэзу.",
  "match3.level.M3_06_TEXTILE_WORKSHOP.clueTitle": "Шво пасля рамонту",
  "match3.level.M3_06_TEXTILE_WORKSHOP.clueSummary": "Да цэнтральнай пральні серабрыстага шва не было; абсталяванне Хінаты не падтрымлівае такую электраправодную нітку.",

  // ANM-029B2B2 — Belarusian Match-3 levels 07–13.
  "match3.ingredient.asterionSpec": "Спецыфікацыя Asterion",
  "match3.ingredient.missingNumberSheet": "Аркуш прапушчаных нумароў",
  "match3.ingredient.handoffSlip": "Накладная перадачы",
  "match3.clue.CUE_008": "Нітка Asterion",
  "match3.clue.CUE_009": "Прапускі ў журнале",
  "match3.clue.CUE_010": "Начныя кантэйнеры",
  "match3.bark.fiveMoves.7": "Пяць хадоў. Аддзяліце фізічнае супадзенне ад запісу ў рэестры.",
  "match3.bark.fiveMoves.8": "Пяць хадоў. Прапушчаны дыяпазон павінен выявіцца зараз.",
  "match3.bark.fiveMoves.9": "Пяць хадоў. Ключ і накладная павінны выйсці разам.",
  "match3.bark.blockers.7": "Палова ахоўных вечкаў знятая. Цяпер бачны парадак лабараторных картак.",
  "match3.bark.blockers.8": "Секцыі адкрываюцца. Правярайце нумары як паслядоўнасць, а не як асобныя пакеты.",
  "match3.bark.blockers.9": "Гаспадарчыя скрыні разабраныя. Застаўся маршрут ключа і каляскі.",
  "match3.bark.ingredient.7": "Спецыфікацыя наверсе. Вызваліце ёй прамы шлях уніз.",
  "match3.bark.ingredient.8": "Аркуш з прапускамі павінен прайсці праз сэрвісныя шэрагі цалкам.",
  "match3.bark.ingredient.9": "Ключ і накладная — адзін ланцужок. Не раздзяляйце іх у выснове.",
  "match3.level.M3_07_ASTERION_THREAD.title": "Узоры Asterion",
  "match3.level.M3_07_ASTERION_THREAD.storyAction": "Супаставіць серабрыстую нітку, лабараторныя карткі і афіцыйную спецыфікацыю.",
  "match3.level.M3_07_ASTERION_THREAD.objective.0": "Вечкі",
  "match3.level.M3_07_ASTERION_THREAD.objective.1": "Узоры",
  "match3.level.M3_07_ASTERION_THREAD.objective.2": "Спецыфікацыя",
  "match3.level.M3_07_ASTERION_THREAD.startBark.speaker": "Куросэ",
  "match3.level.M3_07_ASTERION_THREAD.startBark.text": "Склад, крок шва, код партыі. Калі ўзор наш — прыбор гэта пакажа.",
  "match3.level.M3_07_ASTERION_THREAD.winBark.speaker": "Міку",
  "match3.level.M3_07_ASTERION_THREAD.winBark.text": "Нітка супала. А афіцыйнага прызначэння на асабістыя рэчы ўсё роўна няма.",
  "match3.level.M3_07_ASTERION_THREAD.loseBark.speaker": "Оноэ",
  "match3.level.M3_07_ASTERION_THREAD.loseBark.text": "Мы змяшалі тэхнічнае супадзенне і адміністрацыйны запіс. Раздзелім іх.",
  "match3.level.M3_07_ASTERION_THREAD.clueTitle": "Нітка Asterion",
  "match3.level.M3_07_ASTERION_THREAD.clueSummary": "Серабрыстая нітка належыць Asterion, але адкрыты рэестр не змяшчае прызначэнняў на асабістыя рэчы студэнтаў.",
  "match3.level.M3_08_LOST_FOUND_LEDGER.title": "Восемдзесят сем пакетаў",
  "match3.level.M3_08_LOST_FOUND_LEDGER.storyAction": "Аднавіць сэрвісныя шэрагі склада і паслядоўнасць прапушчаных нумароў.",
  "match3.level.M3_08_LOST_FOUND_LEDGER.objective.0": "Пакеты",
  "match3.level.M3_08_LOST_FOUND_LEDGER.objective.1": "Сэрвісныя коды",
  "match3.level.M3_08_LOST_FOUND_LEDGER.objective.2": "Прапускі",
  "match3.level.M3_08_LOST_FOUND_LEDGER.startBark.speaker": "Рына",
  "match3.level.M3_08_LOST_FOUND_LEDGER.startBark.text": "Нумары важнейшыя за змесціва. Калі паслядоўнасць парушаная, спачатку знайдзіце месца разрыву.",
  "match3.level.M3_08_LOST_FOUND_LEDGER.winBark.speaker": "Оноэ",
  "match3.level.M3_08_LOST_FOUND_LEDGER.winBark.text": "Гэта не выпадковыя страты. З журнала выразаныя цэлыя дыяпазоны аднаго сэрвіснага ланцужка.",
  "match3.level.M3_08_LOST_FOUND_LEDGER.loseBark.speaker": "Рына",
  "match3.level.M3_08_LOST_FOUND_LEDGER.loseBark.text": "Вы змяшалі секцыі і статусы. Склад даруе гэта горш, чым музей.",
  "match3.level.M3_08_LOST_FOUND_LEDGER.clueTitle": "Прапускі ў журнале",
  "match3.level.M3_08_LOST_FOUND_LEDGER.clueSummary": "Спрэчныя пакеты выдаленыя са звычайнай паслядоўнасці цэлымі дыяпазонамі, якія супадаюць з датамі пацверджаных знікненняў.",
  "match3.level.M3_09_MAINTENANCE_KEYS.title": "Журнал універсальнага ключа",
  "match3.level.M3_09_MAINTENANCE_KEYS.storyAction": "Разабраць гаспадарчы склад, аднавіць перадачу ключа і транспартную накладную.",
  "match3.level.M3_09_MAINTENANCE_KEYS.objective.0": "Скрыні",
  "match3.level.M3_09_MAINTENANCE_KEYS.objective.1": "Пары шкарпэтак",
  "match3.level.M3_09_MAINTENANCE_KEYS.objective.2": "Ключ і накладная",
  "match3.level.M3_09_MAINTENANCE_KEYS.startBark.speaker": "Гэн",
  "match3.level.M3_09_MAINTENANCE_KEYS.startBark.text": "Ключы злева, вяртанні справа. Шкарпэткі — асобная сістэма, і прашу яе паважаць.",
  "match3.level.M3_09_MAINTENANCE_KEYS.winBark.speaker": "Міку",
  "match3.level.M3_09_MAINTENANCE_KEYS.winBark.text": "Гэн не сыходзіцца па часе. А кантэйнер Asterion сыходзіцца з маршрутам занадта добра.",
  "match3.level.M3_09_MAINTENANCE_KEYS.loseBark.speaker": "Аюкі",
  "match3.level.M3_09_MAINTENANCE_KEYS.loseBark.text": "Я прайграла стэнду шкарпэтак. Ён патрабуе рэваншу па форме U.",
  "match3.level.M3_09_MAINTENANCE_KEYS.clueTitle": "Начныя кантэйнеры",
  "match3.level.M3_09_MAINTENANCE_KEYS.clueSummary": "Пасля закрыцця пральні кантэйнеры Asterion уваходзяць у той самы фізічны маршрут; накладная звязвае начную перадачу з лабараторным прэфіксам Куросэ.",
  "match3.ingredient.stitchedWristband": "Напульснік са швом",
  "match3.ingredient.transferSeal": "Пломба кантэйнера",
  "match3.ingredient.routeCard": "Картка маршруту",
  "match3.ingredient.transferManifest": "Маніфест перадачы",
  "match3.ingredient.secondSkinTag": "Мікраметка Second Skin",
  "match3.clue.CUE_011": "Кантрольная выбарка",
  "match3.clue.CUE_012": "Ланцужок перадачы Asterion",
  "match3.clue.CUE_013": "Метка Second Skin",
  "match3.bark.fiveMoves.10": "Пяць хадоў. Аддзяліце тэхнічны крытэрый ад асабістай рэчы.",
  "match3.bark.fiveMoves.11": "Пяць хадоў. Пломба, маршрут і маніфест павінны сысціся ў адзін ланцужок.",
  "match3.bark.fiveMoves.12": "Пяць хадоў. Прыбярыце шум і выведзіце актыўную метку.",
  "match3.bark.blockers.10": "Палова замкоў знятая. Цяпер бачна, што кантрольная выбарка шырэйшая за адзін тып адзення.",
  "match3.bark.blockers.11": "Упакоўка раскрытая. Супастаўляйце нумары пломбаў з маршрутам, а не са змесцівам.",
  "match3.bark.blockers.12": "Перашкоды слабеюць. Паўторны сігнал ужо аддзяляецца ад шуму.",
  "match3.bark.ingredient.10": "Напульснік павінен выйсці цалкам: менавіта на ім паўтараецца серабрысты шво.",
  "match3.bark.ingredient.11": "Спачатку пломба і маршрут, потым маніфест — гэта адна перадача.",
  "match3.bark.ingredient.12": "Мікраметка павінна дайсці ўніз без страты сігнальнага ланцужка.",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.title": "Кантрольная экіпіроўка",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.storyAction": "Адкрыць секцыі клуба каратэ, аддзяліць перамешчаную экіпіроўку і праверыць паўторны серабрысты шво.",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.objective.0": "Замкі",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.objective.1": "Сэрвісныя біркі",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.objective.2": "Напульснік са швом",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.startBark.speaker": "Аоі",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.startBark.text": "Адкрываем секцыі па парадку. Гонар клуба перажыве кантрольную выбарку.",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.winBark.speaker": "Міку",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.winBark.text": "Шво паўтараецца на знешняй экіпіроўцы. Значыць, крытэрый тэхнічны, а не асабісты.",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.loseBark.speaker": "Оноэ",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.loseBark.text": "Мы змяшалі перамяшчэнне і знікненне. Раздзелім выбарку і паўторым.",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.clueTitle": "Кантрольная выбарка",
  "match3.level.M3_10_CONTROL_SAMPLE_GEAR.clueSummary": "Серабрыстая сістэма сустракаецца на бялізне і знешняй экіпіроўцы ўдзельнікаў маніторынгу: бялізна — асноўная выбарка, але не адзіная.",
  "match3.level.M3_11_ASTERION_TRANSFER.title": "Ланцужок кантэйнера",
  "match3.level.M3_11_ASTERION_TRANSFER.storyAction": "Супаставіць пломбы, маршрут і маніфест паміж пральняй, перагрузачным пунктам і лабараторыяй Asterion.",
  "match3.level.M3_11_ASTERION_TRANSFER.objective.0": "Упакоўка",
  "match3.level.M3_11_ASTERION_TRANSFER.objective.1": "Пломба і маршрут",
  "match3.level.M3_11_ASTERION_TRANSFER.objective.2": "Маніфест",
  "match3.level.M3_11_ASTERION_TRANSFER.startBark.speaker": "Кэнтаро",
  "match3.level.M3_11_ASTERION_TRANSFER.startBark.text": "Нумар кантэйнера ёсць у арыгінале. Цяпер дакажам увесь шлях, а не толькі прыгожы кадр.",
  "match3.level.M3_11_ASTERION_TRANSFER.winBark.speaker": "Оноэ",
  "match3.level.M3_11_ASTERION_TRANSFER.winBark.text": "Ланцужок бесперапынны. Лабараторыя ўваходзіць у фізічны маршрут рэчаў.",
  "match3.level.M3_11_ASTERION_TRANSFER.loseBark.speaker": "Міку",
  "match3.level.M3_11_ASTERION_TRANSFER.loseBark.text": "У нас ёсць часткі маршруту, але няма бесперапыннага ланцужка. Збяром яго нанова.",
  "match3.level.M3_11_ASTERION_TRANSFER.clueTitle": "Ланцужок перадачы Asterion",
  "match3.level.M3_11_ASTERION_TRANSFER.clueSummary": "Фатаграфіі, пломбы і маніфест даказваюць маршрут спрэчных рэчаў з пральні ў лабараторны контур Asterion і назад.",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.title": "Сігнал Second Skin",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.storyAction": "Аддзяліць радыёперашкоды ад паўторнага сігналу і выняць актыўную мікраметку з сэрвіснай біркі.",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.objective.0": "Перашкоды",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.objective.1": "Сігнальныя вузлы",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.objective.2": "Мікраметка",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.startBark.speaker": "Аюкі",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.startBark.text": "Калі ПанцуІтэр сапраўдны, зараз у яго будзе вельмі дрэнная ноч.",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.winBark.speaker": "Міку",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.winBark.text": "Не дэман. Актыўная метка, радыёпакет і імя Second Skin.",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.loseBark.speaker": "Оноэ",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.loseBark.text": "Шум перамог вымярэнне. Паўторым з падзеленымі частотамі.",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.clueTitle": "Метка Second Skin",
  "match3.level.M3_12_SECOND_SKIN_SIGNAL.clueSummary": "Актыўная мікраметка перадае даныя пад унутраным імем Second Skin і тлумачыць тэхнічны крытэрый выбару рэчаў.",
  "match3.ingredient.pilotList": "Закрыты спіс пілота",
  "match3.clue.CUE_014": "Закрыты спіс пілота",
  "match3.bark.fiveMoves.13": "Пяць хадоў. Спіс пілота павінен выйсці без здагадак пра Кубо.",
  "match3.bark.blockers.13": "Стойкі вызваляюцца. Цяпер коды ўладальнікаў чытаюцца як адна выбарка.",
  "match3.bark.ingredient.13": "Закрыты спіс павінен дайсці ўніз і сустрэцца з пацверджанымі кодамі.",
  "match3.level.M3_13_KENDO_PILOT_LIST.title": "Пад даспехамі",
  "match3.level.M3_13_KENDO_PILOT_LIST.storyAction": "Расчысціць стойкі кэндо і супаставіць сэрвісныя коды з закрытым спісам удзельнікаў пілота.",
  "match3.level.M3_13_KENDO_PILOT_LIST.objective.0": "Стойкі з даспехамі",
  "match3.level.M3_13_KENDO_PILOT_LIST.objective.1": "Коды ўдзельнікаў",
  "match3.level.M3_13_KENDO_PILOT_LIST.objective.2": "Спіс пілота",
  "match3.level.M3_13_KENDO_PILOT_LIST.startBark.speaker": "Кубо",
  "match3.level.M3_13_KENDO_PILOT_LIST.startBark.text": "Прашу аддзяліць мае перамяшчэнні мяшкоў ад таго, што было ўнутры іх.",
  "match3.level.M3_13_KENDO_PILOT_LIST.winBark.speaker": "Міку",
  "match3.level.M3_13_KENDO_PILOT_LIST.winBark.text": "Усё супала. Знікненні ідуць паводле спіса ўдзельнікаў пілота.",
  "match3.level.M3_13_KENDO_PILOT_LIST.loseBark.speaker": "Оноэ",
  "match3.level.M3_13_KENDO_PILOT_LIST.loseBark.text": "Спіс не адноўлены. Паўтараем без высноў пра пасрэдніка.",
  "match3.level.M3_13_KENDO_PILOT_LIST.clueTitle": "Закрыты спіс пілота",
  "match3.level.M3_13_KENDO_PILOT_LIST.clueSummary": "Усе пацверджаныя ўладальнікі зніклых рэчаў уваходзяць у закрыты спіс удзельнікаў Second Skin.",

  // ANM-029B2B3 — Belarusian Match-3 levels 14–21.
  "match3.ingredient.familyReceipt": "Квітанцыя атэлье",
  "match3.ingredient.atelierLedger": "Кніга заказаў",
  "match3.ingredient.markedPackage": "Пазначаны пакет",
  "match3.ingredient.serviceKeyCard": "Службовая ключ-карта",
  "match3.clue.CUE_015": "Рына ведала загадзя",
  "match3.clue.CUE_016": "Маршрут згоды",
  "match3.bark.fiveMoves.14": "Пяць хадоў. Не змешвайце запісы старонніх кліентаў з доказам.",
  "match3.bark.fiveMoves.15": "Пяць хадоў. Пакет і ключ-карта павінны выйсці разам.",
  "match3.bark.blockers.14": "Тканіна разабраная. Храналогія заказаў становіцца бачнай.",
  "match3.bark.blockers.15": "Праход ачышчаецца. Стары сэрвісны маршрут усё яшчэ выкарыстоўваецца.",
  "match3.bark.ingredient.14": "Квітанцыя і кніга заказаў патрэбныя разам — паасобку яны слабейшыя.",
  "match3.bark.ingredient.15": "Не раздзяляйце пакет і ключ-карту: яны даказваюць адзін дзейны маршрут.",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.title": "Кніга сямейнага атэлье",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.storyAction": "Супаставіць квітанцыі, вырабы і кнігу заказаў, не змешваючы запісы старонніх кліентаў.",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.objective.0": "Стосы тканіны",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.objective.1": "Коды заказаў",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.objective.2": "Квітанцыя + кніга",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.startBark.speaker": "Маці Кубо",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.startBark.text": "Спачатку даты і вырабы. Чужыя імёны не трапляюць у расследаванне аўтаматычна.",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.winBark.speaker": "Оноэ",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.winBark.text": "Храналогія гатовая. Рына шукала меткі да пачатку публічных знікненняў.",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.loseBark.speaker": "Кубо",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.loseBark.text": "Сямейная кніга заслугоўвае больш акуратнага другога праходу.",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.clueTitle": "Рына ведала загадзя",
  "match3.level.M3_14_KUBO_ATELIER_LEDGER.clueSummary": "Кніга заказаў даказвае: Рына шукала серабрыстыя швы і запісвала коды яшчэ да першых публічных крадзяжоў.",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.title": "Стары сэрвісны маршрут",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.storyAction": "Расчысціць закінутую пральню, сабраць сляды ніткі і вывесці пазначаны пакет з дзейнай ключ-картай.",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.objective.0": "Смецце",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.objective.1": "Сляды ніткі",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.objective.2": "Пакет + ключ-карта",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.startBark.speaker": "Аюкі",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.startBark.text": "Калі кот зараз яшчэ і адкрые шафу, я залічу яго ў штат.",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.winBark.speaker": "Міку",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.winBark.text": "Маршрут дзейны. І запіска пераводзіць справу ад крадзяжоў да пытання згоды.",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.loseBark.speaker": "Оноэ",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.loseBark.text": "Смецце схавала ланцужок. Паўтараем і трымаем пакет асобна ад версіі.",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.clueTitle": "Маршрут згоды",
  "match3.level.M3_15_ABANDONED_LAUNDRY_ROUTE.clueSummary": "Стары корпус застаецца дзейным службовым маршрутам; ананімная крыніца ведае пра згоду ўдзельнікаў і вядзе клуб па следзе Рыны.",
  "match3.ingredient.handheldScanner": "Ручны сканер",
  "match3.ingredient.rinaCatalog": "Каталог Рыны",
  "match3.ingredient.recentMarkedItem": "Новы пазначаны прадмет",
  "match3.clue.CUE_017": "Актывацыя пасля Рыны",
  "match3.clue.CUE_018": "Каталог Рыны",
  "match3.clue.CUE_019": "Працяг Second Skin",
  "match3.bark.fiveMoves.16": "Пяць хадоў. Сканер павінен выйсці разам з пацверджаным часам актывацыі.",
  "match3.bark.fiveMoves.17": "Пяць хадоў. Не змешвайце кантрольную паліцу з рэальнымі мэтамі.",
  "match3.bark.fiveMoves.18": "Пяць хадоў. Новая метка павінна застацца ў правільнай часовай лініі.",
  "match3.bark.blockers.16": "Стужкі разблытаныя. Сэрвісныя коды і сігнал чытаюцца асобна.",
  "match3.bark.blockers.17": "Пломбы знятыя. Каталог можна звяраць шэраг за шэрагам.",
  "match3.bark.blockers.18": "Ілжывыя высновы знікаюць. Даказаныя дзеянні падзяляюцца па часе.",
  "match3.bark.ingredient.16": "Сканер патрэбны як незалежнае пацвярджэнне новай актывацыі.",
  "match3.bark.ingredient.17": "Каталог павінен выйсці з архіва цэлым і ў кантэксце пломбаў.",
  "match3.bark.ingredient.18": "Новы пазначаны прадмет даказвае працяг праекта пасля Рыны.",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.title": "Ружовыя стужкі не хлусяць",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.storyAction": "Разблытаць стужкі, аднавіць сэрвісныя коды і пацвердзіць свежую актывацыю Second Skin ручным сканерам.",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.objective.0": "Вузлы стужак",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.objective.1": "Коды метак",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.objective.2": "Сканер",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.startBark.speaker": "Вінсент",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.startBark.text": "Стужкі асобна, сэрвісныя ярлыкі асобна. Сканер не любіць, калі яму дапамагаюць здагадкамі.",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.winBark.speaker": "Міку",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.winBark.text": "Новая актывацыя пазнейшая за доступ Рыны. Second Skin працягвае працаваць без яе.",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.loseBark.speaker": "Оноэ",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.loseBark.text": "Мы згубілі час актывацыі ў шуме. Паўтараем і захоўваем парадак кодаў.",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.clueTitle": "Актывацыя пасля Рыны",
  "match3.level.M3_16_PINK_RIBBON_SCANNER.clueSummary": "Новая метка Second Skin актывавалася пасля сыходу Рыны, а SS-EDGE адказаў праз дзейны кампусны рэтранслятар.",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.title": "Каталог Рыны",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.storyAction": "Адкрыць архіўныя шэрагі, аддзяліць рэальныя мэты ад кантрольных прадметаў і зверыць каталог з пацверджанымі знікненнямі.",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.objective.0": "Архіўныя пломбы",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.objective.1": "Коды мэт",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.objective.2": "Каталог",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.startBark.speaker": "Рына",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.startBark.text": "Спачатку коды і пломбы. Матыў не стане дакладнейшым, калі вы пераблытаеце кантрольную паліцу з мэтамі.",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.winBark.speaker": "Оноэ",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.winBark.text": "Супадзенне поўнае. Рына фізічна забірала рэчы і каталогізавала кожную мэту.",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.loseBark.speaker": "Рына",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.loseBark.text": "Вы змяшалі мэты і статыстычны шум. Архіў патрабуе больш строгага другога праходу.",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.clueTitle": "Каталог Рыны",
  "match3.level.M3_17_RINA_ARCHIVE_CATALOG.clueSummary": "Запячатаны каталог цалкам супадае з пацверджанымі крадзяжамі і аддзяляе рэальныя мэты Second Skin ад выпадковай маскіруючай выбаркі.",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.title": "Поўная часовая лінія",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.storyAction": "Прыбраць абвергнутыя версіі, звесці ключавыя доказы па датах і даказаць працяг Second Skin пасля адклікання доступу Рыны.",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.objective.0": "Ілжывыя высновы",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.objective.1": "Ключавыя коды",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.objective.2": "Новы прадмет",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.startBark.speaker": "Эмі",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.startBark.text": "Адзначайце асобна ўсё, што праект і Рына вырашылі за ўладальнікаў. Не змешвайце шкоду.",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.winBark.speaker": "Міку",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.winBark.text": "Лінія сыходзіцца. Рына — выкрадальніца, але Second Skin працягнуўся незалежна ад яе.",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.loseBark.speaker": "Оноэ",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.loseBark.text": "Мы змяшалі даказаныя дзеянні і гіпотэзу пра арганізатара. Перазбіраем часовую лінію.",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.clueTitle": "Працяг Second Skin",
  "match3.level.M3_18_FULL_TIMELINE_PROOF.clueSummary": "Новая маркіроўка і SS-EDGE працягваюцца пасля адклікання доступу Рыны; яе крадзяжы і схаваны эксперымент Куросэ — розныя даказаныя парушэнні.",
  "match3.ingredient.returnConfirmation": "Пацвярджэнне вяртання",
  "match3.ingredient.backupDrive": "Рэзервовы назапашвальнік",
  "match3.ingredient.finalSlide": "Фінальны слайд",
  "match3.clue.CUE_020": "Фармальна закрыта",
  "match3.clue.CUE_021": "Журналы згоды",
  "match3.clue.CUE_022": "Выдаленыя супярэчнасці",
  "match3.bark.fiveMoves.19": "Пяць хадоў. Захоўваем прыватнасць да апошняй ячэйкі.",
  "match3.bark.fiveMoves.20": "Пяць хадоў. Рэзервовая копія павінна выйсці да выдалення.",
  "match3.bark.fiveMoves.21": "Пяць хадоў. Нават зручная версія павінна дажыць да фінальнага слайда.",
  "match3.bark.blockers.19": "Пломбы знятыя. Можна звяраць ананімныя коды.",
  "match3.bark.blockers.20": "Серверныя шлюзы адкрытыя. Журналы даступныя для захавання.",
  "match3.bark.blockers.21": "Пярэчанні прыбраныя. Прэзентацыя становіцца небяспечна гладкай.",
  "match3.bark.ingredient.19": "Пацвярджэнне завершыць прыватную выдачу.",
  "match3.bark.ingredient.20": "Рэзервовы назапашвальнік захоўвае журнал згоды.",
  "match3.bark.ingredient.21": "Фінальны слайд замацоўвае зручную версію.",
  "match3.level.M3_19_PRIVATE_RETURN.title": "Прыватнае вяртанне",
  "match3.level.M3_19_PRIVATE_RETURN.storyAction": "Вярнуць пакеты правільным уладальнікам па ананімных кодах, не раскрываючы чужыя даныя.",
  "match3.level.M3_19_PRIVATE_RETURN.objective.0": "Пломбы вяртання",
  "match3.level.M3_19_PRIVATE_RETURN.objective.1": "Ананімныя коды",
  "match3.level.M3_19_PRIVATE_RETURN.objective.2": "Пацвярджэнне",
  "match3.level.M3_19_PRIVATE_RETURN.startBark.speaker": "Эмі",
  "match3.level.M3_19_PRIVATE_RETURN.startBark.text": "Коды — асобна ад імёнаў. Ніхто не павінен плаціць прыватнасцю за вяртанне сваёй рэчы.",
  "match3.level.M3_19_PRIVATE_RETURN.winBark.speaker": "Оноэ",
  "match3.level.M3_19_PRIVATE_RETURN.winBark.text": "Выдача сыходзіцца. Крадзяжы Рыны закрытыя доказамі і без раскрыцця ўладальнікаў.",
  "match3.level.M3_19_PRIVATE_RETURN.loseBark.speaker": "Міку",
  "match3.level.M3_19_PRIVATE_RETURN.loseBark.text": "Мы змяшалі коды выдачы. Паўтараем — тут памылка сама стане новым парушэннем.",
  "match3.level.M3_19_PRIVATE_RETURN.clueTitle": "Фармальна закрыта",
  "match3.level.M3_19_PRIVATE_RETURN.clueSummary": "Усе скрадзеныя рэчы вернутыя прыватна, а адміністрацыя закрывае серыю крадзяжоў, усклаўшы адказнасць на Рыну, не тлумачачы Second Skin, які працягвае працаваць.",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.title": "Карта згоды",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.storyAction": "Захаваць серверныя журналы Second Skin да выдалення і вывесці рэзервовы назапашвальнік з сэрвіснай зоны.",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.objective.0": "Серверныя шлюзы",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.objective.1": "Журналы згоды",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.objective.2": "Рэзервовая копія",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.startBark.speaker": "Міку",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.startBark.text": "Толькі журнал згоды і рэзервовая копія. Мы расследуем парушэнне, а не выгружаем чужое жыццё.",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.winBark.speaker": "Эмі",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.winBark.text": "Вось яно. Згоду на форму ператварылі ў дазвол на асабістыя рэчы ўжо пасля подпісу.",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.loseBark.speaker": "Оноэ",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.loseBark.text": "Выдаленне апярэджвае капіраванне. Паўтараем і аддаём прыярытэт журналу згоды.",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.clueTitle": "Журналы згоды",
  "match3.level.M3_20_SERVER_CONSENT_LOGS.clueSummary": "Серверныя журналы даказваюць схаваную маркіроўку асабістых рэчаў, падмену межаў згоды і працяг пілота пасля першых сігналаў рызыкі.",
  "match3.level.M3_21_CONVENIENT_CASE.title": "Ідэальны падазраваны",
  "match3.level.M3_21_CONVENIENT_CASE.storyAction": "Сабраць зручныя супадзенні, прыбраць карткі з супярэчнасцямі і падрыхтаваць эфектны, але ілжывы фінальны слайд.",
  "match3.level.M3_21_CONVENIENT_CASE.objective.0": "Зручныя супадзенні",
  "match3.level.M3_21_CONVENIENT_CASE.objective.1": "Пярэчанні",
  "match3.level.M3_21_CONVENIENT_CASE.objective.2": "Фінальны слайд",
  "match3.level.M3_21_CONVENIENT_CASE.startBark.speaker": "Оноэ",
  "match3.level.M3_21_CONVENIENT_CASE.startBark.text": "Я адзначу кожнае пярэчанне, якое мы цяпер прыбіраем. Хаця б паміж сабой не будзем называць гэта доказам.",
  "match3.level.M3_21_CONVENIENT_CASE.winBark.speaker": "Аюкі",
  "match3.level.M3_21_CONVENIENT_CASE.winBark.text": "Слайд ідэальны. І цяпер я вельмі добра бачу, чаму ідэальная гісторыя можа быць няправільнай.",
  "match3.level.M3_21_CONVENIENT_CASE.loseBark.speaker": "Міку",
  "match3.level.M3_21_CONVENIENT_CASE.loseBark.text": "Нават ілжывая версія развалілася. Перазбіраем і глядзім, якія факты даводзіцца хаваць.",
  "match3.level.M3_21_CONVENIENT_CASE.clueTitle": "Выдаленыя супярэчнасці",
  "match3.level.M3_21_CONVENIENT_CASE.clueSummary": "Публічная версія выглядае пераканаўча толькі пасля свядомага выдалення фактаў, якія здымаюць віну са зручнага падазраванага і ўказваюць на Second Skin.",

  // ANM-029B3A — Belarusian VN story slot 0 (VN0001–VN0084 + CHOICE_00 + scenes 00–02).
  "vn.choice.header": "Выбар версіі",
  "vn.choice.prompt": "З чаго пачаць?",
  "vn.choice.A.title": "Спачатку знойдзем другую пацярпелую",
  "vn.choice.A.effect": "Давер крыніц +1",
  "vn.choice.B.title": "Папярэдзім ананімна",
  "vn.choice.B.effect": "Сіла чутак +1",
  "vn.choice.C.title": "Перададзім справу адміністрацыі",
  "vn.choice.C.effect": "Давер Оноэ +1",
  "vn.scene.VN_SCENE_00_PROLOGUE.title": "Клуб, якога амаль няма",
  "vn.scene.VN_SCENE_00_PROLOGUE.location": "Пакой дэтэктыўнага клуба",
  "vn.scene.VN_SCENE_01_E0_PRE.title": "Справа класа U",
  "vn.scene.VN_SCENE_01_E0_PRE.location": "Пакой клуба → распранальня",
  "vn.scene.VN_SCENE_02_E0_POST.title": "Тое, што пакінуў злодзей",
  "vn.scene.VN_SCENE_02_E0_POST.location": "Распранальня лёгкай атлетыкі",
  "vn.line.VN0001.speaker": "РЭЖЫСУРА",
  "vn.line.VN0001.emotion": "FADE IN",
  "vn.line.VN0001.text": "Пасля званка. Вузкі пакой былой кладоўкі; дошка, два крэслы, складны стол і таблічка «Дэтэктыўны клуб», прыклееная паверх слова «Інвентар».",
  "vn.line.VN0002.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0002.emotion": "АСЦЯРОЖНАЯ",
  "vn.line.VN0002.text": "У буклеце гэта называлася «прасторай для студэнцкіх ініцыятыў».",
  "vn.line.VN0003.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0003.emotion": "СУХА",
  "vn.line.VN0003.text": "У буклеце не было швабры за фіранкай.",
  "vn.line.VN0004.speaker": "ОНОЭ",
  "vn.line.VN0004.emotion": "ЗАСЯРОДЖАНАЯ",
  "vn.line.VN0004.text": "Пункт чацвёрты: клуб абавязваецца не праводзіць допыты без згоды ўдзельніка.",
  "vn.line.VN0005.speaker": "АЮКІ",
  "vn.line.VN0005.emotion": "ВЯСЁЛАЯ",
  "vn.line.VN0005.text": "Занадта негатыўна. Напішы: «Мы паважаем права падазраванага на эфектнае з’яўленне».",
  "vn.line.VN0006.speaker": "ОНОЭ",
  "vn.line.VN0006.emotion": "НЕ ПАДЫМАЮЧЫ ВАЧЭЙ",
  "vn.line.VN0006.text": "Гэта не права.",
  "vn.line.VN0007.speaker": "АЮКІ",
  "vn.line.VN0007.emotion": "ЗАДУМЕННАЯ",
  "vn.line.VN0007.text": "Пакуль не права.",
  "vn.line.VN0008.speaker": "МІКУ",
  "vn.line.VN0008.emotion": "НЯЎПЭЎНЕНАЯ",
  "vn.line.VN0008.text": "Прабачце… гэта сход дэтэктыўнага клуба?",
  "vn.line.VN0009.speaker": "АЮКІ",
  "vn.line.VN0009.emotion": "ПАВАРОТ ДА МІКУ",
  "vn.line.VN0009.text": "Залежыць. Ты кліент, сведка ці доўгачаканы трэці ўдзельнік?",
  "vn.line.VN0010.speaker": "МІКУ",
  "vn.line.VN0010.emotion": "ЗБЯНТЭЖАНАЯ",
  "vn.line.VN0010.text": "Я думала спачатку паглядзець.",
  "vn.line.VN0011.speaker": "ОНОЭ",
  "vn.line.VN0011.emotion": "АЦЭНЬВАЕ",
  "vn.line.VN0011.text": "Назіранне — дапушчальная спецыялізацыя.",
  "vn.line.VN0012.speaker": "АЮКІ",
  "vn.line.VN0012.emotion": "ТЭАТРАЛЬНАЯ",
  "vn.line.VN0012.text": "Прынята аднагалосна.",
  "vn.line.VN0013.speaker": "МІКУ",
  "vn.line.VN0013.emotion": "ЗДЗІЎЛЕНАЯ",
  "vn.line.VN0013.text": "Вы яшчэ не галасавалі.",
  "vn.line.VN0014.speaker": "ОНОЭ",
  "vn.line.VN0014.emotion": "НЕЙТРАЛЬНАЯ",
  "vn.line.VN0014.text": "Нас двое. Аднагалоссе ўзнікае хутка.",
  "vn.line.VN0015.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0015.emotion": "ІРАНІЧНАЯ",
  "vn.line.VN0015.text": "Я прыйшла маляваць афішу. Праз сорак секунд атрымала пасаду.",
  "vn.line.VN0016.speaker": "АЮКІ",
  "vn.line.VN0016.emotion": "З ЛІСТОМ",
  "vn.line.VN0016.text": "Засталося выбраць назву: «Вока Сэйрана», «Тры алібі» або «Красуні дэдукцыі».",
  "vn.line.VN0017.speaker": "ОНОЭ",
  "vn.line.VN0017.emotion": "ХОЛАДНА",
  "vn.line.VN0017.text": "Апошняя назва зніжае нашу доказную каштоўнасць.",
  "vn.line.VN0018.speaker": "МІКУ",
  "vn.line.VN0018.emotion": "РАЗГЛЯДАЕ ТАБЛІЧКУ",
  "vn.line.VN0018.text": "А афіцыйны статус у клуба ёсць?",
  "vn.line.VN0019.speaker": "ОНОЭ",
  "vn.line.VN0019.emotion": "ПАЎЗА",
  "vn.line.VN0019.text": "Заяўка амаль гатовая.",
  "vn.line.VN0020.speaker": "АЮКІ",
  "vn.line.VN0020.emotion": "ЦІХА ДА МІКУ",
  "vn.line.VN0020.text": "Гэта хімічна дакладнае «не».",
  "vn.line.VN0021.speaker": "РЭЖЫСУРА",
  "vn.line.VN0021.emotion": "SFX: ТРЫ ХУТКІЯ СТУКІ",
  "vn.line.VN0021.text": "Дзверы адчыняюцца раней, чым Оноэ паспявае адказаць.",
  "vn.line.VN0022.speaker": "ЭМІ",
  "vn.line.VN0022.emotion": "УСТРЫВОЖАНАЯ",
  "vn.line.VN0022.text": "Мне сказалі, вы знаходзіце рэчы, якіх адміністрацыя аддае перавагу не заўважаць.",
  "vn.line.VN0023.speaker": "ОНОЭ",
  "vn.line.VN0023.emotion": "ДЗЕЛАВАЯ",
  "vn.line.VN0023.text": "Сядайце. Імя, клуб, час, калі заўважылі знікненне.",
  "vn.line.VN0024.speaker": "ЭМІ",
  "vn.line.VN0024.emotion": "НЕРВОВАЯ",
  "vn.line.VN0024.text": "Эмі Такахасі. Лёгкая атлетыка. І можна спачатку зачыніць дзверы?",
  "vn.line.VN0025.speaker": "РЭЖЫСУРА",
  "vn.line.VN0025.emotion": "CLOSE ON DOOR",
  "vn.line.VN0025.text": "Міку зачыняе дзверы; Аюкі пераварочвае таблічку чыстым бокам вонкі.",
  "vn.line.VN0026.speaker": "ЭМІ",
  "vn.line.VN0026.emotion": "ЗБЯНТЭЖАНАЯ",
  "vn.line.VN0026.text": "З маёй шафкі знікла бялізна. Два камплекты.",
  "vn.line.VN0027.speaker": "АЮКІ",
  "vn.line.VN0027.emotion": "ІМГНЕННА СУР'ЁЗНАЯ",
  "vn.line.VN0027.text": "Добра. Жарты потым. Шафка была замкнёная?",
  "vn.line.VN0028.speaker": "ЭМІ",
  "vn.line.VN0028.emotion": "КІВАЕ",
  "vn.line.VN0028.text": "Так. Грошы, гадзіннік і новыя красоўкі засталіся.",
  "vn.line.VN0029.speaker": "ОНОЭ",
  "vn.line.VN0029.emotion": "ПІША",
  "vn.line.VN0029.text": "Папярэдняя катэгорыя — U.",
  "vn.line.VN0030.speaker": "АЮКІ",
  "vn.line.VN0030.emotion": "ЗАЦІКАЎЛЕНАЯ",
  "vn.line.VN0030.text": "«Ультрадалікатнае»?",
  "vn.line.VN0031.speaker": "ОНОЭ",
  "vn.line.VN0031.emotion": "НЕЙТРАЛЬНАЯ",
  "vn.line.VN0031.text": "Undergarment.",
  "vn.line.VN0032.speaker": "ЭМІ",
  "vn.line.VN0032.emotion": "РАЗДРАЖНЁНАЯ",
  "vn.line.VN0032.text": "Можна хаця б пяць хвілін не ператвараць мае трусікі ў назву стрыму?",
  "vn.line.VN0033.speaker": "АЮКІ",
  "vn.line.VN0033.emotion": "ПРЫМІРАЛЬНАЯ",
  "vn.line.VN0033.text": "Можна. Таймер пайшоў.",
  "vn.line.VN0034.speaker": "МІКУ",
  "vn.line.VN0034.emotion": "МЯККА",
  "vn.line.VN0034.text": "Хто яшчэ ведаў код шафкі?",
  "vn.line.VN0035.speaker": "ЭМІ",
  "vn.line.VN0035.emotion": "ДУМАЕ",
  "vn.line.VN0035.text": "Ніхто. Але раніцай рэчы забіралі ў цэнтральную пральню, потым вярнулі перад трэніроўкай.",
  "vn.line.VN0036.speaker": "ОНОЭ",
  "vn.line.VN0036.emotion": "ПАДЫМАЕ ВОЧЫ",
  "vn.line.VN0036.text": "Значыць, доступ меў не толькі той, хто адкрыў шафку.",
  "vn.line.VN0037.speaker": "ЭМІ",
  "vn.line.VN0037.emotion": "ЦІХА",
  "vn.line.VN0037.text": "Я не хачу, каб увесь каледж абмяркоўваў, што менавіта знікла.",
  "vn.line.VN0038.speaker": "АЮКІ",
  "vn.line.VN0038.emotion": "З ТЭЛЕФОНАМ",
  "vn.line.VN0038.text": "Ананімнае папярэджанне абароніць астатніх. Без імя і падрабязнасцяў.",
  "vn.line.VN0039.speaker": "ОНОЭ",
  "vn.line.VN0039.emotion": "ПЯРЭЧЫЦЬ",
  "vn.line.VN0039.text": "Спачатку трэба зарэгістраваць інцыдэнт і паведаміць студсавету.",
  "vn.line.VN0040.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0040.emotion": "НАПРУЖАНАЯ",
  "vn.line.VN0040.text": "Хвіліна ў клубе — і мне ўжо прапануюць выбіраць паміж чуткай, бланкам і чалавекам, які баіцца і таго, і другога.",
  "vn.line.VN0041A.speaker": "МІКУ",
  "vn.line.VN0041A.emotion": "БОЛЬШ УПЭЎНЕНА",
  "vn.line.VN0041A.text": "Спачатку праверым, ці адзінкавы гэта выпадак. Без публікацый і імёнаў.",
  "vn.line.VN0042A.speaker": "ЭМІ",
  "vn.line.VN0042A.emotion": "З ПАЛЁГКАЙ",
  "vn.line.VN0042A.text": "Я спытаю ў суседкі па камандзе. Учора яна неяк дзіўна пералічвала рэчы.",
  "vn.line.VN0043A.speaker": "ОНОЭ",
  "vn.line.VN0043A.emotion": "ПРЫМАЕ",
  "vn.line.VN0043A.text": "Незалежнае пацвярджэнне карыснейшае за чутку.",
  "vn.line.VN0044A.speaker": "АЮКІ",
  "vn.line.VN0044A.emotion": "ПРЫБІРАЕ ТЭЛЕФОН",
  "vn.line.VN0044A.text": "Добра. Мой сенсацыйны загаловак паляжыць тварам уніз.",
  "vn.line.VN0045A.speaker": "РЭЖЫСУРА",
  "vn.line.VN0045A.emotion": "UI MESSAGE",
  "vn.line.VN0045A.text": "Эмі атрымлівае адказ: у другой спартсменкі пасля той жа партыі мыцця знік адзін прадмет.",
  "vn.line.VN0046A.speaker": "СІСТЭМА",
  "vn.line.VN0046A.emotion": "VARIABLE",
  "vn.line.VN0046A.text": "{approach=verify; source_trust+1; bonus_laundry_detail=true}",
  "vn.line.VN0041B.speaker": "МІКУ",
  "vn.line.VN0041B.emotion": "РАШУЧАЯ",
  "vn.line.VN0041B.text": "Папярэджанне патрэбнае. Але без пераліку рэчаў і без версіі пра вінаватага.",
  "vn.line.VN0042B.speaker": "АЮКІ",
  "vn.line.VN0042B.emotion": "АЖЫЎЛЕНАЯ",
  "vn.line.VN0042B.text": "«Праверце шафкі пасля цэнтралізаванага мыцця». Суха, карысна, амаль без мяне.",
  "vn.line.VN0043B.speaker": "ЭМІ",
  "vn.line.VN0043B.emotion": "АСЦЯРОЖНАЯ",
  "vn.line.VN0043B.text": "Калі сапраўды без імя… добра.",
  "vn.line.VN0044B.speaker": "РЭЖЫСУРА",
  "vn.line.VN0044B.emotion": "UI POST / NOTIFICATIONS",
  "vn.line.VN0044B.text": "Пост атрымлівае некалькі адказаў; у адным з іх згадваюць фатографа Кэнтаро каля службовага калідора.",
  "vn.line.VN0045B.speaker": "ОНОЭ",
  "vn.line.VN0045B.emotion": "НЕ ЎХВАЛЯЕ",
  "vn.line.VN0045B.text": "Цяпер у нас ёсць сведчанне і некантраляваная інтэрпрэтацыя сведчання.",
  "vn.line.VN0046B.speaker": "СІСТЭМА",
  "vn.line.VN0046B.emotion": "VARIABLE",
  "vn.line.VN0046B.text": "{approach=warn; rumor_heat+1}",
  "vn.line.VN0041C.speaker": "МІКУ",
  "vn.line.VN0041C.emotion": "АСЦЯРОЖНАЯ",
  "vn.line.VN0041C.text": "Спачатку зарэгіструем знікненне. Калі выпадкі паўторацца, папяровы след спатрэбіцца.",
  "vn.line.VN0042C.speaker": "ОНОЭ",
  "vn.line.VN0042C.emotion": "УХВАЛЯЕ",
  "vn.line.VN0042C.text": "Карэктна.",
  "vn.line.VN0043C.speaker": "РЭЖЫСУРА",
  "vn.line.VN0043C.emotion": "PHONE CALL / SPLIT PORTRAIT MAYU",
  "vn.line.VN0043C.text": "Оноэ ўключае гучную сувязь з Маю Хаясакай са студсавета.",
  "vn.line.VN0044C.speaker": "МАЮ",
  "vn.line.VN0044C.emotion": "ВЕТЛІВА-НАПРУЖАНАЯ",
  "vn.line.VN0044C.text": "Зарэгіструйце гэта як памылку сартавання. Калі ласка, не выкарыстоўвайце слова «крадзеж», пакуль няма доказаў.",
  "vn.line.VN0045C.speaker": "ЭМІ",
  "vn.line.VN0045C.emotion": "ХОЛАДНА",
  "vn.line.VN0045C.text": "Мая шафка сама памылілася?",
  "vn.line.VN0046C.speaker": "МАЮ",
  "vn.line.VN0046C.emotion": "ПАЎЗА",
  "vn.line.VN0046C.text": "Я дашлю журнал доступу. І прашу праводзіць праверку ціха.",
  "vn.line.VN0047C.speaker": "СІСТЭМА",
  "vn.line.VN0047C.emotion": "VARIABLE",
  "vn.line.VN0047C.text": "{approach=report; onoe_trust+1}",
  "vn.line.VN0048.speaker": "РЭЖЫСУРА",
  "vn.line.VN0048.emotion": "CUT TO BG_LOCKER_ATHLETICS_DAY",
  "vn.line.VN0048.text": "Шафка Эмі адкрытая. Рэчы ляжаць бязладна, але дарагія прадметы добра відаць.",
  "vn.line.VN0049.speaker": "АЮКІ",
  "vn.line.VN0049.emotion": "У ПАЛЬЧАТКАХ",
  "vn.line.VN0049.text": "Я гатовая працаваць з доказамі класа U.",
  "vn.line.VN0050.speaker": "ЭМІ",
  "vn.line.VN0050.emotion": "ПАПЯРЭДЖВАЕ",
  "vn.line.VN0050.text": "Калі дасі ім імёны, я пайду.",
  "vn.line.VN0051.speaker": "АЮКІ",
  "vn.line.VN0051.emotion": "ПАКОРЛІВАЯ",
  "vn.line.VN0051.text": "Нумары. Толькі строгія нумары.",
  "vn.line.VN0052.speaker": "ОНОЭ",
  "vn.line.VN0052.emotion": "ПАКАЗВАЕ НА ШАФКУ",
  "vn.line.VN0052.text": "Не шукаем «падазронае». Фіксуем, што засталося, што знікла і што праходзіла апрацоўку.",
  "vn.line.VN0053.speaker": "МІКУ",
  "vn.line.VN0053.emotion": "УВАЖЛІВАЯ",
  "vn.line.VN0053.text": "Красоўкі новыя. Карункавы камплект ляжыць зверху. Калі злодзей выбіраў самае дарагое ці прыкметнае, ён выбіраў дзіўна.",
  "vn.line.VN0054.speaker": "ОНОЭ",
  "vn.line.VN0054.emotion": "ЗАЦІКАЎЛЕНАЯ",
  "vn.line.VN0054.text": "Добрае назіранне. Праверым кожную катэгорыю.",
  "vn.line.VN0055.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0055.emotion": "ЗАСЯРОДЖАНАЯ",
  "vn.line.VN0055.text": "Першая сапраўдная справа. І першая задача — прафесійна рассартаваць бялізну незнаёмай дзяўчыны.",
  "vn.line.VN0056.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0056.emotion": "СУХА",
  "vn.line.VN0056.text": "У буклеце пра гэта таксама не было.",
  "vn.line.VN0057.speaker": "РЭЖЫСУРА",
  "vn.line.VN0057.emotion": "TRANSITION TO MATCH-3",
  "vn.line.VN0057.text": "Буйны план адкрытай шафкі ператвараецца ў поле.",
  "vn.line.VN0058.speaker": "РЭЖЫСУРА",
  "vn.line.VN0058.emotion": "CLOSE UP: SERVICE TAG",
  "vn.line.VN0058.text": "На ўнутраным баку прадмета, што застаўся, — свежая сэрвісная бірка цэнтральнай пральні.",
  "vn.line.VN0059.speaker": "ОНОЭ",
  "vn.line.VN0059.emotion": "ЗАСЯРОДЖАНАЯ",
  "vn.line.VN0059.text": "Квітанцыя пацвярджае адну партыю. Але з яе зніклі толькі два прадметы.",
  "vn.line.VN0060.speaker": "АЮКІ",
  "vn.line.VN0060.emotion": "З КАРУНКАВЫМ ПАКЕТАМ-ДОКАЗАМ",
  "vn.line.VN0060.text": "Значыць, у злачынцы дзіўна спецыфічны густ.",
  "vn.line.VN0061.speaker": "ОНОЭ",
  "vn.line.VN0061.emotion": "СУР'ЁЗНА",
  "vn.line.VN0061.text": "Версія: асабістая эстэтычная селекцыя.",
  "vn.line.VN0062.speaker": "АЮКІ",
  "vn.line.VN0062.emotion": "ЗАХОПЛЕНАЯ",
  "vn.line.VN0062.text": "Ты толькі што навукова сказала «злодзей выбірае трусікі на свой густ».",
  "vn.line.VN0063.speaker": "МІКУ",
  "vn.line.VN0063.emotion": "ГЛЯДЗІЦЬ У ШАФКУ",
  "vn.line.VN0063.text": "Але самы дарагі камплект застаўся. І самы прыкметны таксама.",
  "vn.line.VN0064.speaker": "ЭМІ",
  "vn.line.VN0064.emotion": "СУХА",
  "vn.line.VN0064.text": "Дзякуй, што ацанілі асартымент.",
  "vn.line.VN0065.speaker": "МІКУ",
  "vn.line.VN0065.emotion": "ЗБЯНТЭЖАНАЯ",
  "vn.line.VN0065.text": "Прабач. Я пра выбар злодзея, не пра твой.",
  "vn.line.VN0066.speaker": "ЭМІ",
  "vn.line.VN0066.emotion": "МЯКЧЭЙ",
  "vn.line.VN0066.text": "Разумею. Проста… запішыце гэта без характарыстык.",
  "vn.line.VN0067.speaker": "ОНОЭ",
  "vn.line.VN0067.emotion": "ВЫПРАЎЛЯЕ ЗАПІС",
  "vn.line.VN0067.text": "Факт: знікненне выбарачнае. Цана, колер і прыкметнасць яго не тлумачаць.",
  "vn.line.VN0068.speaker": "РЭЖЫСУРА",
  "vn.line.VN0068.emotion": "DOSSIER UNLOCK",
  "vn.line.VN0068.text": "Адкрываецца экран дасье; картка доказу замацоўваецца асобна ад версіі.",
  "vn.line.VN0069.speaker": "СІСТЭМА",
  "vn.line.VN0069.emotion": "DOSSIER",
  "vn.line.VN0069.text": "{dossier_unlocked=true; ADD CUE_001_SELECTIVE_THEFT}",
  "vn.line.VN0070.speaker": "АЮКІ",
  "vn.line.VN0070.emotion": "З ТЭЛЕФОНАМ",
  "vn.line.VN0070.text": "Эмі даслала фотаздымкі з ранішняй трэніроўкі. На адным ёсць нешта карыснае.",
  "vn.line.VN0071.speaker": "РЭЖЫСУРА",
  "vn.line.VN0071.emotion": "INSERT: PHONE PHOTO",
  "vn.line.VN0071.text": "На здымку Кэнтаро стаіць каля службовага калідора і глядзіць на каляску пральні.",
  "vn.line.VN0072.speaker": "ЭМІ",
  "vn.line.VN0072.emotion": "НАПРУЖАНАЯ",
  "vn.line.VN0072.text": "Ён здымаў нас увесь тыдзень.",
  "vn.line.VN0073.speaker": "ОНОЭ",
  "vn.line.VN0073.emotion": "АНАЛІТЫЧНАЯ",
  "vn.line.VN0073.text": "Доступ да раскладу, прысутнасць каля месца і прафесійная цікавасць да выявы адзення.",
  "vn.line.VN0074.speaker": "МІКУ",
  "vn.line.VN0074.emotion": "СУМНЯВАЕЦЦА",
  "vn.line.VN0074.text": "Апошні пункт гучыць шырэй, чым даказвае фотаздымак.",
  "vn.line.VN0075.speaker": "АЮКІ",
  "vn.line.VN0075.emotion": "НАБЛІЖАЕ ФОТА",
  "vn.line.VN0075.text": "Затое яго погляд кажа: «Я ведаю, што ў гэтай калясцы».",
  "vn.line.VN0076.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0076.emotion": "ІРАНІЧНАЯ",
  "vn.line.VN0076.text": "Магчыма, яго погляд казаў: «Чаму мяне зноў фатаграфуюць на маю ж камеру».",
  "vn.line.VN0077.speaker": "ЭМІ",
  "vn.line.VN0077.emotion": "ДАВЕРЛІВАЯ",
  "vn.line.VN0077.text": "Суседка пацвердзіла: яе рэчы таксама былі ў ранішняй партыі. Я перашлю нумар каляскі.",
  "vn.line.VN0078.speaker": "АЮКІ",
  "vn.line.VN0078.emotion": "ВІНАВАТА",
  "vn.line.VN0078.text": "У каментарыях яго ўжо назвалі «фатографам трусікаў». Я гэтага не пісала, але пост быў мой.",
  "vn.line.VN0079.speaker": "ОНОЭ",
  "vn.line.VN0079.emotion": "З ЖУРНАЛАМ",
  "vn.line.VN0079.text": "Маю даслала дадзеныя доступу. Кэнтаро прайшоў у службовы калідор у 09:12.",
  "vn.line.VN0080.speaker": "ОНОЭ",
  "vn.line.VN0080.emotion": "РАШУЧАЯ",
  "vn.line.VN0080.text": "Пагаворым з ім да таго, як версія стане прысудам.",
  "vn.line.VN0081.speaker": "АЮКІ",
  "vn.line.VN0081.emotion": "ПА-ДЗЕЛАВОМУ",
  "vn.line.VN0081.text": "І да таго, як ён паспее прыбраць калекцыю.",
  "vn.line.VN0082.speaker": "МІКУ",
  "vn.line.VN0082.emotion": "ЦІХА",
  "vn.line.VN0082.text": "Мы пакуль не ведаем, што калекцыя існуе.",
  "vn.line.VN0083.speaker": "АЮКІ",
  "vn.line.VN0083.emotion": "УЖО КАЛЯ ДЗВЯРЭЙ",
  "vn.line.VN0083.text": "Таму і ідзём правяраць.",
  "vn.line.VN0084.speaker": "РЭЖЫСУРА",
  "vn.line.VN0084.emotion": "EPISODE CARD",
  "vn.line.VN0084.text": "«Эпізод 1 — Чужая калекцыя»",

  // ANM-029B3B — Belarusian VN story slot 1 (canonical runtime graph: VN0085–VN0142 + scenes 03–04).
  "vn.scene.VN_SCENE_03_E1_PRE.title": "Пакой, які ўсё тлумачыць занадта дрэнна",
  "vn.scene.VN_SCENE_03_E1_PRE.location": "Кватэра Кэнтаро",
  "vn.scene.VN_SCENE_04_E1_POST.title": "Манекен з найлепшым алібі",
  "vn.scene.VN_SCENE_04_E1_POST.location": "Кватэра Кэнтаро",

  "vn.line.VN0085.speaker": "РЭЖЫСУРА",
  "vn.line.VN0085.emotion": "FADE IN",
  "vn.line.VN0085.text": "Невялікая кватэра адначасова служыць фотастудыяй. Скрынкі, стойкі для святла, чахлы і два непразрыстыя мяшкі з адзеннем.",
  "vn.line.VN0086.speaker": "КЭНТАРО",
  "vn.line.VN0086.emotion": "АБАРАНЯЕЦЦА",
  "vn.line.VN0086.text": "Я ўжо сказаў: гэта не маё.",
  "vn.line.VN0087.speaker": "АЮКІ",
  "vn.line.VN0087.emotion": "ЗЗЯЕ",
  "vn.line.VN0087.text": "Цудоўны пачатак тлумачэння.",
  "vn.line.VN0088.speaker": "КЭНТАРО",
  "vn.line.VN0088.emotion": "ПАНУРА",
  "vn.line.VN0088.text": "Мне гэта далі.",
  "vn.line.VN0089.speaker": "АЮКІ",
  "vn.line.VN0089.emotion": "ДА МІКУ",
  "vn.line.VN0089.text": "І становіцца ўсё лепш.",
  "vn.line.VN0090.speaker": "КЭНТАРО",
  "vn.line.VN0090.emotion": "СПРАБУЕ ТЛУМАЧЫЦЬ",
  "vn.line.VN0090.text": "Для здымкі. Я збіраўся зняць гэта ўначы.",
  "vn.line.VN0091.speaker": "РЭЖЫСУРА",
  "vn.line.VN0091.emotion": "КАМЕДЫЙНАЯ ПАЎЗА",
  "vn.line.VN0091.text": "Усе трое моўчкі глядзяць на яго.",
  "vn.line.VN0092.speaker": "КЭНТАРО",
  "vn.line.VN0092.emotion": "ЗАКРЫВАЕ ТВАР",
  "vn.line.VN0092.text": "Адзенне. На манекенах. Начную рэкламную здымку.",
  "vn.line.VN0093.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0093.emotion": "СА СПАЧУВАННЕМ",
  "vn.line.VN0093.text": "У Кэнтаро быў рэдкі талент: кожнае наступнае ўдакладненне гучала як новае абвінавачанне.",
  "vn.line.VN0094.speaker": "ОНОЭ",
  "vn.line.VN0094.emotion": "З НАТАТНІКАМ",
  "vn.line.VN0094.text": "Чаму мяшкі дома, а не ў студыі?",
  "vn.line.VN0095.speaker": "КЭНТАРО",
  "vn.line.VN0095.emotion": "ПАКАЗВАЕ НА СКРЫНКІ",
  "vn.line.VN0095.text": "Студыю затапіла. Я вывез рэквізіт і згубіў карту памяці з вопісам.",
  "vn.line.VN0096.speaker": "АЮКІ",
  "vn.line.VN0096.emotion": "ПРЫЖМУРЫЛАСЯ",
  "vn.line.VN0096.text": "Вельмі зручная страта.",
  "vn.line.VN0097.speaker": "МІКУ",
  "vn.line.VN0097.emotion": "РАЗГЛЯДАЕ МЯШОК",
  "vn.line.VN0097.text": "Тут нумар `PS-14`. Такі ж шрыфт на абсталяванні каледжа.",
  "vn.line.VN0098.speaker": "КЭНТАРО",
  "vn.line.VN0098.emotion": "З ПАЛЁГКАЙ",
  "vn.line.VN0098.text": "Бо гэта інвентар фотастудыі!",
  "vn.line.VN0099.speaker": "ОНОЭ",
  "vn.line.VN0099.emotion": "СТРЫМАНА",
  "vn.line.VN0099.text": "Нумар пацвярджае паходжанне мяшка, але не кожнага прадмета ў ім.",
  "vn.line.VN0100.speaker": "КЭНТАРО",
  "vn.line.VN0100.emotion": "РАЗДРАЖНЁНЫ",
  "vn.line.VN0100.text": "Знойдзеце карту — атрымаеце вопіс, таймкоды і арыгіналы. Тады прыбераце маё імя з вашай справы.",
  "vn.line.VN0101.speaker": "КЭНТАРО",
  "vn.line.VN0101.emotion": "ПАКАЗВАЕ ТЭЛЕФОН",
  "vn.line.VN0101.text": "І з паста. Мне ўжо тры разы даслалі лупу і эмодзі трусікаў.",
  "vn.line.VN0102.speaker": "АЮКІ",
  "vn.line.VN0102.emotion": "ВІНАВАТА, БЕЗ ЖАРТАЎ",
  "vn.line.VN0102.text": "Гэта наступства нашага паста. Калі здымкі цябе апраўдаюць, я выпраўлю публікацыю.",
  "vn.line.VN0103.speaker": "МІКУ",
  "vn.line.VN0103.emotion": "ПАКАЗВАЕ НУМАР КАЛЯСКІ",
  "vn.line.VN0103.text": "Эмі дала нумар партыі. Мы праверым толькі рэчы з патрэбнага прамежку.",
  "vn.line.VN0104.speaker": "ОНОЭ",
  "vn.line.VN0104.emotion": "ПАКАЗВАЕ ЖУРНАЛ",
  "vn.line.VN0104.text": "У нас ёсць афіцыйны таймкод. Абмяжуем агляд звязанымі мяшкамі.",
  "vn.line.VN0105.speaker": "КЭНТАРО",
  "vn.line.VN0105.emotion": "УЗДЫХАЕ",
  "vn.line.VN0105.text": "Не адкрывайце чырвоную скрынку рэзка.",
  "vn.line.VN0106.speaker": "АЮКІ",
  "vn.line.VN0106.emotion": "ПАДАЗРОНАЯ",
  "vn.line.VN0106.text": "Чаму?",
  "vn.line.VN0107.speaker": "КЭНТАРО",
  "vn.line.VN0107.emotion": "СТОМЛЕНА",
  "vn.line.VN0107.text": "Там спружынны фон. І ён ужо перамог двух першакурснікаў.",
  "vn.line.VN0108.speaker": "РЭЖЫСУРА",
  "vn.line.VN0108.emotion": "SFX: ШЧАЛК / ФОН РАСКРЫВАЕЦЦА",
  "vn.line.VN0108.text": "Аюкі дакранаецца да зашчапкі; ружовы фон раскрываецца і прыціскае яе да сцяны.",
  "vn.line.VN0109.speaker": "АЮКІ",
  "vn.line.VN0109.emotion": "З-ЗА ФОНУ",
  "vn.line.VN0109.text": "Падазраваны ўзброены дэкарацыямі.",
  "vn.line.VN0110.speaker": "МІКУ",
  "vn.line.VN0110.emotion": "СТРЫМЛІВАЕ СМЕХ",
  "vn.line.VN0110.text": "Запішам пасля інвентарызацыі.",
  "vn.line.VN0111.speaker": "ОНОЭ",
  "vn.line.VN0111.emotion": "РАЗМЯРКОЎВАЕ ЗОНЫ",
  "vn.line.VN0111.text": "Міку — маркіроўка. Аюкі — скрынкі. Я — часавая лінія. Шукаем карту памяці, а не пацвярджэнне любімай версіі.",
  "vn.line.VN0112.speaker": "АЮКІ",
  "vn.line.VN0112.emotion": "ВЫБІРАЕЦЦА",
  "vn.line.VN0112.text": "Мая любімая версія толькі што на мяне напала.",
  "vn.line.VN0113.speaker": "РЭЖЫСУРА",
  "vn.line.VN0113.emotion": "TRANSITION TO MATCH-3",
  "vn.line.VN0113.text": "Камера праходзіць па скрынках і ператвараецца ў гульнявое поле.",
  "vn.line.VN0114.speaker": "РЭЖЫСУРА",
  "vn.line.VN0114.emotion": "INSERT: ГАЛЕРЭЯ КАРТЫ ПАМЯЦІ",
  "vn.line.VN0114.text": "На экране — здымачныя лісты, таймкоды і кадры з манекенамі.",
  "vn.line.VN0115.speaker": "КЭНТАРО",
  "vn.line.VN0115.emotion": "СКРЭШЧВАЕ РУКІ",
  "vn.line.VN0115.text": "Мяшок `PS-14`. Кампанія крамы спартыўнага адзення. Дата, уладальнік, вяртанне.",
  "vn.line.VN0116.speaker": "АЮКІ",
  "vn.line.VN0116.emotion": "ДАСТАЕ СПАРТЫЎНЫ БЮСТГАЛЬТАР У ПАКЕЦЕ",
  "vn.line.VN0116.text": "А галоўны трафей ператрусу?",
  "vn.line.VN0117.speaker": "КЭНТАРО",
  "vn.line.VN0117.emotion": "ГАРТАЕ ФОТА",
  "vn.line.VN0117.text": "Касцюм талісмана. Кадр сорак сем.",
  "vn.line.VN0118.speaker": "РЭЖЫСУРА",
  "vn.line.VN0118.emotion": "INSERT: МАНЕКЕН-ТАЛІСМАН",
  "vn.line.VN0118.text": "На фота спартыўны бюстгальтар надзеты паверх майкі на вуглаваты манекен-талісман.",
  "vn.line.VN0119.speaker": "МІКУ",
  "vn.line.VN0119.emotion": "НЕЙТРАЛЬНА",
  "vn.line.VN0119.text": "Манекен выглядае ўпэўненей за ўсіх нас.",
  "vn.line.VN0120.speaker": "АЮКІ",
  "vn.line.VN0120.emotion": "АЦЭНЬВАЕ",
  "vn.line.VN0120.text": "У яго правільная пастава і чыстае сумленне.",
  "vn.line.VN0121.speaker": "ОНОЭ",
  "vn.line.VN0121.emotion": "ПРАВЯРАЕ ТАЙМКОД",
  "vn.line.VN0121.text": "У момант знікнення Кэнтаро здымаў тэнісны корт. Дваццаць хвілін бесперапынных кадраў.",
  "vn.line.VN0122.speaker": "КЭНТАРО",
  "vn.line.VN0122.emotion": "КОРОТКА",
  "vn.line.VN0122.text": "І?",
  "vn.line.VN0123.speaker": "ОНОЭ",
  "vn.line.VN0123.emotion": "З ДОШКАЙ НА ТЭЛЕФОНЕ",
  "vn.line.VN0123.text": "Верагоднасць асабістага ўдзелу зніжаецца з 87 да 12 працэнтаў.",
  "vn.line.VN0124.speaker": "КЭНТАРО",
  "vn.line.VN0124.emotion": "НЕ ВЕРЫЦЬ",
  "vn.line.VN0124.text": "Гэта тваё прабачэнне?",
  "vn.line.VN0125.speaker": "ОНОЭ",
  "vn.line.VN0125.emotion": "СУР'ЁЗНА",
  "vn.line.VN0125.text": "Гэта істотнае выпраўленне.",
  "vn.line.VN0126.speaker": "МІКУ",
  "vn.line.VN0126.emotion": "ЦВЁРДА",
  "vn.line.VN0126.text": "Мы памыліліся. Прабач.",
  "vn.line.VN0127.speaker": "АЮКІ",
  "vn.line.VN0127.emotion": "ШЧЫРАЯ",
  "vn.line.VN0127.text": "Я абнаўлю пост з алібі і выдалю абвінаваўчыя каментарыі.",
  "vn.line.VN0128.speaker": "АЮКІ",
  "vn.line.VN0128.emotion": "КРЫХУ ЦІШЭЙ",
  "vn.line.VN0128.text": "І я не буду рабіць загаловак з таго, чаго мы не даказалі.",
  "vn.line.VN0129.speaker": "КЭНТАРО",
  "vn.line.VN0129.emotion": "МЯКЧЭЙ",
  "vn.line.VN0129.text": "Тады паглядзіце апошнія кадры каля службовага ўваходу.",
  "vn.line.VN0130.speaker": "РЭЖЫСУРА",
  "vn.line.VN0130.emotion": "INSERT: ПАСЛЯДОЎНАСЦЬ З СЭРВІСНАЙ КАЛЯСКАЙ",
  "vn.line.VN0130.text": "Тры паслядоўныя здымкі: каляска пральні пад'язджае да трэніроўкі і ад'язджае пасля яе.",
  "vn.line.VN0131.speaker": "МІКУ",
  "vn.line.VN0131.emotion": "УВАЖЛІВАЯ",
  "vn.line.VN0131.text": "На першым кадры мяшок поўны. На другім пломба ўжо іншага колеру.",
  "vn.line.VN0132.speaker": "ОНОЭ",
  "vn.line.VN0132.emotion": "ЗАЦІКАЎЛЕНАЯ",
  "vn.line.VN0132.text": "Паміж кадрамі прайшло дзевяць хвілін. Каляска — частка часовай лініі.",
  "vn.line.VN0133.speaker": "КЭНТАРО",
  "vn.line.VN0133.emotion": "ПАКАЗВАЕ",
  "vn.line.VN0133.text": "Я глядзеў на яе, бо супрацоўнік зачапіў маю стойку і нават не спыніўся.",
  "vn.line.VN0134.speaker": "АЮКІ",
  "vn.line.VN0134.emotion": "УЗДЫХАЕ",
  "vn.line.VN0134.text": "Самае нявіннае тлумачэнне зноў аказалася самым сумным.",
  "vn.line.VN0135.speaker": "МІКУ",
  "vn.line.VN0135.emotion": "З ЛЁГКАЙ УСМЕШКАЙ",
  "vn.line.VN0135.text": "Затое фатаграфія карысная.",
  "vn.line.VN0136.speaker": "СІСТЭМА",
  "vn.line.VN0136.emotion": "DOSSIER",
  "vn.line.VN0136.text": "{ADD CUE_002_SERVICE_CART; SET SUS_KENTARO=cleared}",
  "vn.line.VN0137.speaker": "РЭЖЫСУРА",
  "vn.line.VN0137.emotion": "SFX: MESSAGE",
  "vn.line.VN0137.text": "На тэлефоне Аюкі з'яўляецца тэрміновае паведамленне ад клуба плавання.",
  "vn.line.VN0138.speaker": "АЮКІ",
  "vn.line.VN0138.emotion": "ЧЫТАЕ",
  "vn.line.VN0138.text": "«Пасля вячэрняй трэніроўкі знікла бялізна. Зноў. І шмат».",
  "vn.line.VN0139.speaker": "ОНОЭ",
  "vn.line.VN0139.emotion": "УЖО ЗБІРАЕЦЦА",
  "vn.line.VN0139.text": "Новы выпадак канчаткова здымае падазрэнні з Кэнтаро.",
  "vn.line.VN0140.speaker": "КЭНТАРО",
  "vn.line.VN0140.emotion": "СУХА",
  "vn.line.VN0140.text": "Рады, што сапраўдны злодзей выконвае дэдлайны.",
  "vn.line.VN0141.speaker": "РЭЖЫСУРА",
  "vn.line.VN0141.emotion": "EPISODE CARD",
  "vn.line.VN0141.text": "«Эпізод 2 — Мокрыя паказанні»",
  "vn.line.VN0142.speaker": "РЭЖЫСУРА",
  "vn.line.VN0142.emotion": "FADE IN / AMBIENT POOL",
  "vn.line.VN0142.text": "Пустая распранальня пасля трэніроўкі. На лаўках мокрыя ручнікі, з душавой паўзе пена.",

  // ANM-029B3C — Belarusian VN story slot 2 (canonical runtime graph: VN0143–VN0191 + scenes 05–06).
  "vn.scene.VN_SCENE_05_E2_PRE.title": "Мокрыя паказанні",
  "vn.scene.VN_SCENE_05_E2_PRE.location": "Распранальня клуба плавання",
  "vn.scene.VN_SCENE_06_E2_POST.title": "Табліца без густу",
  "vn.scene.VN_SCENE_06_E2_POST.location": "Распранальня клуба плавання",
  "vn.line.VN0143.speaker": "АЮКІ",
  "vn.line.VN0143.emotion": "ЛЯ ДОШКІ СА СХЕМАЙ",
  "vn.line.VN0143.text": "Профіль злачынцы: дзейнічае ўпэўнена, любіць рызыку і атачае сябе тканінай.",
  "vn.line.VN0144.speaker": "МІКУ",
  "vn.line.VN0144.emotion": "ГЛЯДЗІЦЬ НА СХЕМУ",
  "vn.line.VN0144.text": "Ты апісала цэнтральную пральню.",
  "vn.line.VN0145.speaker": "АЮКІ",
  "vn.line.VN0145.emotion": "ДАДАЕ СТРЭЛКУ",
  "vn.line.VN0145.text": "Або яе самага небяспечнага кліента.",
  "vn.line.VN0146.speaker": "ОНОЭ",
  "vn.line.VN0146.emotion": "З ЖУРНАЛАМ",
  "vn.line.VN0146.text": "Зніклі мужчынскія баксёры, жаночыя трусікі, два нейтральныя спартыўныя камплекты і ручнік.",
  "vn.line.VN0147.speaker": "АЮКІ",
  "vn.line.VN0147.emotion": "ЗАДУМЕННАЯ",
  "vn.line.VN0147.text": "Усеядны эстэт.",
  "vn.line.VN0148.speaker": "ОНОЭ",
  "vn.line.VN0148.emotion": "ВЫПРАЎЛЯЕ",
  "vn.line.VN0148.text": "Або адсутнасць эстэтычнага крытэрыю.",
  "vn.line.VN0149.speaker": "РЭЖЫСУРА",
  "vn.line.VN0149.emotion": "SFX: ДЗВЕРЫ ДУШАВОЙ",
  "vn.line.VN0149.text": "З'яўляецца Норыхіра ў доўгім камандным халаце, з планшэтам і са звязкай ключоў.",
  "vn.line.VN0150.speaker": "НОРЫХІРА",
  "vn.line.VN0150.emotion": "СПАКОЙНЫ",
  "vn.line.VN0150.text": "Калі схема пра мяне, стрэлка павінна весці да службовай шафы.",
  "vn.line.VN0151.speaker": "АЮКІ",
  "vn.line.VN0151.emotion": "ЗАСПЕТАЯ ЗНЯНАЦКУ",
  "vn.line.VN0151.text": "Мы рэканструявалі псіхалогію невядомага злодзея.",
  "vn.line.VN0152.speaker": "НОРЫХІРА",
  "vn.line.VN0152.emotion": "ГЛЯДЗІЦЬ НА НАДПІС «ДРАПЕЖНІК»",
  "vn.line.VN0152.text": "Вядома.",
  "vn.line.VN0153.speaker": "ОНОЭ",
  "vn.line.VN0153.emotion": "НАПРАМУЮ",
  "vn.line.VN0153.text": "Вы апошнім зачынялі распранальні і падпісалі перадачу мяшкоў.",
  "vn.line.VN0154.speaker": "НОРЫХІРА",
  "vn.line.VN0154.emotion": "КІВАЕ",
  "vn.line.VN0154.text": "Так. Потым я забраў апошні мяшок дадому: машына спынілася на паласканні.",
  "vn.line.VN0155.speaker": "АЮКІ",
  "vn.line.VN0155.emotion": "ПРЫЖМУРВАЕЦЦА",
  "vn.line.VN0155.text": "Вы занадта спакойны для мужчыны, акружанага такой колькасцю бялізны.",
  "vn.line.VN0156.speaker": "НОРЫХІРА",
  "vn.line.VN0156.emotion": "НЕЗВАРУШНА",
  "vn.line.VN0156.text": "Я менеджар клуба плавання. Мой парог збянтэжанасці патануў яшчэ на першым курсе.",
  "vn.line.VN0157.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0157.emotion": "СУХА",
  "vn.line.VN0157.text": "Здаецца, Аюкі толькі што прайграла чалавеку ў халаце.",
  "vn.line.VN0158.speaker": "НОРЫХІРА",
  "vn.line.VN0158.emotion": "ПАКАЗВАЕ ЖУРНАЛ",
  "vn.line.VN0158.text": "Памылкі сартавання здараюцца. Спачатку аддзяліце клубныя біркі і знайдзіце ключ ад службовай шафы.",
  "vn.line.VN0159.speaker": "ОНОЭ",
  "vn.line.VN0159.emotion": "ПАДАЗРОНАЯ",
  "vn.line.VN0159.text": "Вы ахвотна дапамагаеце.",
  "vn.line.VN0160.speaker": "НОРЫХІРА",
  "vn.line.VN0160.emotion": "РОЎНА",
  "vn.line.VN0160.text": "Бо заўтра ў шэсць раніцы трэніроўка, а палова каманды абвінавачвае другую палову.",
  "vn.line.VN0161.speaker": "МІКУ",
  "vn.line.VN0161.emotion": "МЯККА",
  "vn.line.VN0161.text": "Хто меў доступ пасля вяртання рэчаў з прання?",
  "vn.line.VN0162.speaker": "НОРЫХІРА",
  "vn.line.VN0162.emotion": "ПЕРАЛІЧВАЕ",
  "vn.line.VN0162.text": "Я, два капітаны і прыбіральшчыкі. Але рэчы зніклі з розных секцый.",
  "vn.line.VN0163.speaker": "ОНОЭ",
  "vn.line.VN0163.emotion": "ЗАСЯРОДЖАНАЯ",
  "vn.line.VN0163.text": "Праверым партыю, секцыі і паслядоўнасць адкрыцця.",
  "vn.line.VN0164.speaker": "АЮКІ",
  "vn.line.VN0164.emotion": "ЗГОРТВАЕ СХЕМУ",
  "vn.line.VN0164.text": "А профіль часова назавём рабочай фантазіяй.",
  "vn.line.VN0165.speaker": "НОРЫХІРА",
  "vn.line.VN0165.emotion": "СУХА",
  "vn.line.VN0165.text": "Назавіце яго смеццем і прыбярыце з маёй лаўкі.",
  "vn.line.VN0166.speaker": "РЭЖЫСУРА",
  "vn.line.VN0166.emotion": "TRANSITION TO MATCH-3",
  "vn.line.VN0166.text": "Пена і мокрыя ручнікі фарміруюць гульнявое поле.",
  "vn.line.VN0167.speaker": "РЭЖЫСУРА",
  "vn.line.VN0167.emotion": "INSERT: ЖУРНАЛ ПРАННЯ",
  "vn.line.VN0167.text": "У раскрытым журнале адзін код партыі паўтараецца каля ўсіх зніклых рэчаў.",
  "vn.line.VN0168.speaker": "ОНОЭ",
  "vn.line.VN0168.emotion": "ЛЯ ДОШКІ",
  "vn.line.VN0168.text": "Фасон — карэляцыі няма. Цана — няма. Гендар уладальніка — няма. Колер — няма.",
  "vn.line.VN0169.speaker": "АЮКІ",
  "vn.line.VN0169.emotion": "АБУРАНАЯ",
  "vn.line.VN0169.text": "У гэтага злачынства ўвогуле ёсць мастацкі кірунак?",
  "vn.line.VN0170.speaker": "МІКУ",
  "vn.line.VN0170.emotion": "УВАЖЛІВАЯ",
  "vn.line.VN0170.text": "Ёсць агульны код прання. І зніклі не ўсе рэчы з гэтым кодам.",
  "vn.line.VN0171.speaker": "ОНОЭ",
  "vn.line.VN0171.emotion": "СУР'ЁЗНА",
  "vn.line.VN0171.text": "Амаль абразліва нядбайная выбарка.",
  "vn.line.VN0172.speaker": "НОРЫХІРА",
  "vn.line.VN0172.emotion": "СУХА",
  "vn.line.VN0172.text": "Перадам злодзею вашу рэцэнзію.",
  "vn.line.VN0173.speaker": "МІКУ",
  "vn.line.VN0173.emotion": "ПАКАЗВАЕ ЖУРНАЛ",
  "vn.line.VN0173.text": "Мужчынскае, жаночае, спартыўнае і ручнік. Значыць, справа не ў адным тыпе бялізны і не ў тым, хто яе носіць.",
  "vn.line.VN0174.speaker": "АЮКІ",
  "vn.line.VN0174.emotion": "ЗАКРЭСЛІВАЕ СХЕМУ",
  "vn.line.VN0174.text": "Бывай, профіль бялізнавага эстэта. Мы амаль цябе ведалі.",
  "vn.line.VN0175.speaker": "СІСТЭМА",
  "vn.line.VN0175.emotion": "DOSSIER",
  "vn.line.VN0175.text": "{ADD CUE_003_MIXED_TARGETS}",
  "vn.line.VN0176.speaker": "ОНОЭ",
  "vn.line.VN0176.emotion": "ДА НОРЫХІРА",
  "vn.line.VN0176.text": "Застаецца апошні мяшок, які вы забралі дадому.",
  "vn.line.VN0177.speaker": "НОРЫХІРА",
  "vn.line.VN0177.emotion": "СПАКОЙНА",
  "vn.line.VN0177.text": "Сухі і складзены. Я прынясу яго раніцай.",
  "vn.line.VN0178.speaker": "АЮКІ",
  "vn.line.VN0178.emotion": "ХУТКА",
  "vn.line.VN0178.text": "Чаму не цяпер?",
  "vn.line.VN0179.speaker": "НОРЫХІРА",
  "vn.line.VN0179.emotion": "ПАКАЗВАЕ ЧАС",
  "vn.line.VN0179.text": "Бо цяпер 21:40, а вы стаіце ў мокрай распранальні без ордара і афіцыйнага статусу клуба.",
  "vn.line.VN0180.speaker": "ОНОЭ",
  "vn.line.VN0180.emotion": "ПАЎЗА",
  "vn.line.VN0180.text": "Фармальна правільна.",
  "vn.line.VN0181.speaker": "АЮКІ",
  "vn.line.VN0181.emotion": "ЦІХА ДА МІКУ",
  "vn.line.VN0181.text": "Спакойны, з ключамі, ведае правілы. Вельмі падазроны набор.",
  "vn.line.VN0182.speaker": "МІКУ",
  "vn.line.VN0182.emotion": "ЦІХА",
  "vn.line.VN0182.text": "Або кампетэнтны менеджар.",
  "vn.line.VN0183.speaker": "НОРЫХІРА",
  "vn.line.VN0183.emotion": "ПАЧУЎ",
  "vn.line.VN0183.text": "Можаце праверыць мяшок сёння, калі скончыце да дзесяці. Я жыву праз дарогу.",
  "vn.line.VN0184.speaker": "ОНОЭ",
  "vn.line.VN0184.emotion": "РАШУЧАЯ",
  "vn.line.VN0184.text": "Пры вашай выразнай згодзе.",
  "vn.line.VN0185.speaker": "НОРЫХІРА",
  "vn.line.VN0185.emotion": "НЕЗВАРУШНА",
  "vn.line.VN0185.text": "Пры маім выразным жаданні заўтра атрымаць форму назад.",
  "vn.line.VN0186.speaker": "АЮКІ",
  "vn.line.VN0186.emotion": "З ТЭЛЕФОНАМ",
  "vn.line.VN0186.text": "Жыве адзін, забраў рэчавы доказ, запрашае дэтэктываў дадому. Гэта альбо алібі, альбо фінал другога акта.",
  "vn.line.VN0187.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0187.emotion": "ІРАНІЧНАЯ",
  "vn.line.VN0187.text": "Мы яшчэ не ведалі, што там нас чакае самы ружовы аргумент вечара.",
  "vn.line.VN0188.speaker": "РЭЖЫСУРА",
  "vn.line.VN0188.emotion": "EPISODE CARD",
  "vn.line.VN0188.text": "«Эпізод 3 — Ружовыя тапачкі»",
  "vn.line.VN0189.speaker": "РЭЖЫСУРА",
  "vn.line.VN0189.emotion": "ESTABLISHING / NIGHT",
  "vn.line.VN0189.text": "За акном цёмна. Унутры кватэры ўсё выраўнавана: абутак, кнігі, ручнікі і падпісаныя кантэйнеры.",
  "vn.line.VN0190.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0190.emotion": "ЗДЗІЎЛЕНАЯ",
  "vn.line.VN0190.text": "Пасля кватэры Кэнтаро гэта месца выглядала як фатаграфія «пасля».",
  "vn.line.VN0191.speaker": "АЮКІ",
  "vn.line.VN0191.emotion": "ШЭПТАМ",
  "vn.line.VN0191.text": "Занадта чыста.",


  // ANM-029B3D — Belarusian VN story slot 3 (canonical runtime graph: VN0192–VN0250 + scenes 07–08).
  "vn.scene.VN_SCENE_07_E3_PRE.title": "Ружовае прызнанне",
  "vn.scene.VN_SCENE_07_E3_PRE.location": "Кватэра Норыхіра",
  "vn.scene.VN_SCENE_08_E3_POST.title": "Гэта не тканіна",
  "vn.scene.VN_SCENE_08_E3_POST.location": "Кватэра Норыхіра",

  "vn.line.VN0192.speaker": "МІКУ",
  "vn.line.VN0192.emotion": "ШЭПТАМ",
  "vn.line.VN0192.text": "Ты толькі што лічыла беспарадак доказам.",
  "vn.line.VN0193.speaker": "АЮКІ",
  "vn.line.VN0193.emotion": "ШЭПТАМ",
  "vn.line.VN0193.text": "Я адаптуюся да доказаў.",
  "vn.line.VN0194.speaker": "НОРЫХІРА",
  "vn.line.VN0194.emotion": "ЗДЫМАЕ АБУТАК",
  "vn.line.VN0194.text": "Мяшок каля шафы. Пальчаткі на паліцы. Нічога не перасоўвайце без пытання.",
  "vn.line.VN0195.speaker": "ОНОЭ",
  "vn.line.VN0195.emotion": "АФІЦЫЙНАЯ",
  "vn.line.VN0195.text": "Пацвердзіце згоду на агляд шафы і мяшка.",
  "vn.line.VN0196.speaker": "НОРЫХІРА",
  "vn.line.VN0196.emotion": "РОЎНА",
  "vn.line.VN0196.text": "Пацвярджаю. Пры ўмове, што Аюкі перастане фатаграфаваць мой калідор.",
  "vn.line.VN0197.speaker": "АЮКІ",
  "vn.line.VN0197.emotion": "ПРЫБІРАЕ ТЭЛЕФОН",
  "vn.line.VN0197.text": "Я правярала асвятленне.",
  "vn.line.VN0198.speaker": "РЭЖЫСУРА",
  "vn.line.VN0198.emotion": "CLOSE UP: PINK SLIPPERS",
  "vn.line.VN0198.text": "З-пад нізкай паліцы відаць вялікія ярка-ружовыя тапачкі.",
  "vn.line.VN0199.speaker": "АЮКІ",
  "vn.line.VN0199.emotion": "ПЕРАМОЖНАЯ",
  "vn.line.VN0199.text": "А вось і яна.",
  "vn.line.VN0200.speaker": "НОРЫХІРА",
  "vn.line.VN0200.emotion": "НЕ РАЗУМЕЕ",
  "vn.line.VN0200.text": "Паліца?",
  "vn.line.VN0201.speaker": "АЮКІ",
  "vn.line.VN0201.emotion": "ПАКАЗВАЕ",
  "vn.line.VN0201.text": "Таемная саўдзельніца. Ружовыя тапачкі ў кватэры мужчыны, які жыве адзін.",
  "vn.line.VN0202.speaker": "МІКУ",
  "vn.line.VN0202.emotion": "СУМНЯВАЕЦЦА",
  "vn.line.VN0202.text": "Яны выглядаюць… вялікімі.",
  "vn.line.VN0203.speaker": "ОНОЭ",
  "vn.line.VN0203.emotion": "АНАЛІТЫЧНАЯ",
  "vn.line.VN0203.text": "Верагодны рэгулярны візіт чалавека з доступам да кватэры і пральні.",
  "vn.line.VN0204.speaker": "НОРЫХІРА",
  "vn.line.VN0204.emotion": "БЯРЭ ТАПАЧКІ",
  "vn.line.VN0204.text": "Памер сорак пяць. Мае.",
  "vn.line.VN0205.speaker": "РЭЖЫСУРА",
  "vn.line.VN0205.emotion": "INSERT: RECEIPT",
  "vn.line.VN0205.text": "Ён дастае электронны чэк.",
  "vn.line.VN0206.speaker": "НОРЫХІРА",
  "vn.line.VN0206.emotion": "СПАКОЙНЫ",
  "vn.line.VN0206.text": "Зніжка семдзесят працэнтаў. Шэрыя адрозніваліся толькі колерам і адсутнасцю зніжкі.",
  "vn.line.VN0207.speaker": "АЮКІ",
  "vn.line.VN0207.emotion": "ЗБЯНТЭЖАНАЯ",
  "vn.line.VN0207.text": "Але ружовыя.",
  "vn.line.VN0208.speaker": "НОРЫХІРА",
  "vn.line.VN0208.emotion": "ГЛЯДЗІЦЬ ПРАМА",
  "vn.line.VN0208.text": "Гэта колер, а не паказанне сведкі.",
  "vn.line.VN0209.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0209.emotion": "НЯЗРУЧНА",
  "vn.line.VN0209.text": "У гэтую секунду наша расследаванне стала горшым за тапачкі: яркім, упэўненым і зусім пустым унутры.",
  "vn.line.VN0210.speaker": "ОНОЭ",
  "vn.line.VN0210.emotion": "ПАСЛЯ ПАЎЗЫ",
  "vn.line.VN0210.text": "Тапачкі выключаем. Праверым мяшок і фактычнае змесціва.",
  "vn.line.VN0211.speaker": "НОРЫХІРА",
  "vn.line.VN0211.emotion": "АДЧЫНЯЕ ШАФУ",
  "vn.line.VN0211.text": "Ручнікі зверху. Камплекты рассартаваныя ніжэй.",
  "vn.line.VN0212.speaker": "АЮКІ",
  "vn.line.VN0212.emotion": "ЗАЗІРАЕ",
  "vn.line.VN0212.text": "Ты заўсёды сартуеш бялізну па колеры?",
  "vn.line.VN0213.speaker": "НОРЫХІРА",
  "vn.line.VN0213.emotion": "СУХА",
  "vn.line.VN0213.text": "Не. Сёння — па ступені вашага расчаравання.",
  "vn.line.VN0214.speaker": "МІКУ",
  "vn.line.VN0214.emotion": "СТРЫМЛІВАЕ СМЕХ",
  "vn.line.VN0214.text": "Тады ружовая секцыя перапоўненая.",
  "vn.line.VN0215.speaker": "ОНОЭ",
  "vn.line.VN0215.emotion": "ПА-ДЗЕЛАВОМУ",
  "vn.line.VN0215.text": "Працуем акуратна. Аднаўляем пары, звяраем чэк і шукаем пашкоджанні пасля мыцця.",
  "vn.line.VN0216.speaker": "РЭЖЫСУРА",
  "vn.line.VN0216.emotion": "TRANSITION TO MATCH-3",
  "vn.line.VN0216.text": "Роўныя секцыі шафы складаюцца ў сетку поля.",
  "vn.line.VN0217.speaker": "РЭЖЫСУРА",
  "vn.line.VN0217.emotion": "TABLE CLOSE UP",
  "vn.line.VN0217.text": "Чэк, ручнік і ружовыя тапачкі ляжаць побач. Скрадзеных рэчаў у кватэры няма.",
  "vn.line.VN0218.speaker": "ОНОЭ",
  "vn.line.VN0218.emotion": "СТРЫМАНА",
  "vn.line.VN0218.text": "Склад мяшка супадае з журналам вяртання. Зніклых прадметаў тут няма.",
  "vn.line.VN0219.speaker": "АЮКІ",
  "vn.line.VN0219.emotion": "ГЛЯДЗІЦЬ НА ТАПАЧКІ",
  "vn.line.VN0219.text": "Саўдзельніцы таксама.",
  "vn.line.VN0220.speaker": "НОРЫХІРА",
  "vn.line.VN0220.emotion": "РОЎНА",
  "vn.line.VN0220.text": "Рады, што яе адсутнасць нарэшце задакументаваная.",
  "vn.line.VN0221.speaker": "ОНОЭ",
  "vn.line.VN0221.emotion": "ПРЫБІРАЕ ВЕРСІЮ",
  "vn.line.VN0221.text": "Норыхіра выключаны са спіса падазраваных.",
  "vn.line.VN0222.speaker": "НОРЫХІРА",
  "vn.line.VN0222.emotion": "КОРОТКА",
  "vn.line.VN0222.text": "І ўсё?",
  "vn.line.VN0223.speaker": "ОНОЭ",
  "vn.line.VN0223.emotion": "НЕ РАЗУМЕЕ",
  "vn.line.VN0223.text": "Факты правераныя.",
  "vn.line.VN0224.speaker": "МІКУ",
  "vn.line.VN0224.emotion": "ЦВЁРДАЯ",
  "vn.line.VN0224.text": "Не. Не ўсё.",
  "vn.line.VN0225.speaker": "РЭЖЫСУРА",
  "vn.line.VN0225.emotion": "SPRITE CHANGE: ONOE SURPRISED / AYUKI QUIET",
  "vn.line.VN0225.text": "Міку ўстае паміж Норыхіра і сяброўкамі.",
  "vn.line.VN0226.speaker": "МІКУ",
  "vn.line.VN0226.emotion": "ПРАМА ДА ОНОЭ І АЮКІ",
  "vn.line.VN0226.text": "Мы вырашылі, што беспарадак робіць Кэнтаро вінаватым, а парадак — Норыхіра падазроным.",
  "vn.line.VN0227.speaker": "МІКУ",
  "vn.line.VN0227.emotion": "ПРАЦЯГВАЕ",
  "vn.line.VN0227.text": "Потым ператварылі колер яго абутку ў доказ чалавека, якога не існуе.",
  "vn.line.VN0228.speaker": "АЮКІ",
  "vn.line.VN0228.emotion": "БЕЗ УСМЕШКІ",
  "vn.line.VN0228.text": "Гэта была дрэнная версія.",
  "vn.line.VN0229.speaker": "МІКУ",
  "vn.line.VN0229.emotion": "СПАКАЙНЕЙ",
  "vn.line.VN0229.text": "Яна была смешнай, пакуль адказваць за яе мусіў не ён.",
  "vn.line.VN0230.speaker": "ОНОЭ",
  "vn.line.VN0230.emotion": "ПАЎЗА, ПОТЫМ КІВАЕ",
  "vn.line.VN0230.text": "Згодная. Я ўнясу ў пратакол не толькі абвяржэнне, але і памылку метаду.",
  "vn.line.VN0231.speaker": "АЮКІ",
  "vn.line.VN0231.emotion": "ДА НОРЫХІРА",
  "vn.line.VN0231.text": "Прабач. Тапачкі выдатныя. Тэорыя — не.",
  "vn.line.VN0232.speaker": "НОРЫХІРА",
  "vn.line.VN0232.emotion": "МЯКЧЭЙ",
  "vn.line.VN0232.text": "Прабачэнне прынята. Тапачкі не патрабавалі апраўдання.",
  "vn.line.VN0233.speaker": "РЭЖЫСУРА",
  "vn.line.VN0233.emotion": "ПАЎЗА БЕЗ ЖАРТУ / CLOSE ON TOWEL",
  "vn.line.VN0233.text": "Міку праводзіць пальцам у пальчатцы ўздоўж краю ручніка.",
  "vn.line.VN0234.speaker": "МІКУ",
  "vn.line.VN0234.emotion": "ЗАСЯРОДЖАНАЯ",
  "vn.line.VN0234.text": "Гэтае шво адрозніваецца. Яно навейшае за тканіну і занадта роўнае для рамонту.",
  "vn.line.VN0235.speaker": "НОРЫХІРА",
  "vn.line.VN0235.emotion": "НАХІЛЯЕЦЦА",
  "vn.line.VN0235.text": "У нашай формы няма серабрыстай аздобы.",
  "vn.line.VN0236.speaker": "ОНОЭ",
  "vn.line.VN0236.emotion": "БЯРЭ ПІНЦЭТ",
  "vn.line.VN0236.text": "Гэта не аздоба. Нітка ўведзена пад сэрвісны ярлык.",
  "vn.line.VN0237.speaker": "АЮКІ",
  "vn.line.VN0237.emotion": "АСЦЯРОЖНА",
  "vn.line.VN0237.text": "Яе маглі дадаць у пральні?",
  "vn.line.VN0238.speaker": "МІКУ",
  "vn.line.VN0238.emotion": "УСПАМІНАЕ",
  "vn.line.VN0238.text": "Усе тры выпадкі звязаныя з партыямі мыцця. Але знікаюць толькі асобныя рэчы.",
  "vn.line.VN0239.speaker": "ОНОЭ",
  "vn.line.VN0239.emotion": "УЗБУДЖАНА-ЗАСЯРОДЖАНАЯ",
  "vn.line.VN0239.text": "Калі такое шво ёсць і на зніклых прадметах, злодзей выбірае не бялізну. Ён выбірае тое, што ў яе дадалі.",
  "vn.line.VN0240.speaker": "АЮКІ",
  "vn.line.VN0240.emotion": "ЦІХА",
  "vn.line.VN0240.text": "То бок увесь гэты час мы шукалі чыйсьці густ, а трэба было шукаць тэхналогію?",
  "vn.line.VN0241.speaker": "МІКУ",
  "vn.line.VN0241.emotion": "КІВАЕ",
  "vn.line.VN0241.text": "І чалавека, які ведае, дзе яна схаваная.",
  "vn.line.VN0242.speaker": "СІСТЭМА",
  "vn.line.VN0242.emotion": "DOSSIER",
  "vn.line.VN0242.text": "{ADD CUE_004_SILVER_THREAD; SET SUS_NORIHIRO=cleared}",
  "vn.line.VN0243.speaker": "РЭЖЫСУРА",
  "vn.line.VN0243.emotion": "LIGHTS DOWN / PHONE FLASHLIGHT",
  "vn.line.VN0243.text": "Норыхіра выключае верхняе святло. Оноэ накіроўвае ліхтарык тэлефона на нітку.",
  "vn.line.VN0244.speaker": "РЭЖЫСУРА",
  "vn.line.VN0244.emotion": "HERO INSERT",
  "vn.line.VN0244.text": "Серабрыстая нітка дае тонкі бірузовы водбліск.",
  "vn.line.VN0245.speaker": "МІКУ (ДУМКІ)",
  "vn.line.VN0245.emotion": "ТРАВОЖНА-ЗАЦІКАЎЛЕНАЯ",
  "vn.line.VN0245.text": "Справа пра зніклую бялізну ўпершыню перастала выглядаць маленькай.",
  "vn.line.VN0246.speaker": "ОНОЭ",
  "vn.line.VN0246.emotion": "ЦІХА, ДАКЛАДНА",
  "vn.line.VN0246.text": "Гэта не тканіна.",
  "vn.line.VN0247.speaker": "ОНОЭ",
  "vn.line.VN0247.emotion": "БУЙНЫ ПЛАН",
  "vn.line.VN0247.text": "Гэта праваднік.",
  "vn.line.VN0248.speaker": "РЭЖЫСУРА",
  "vn.line.VN0248.emotion": "CUT TO BLACK / MUSIC STING",
  "vn.line.VN0248.text": "На экране застаецца бірузовая лінія, якая складваецца ў знак пытання.",
  "vn.line.VN0249.speaker": "СІСТЭМА",
  "vn.line.VN0249.emotion": "CHAPTER COMPLETE",
  "vn.line.VN0249.text": "«Першая нітка знойдзена»",
  "vn.line.VN0250.speaker": "РЭЖЫСУРА",
  "vn.line.VN0250.emotion": "OPTIONAL TEASER",
  "vn.line.VN0250.text": "Дошка клуба. Сем пустых картак спартыўных клубаў; на адной міргае новае паведамленне.",

  // ANM-029B3E — Belarusian VN story slot 4 (canonical runtime graph: VN0251–VN0288 + scenes 09–10 + meeting-tone choice).
  "vn.scene.VN_SCENE_09_E4_PRE.title": "Надзвычайная бялізнавая нарада",
  "vn.scene.VN_SCENE_09_E4_PRE.location": "Аўдыторыя студсавета",
  "vn.scene.VN_SCENE_10_E4_POST.title": "Рытм пральні",
  "vn.scene.VN_SCENE_10_E4_POST.location": "Аўдыторыя студсавета",
  "vn.line.VN0251.speaker": "РЭЖЫСУРА",
  "vn.line.VN0251.emotion": "ESTABLISHING / DAY",
  "vn.line.VN0251.text": "Аўдыторыя студсавета. Сем таблічак спартыўных клубаў, стосы закрытых заяў і праектар з папярэджаннем «БЕЗ СКРЫНШОТАЎ».",
  "vn.line.VN0252.speaker": "МАЮ",
  "vn.line.VN0252.emotion": "ВЕТЛІВА-НАПРУЖАНАЯ",
  "vn.line.VN0252.text": "Адміністрацыя дазволіла сустрэчу пры дзвюх умовах: без імёнаў па-за межамі пакоя і без слова «серыйны».",
  "vn.line.VN0253.speaker": "АЮКІ",
  "vn.line.VN0253.emotion": "З ТЭЛЕФОНАМ",
  "vn.line.VN0253.text": "Тады мая прэзентацыя «Бялізнавы прывід Сэйрана: паляванне пачалося» фармальна парушае толькі адну ўмову.",
  "vn.line.VN0254.speaker": "МІКУ",
  "vn.line.VN0254.emotion": "ХУТКА",
  "vn.line.VN0254.text": "Я ўжо перайменавала яе ў «Інвентарныя неадпаведнасці ў спартыўным корпусе».",
  "vn.line.VN0255.speaker": "ОНОЭ",
  "vn.line.VN0255.emotion": "СУР'ЁЗНА",
  "vn.line.VN0255.text": "Нейтральна, правяральна і досыць сумна, каб ніхто не пераслаў загаловак.",
  "vn.line.VN0256.speaker": "МАЮ",
  "vn.line.VN0256.emotion": "З ПРАЕКТАРАМ",
  "vn.line.VN0256.text": "Менавіта таму сёння за кнопку паказу адказвае Міку.",
  "vn.line.VN0257.speaker": "ПРАДСТАЎНІК КЭНДО",
  "vn.line.VN0257.emotion": "НЕ РАЗУМЕЕ",
  "vn.line.VN0257.text": "Чаму мае трусы на графіку пазначаныя трохвугольнікам?",
  "vn.line.VN0258.speaker": "ОНОЭ",
  "vn.line.VN0258.emotion": "АНАЛІТЫЧНАЯ",
  "vn.line.VN0258.text": "Трохвугольнік пазначае катэгорыю з недастатковай выбаркай, а не форму прадмета.",
  "vn.line.VN0259.speaker": "МІКУ",
  "vn.line.VN0259.emotion": "ВЫКЛЮЧАЕ ПРАЕКТАР",
  "vn.line.VN0259.text": "На гэтым графік пакуль скончаны.",
  "vn.line.VN0260.speaker": "РЭЖЫСУРА",
  "vn.line.VN0260.emotion": "МАНТАЖ СУСТРЭЧЫ",
  "vn.line.VN0260.text": "Рэплікі накладаюцца адна на адну: «толькі пасля трэніроўкі», «з закрытай шафы», «вярнулі не той мяшок», «гэта ўвогуле быў запасны камплект».",
  "vn.line.VN0261.speaker": "МІКУ",
  "vn.line.VN0261.emotion": "СПАКОЙНАЯ",
  "vn.line.VN0261.text": "Па адным факце ад кожнага клуба. Без версіі, без вінаватага, без ацэнкі таго, наколькі рэч была прыгожай.",
  "vn.line.VN0262.speaker": "СІСТЭМА",
  "vn.line.VN0262.emotion": "CHOICE CHECKPOINT",
  "vn.line.VN0262.text": "{CHOICE meeting-tone}",
  "vn.line.VN0263.speaker": "РЭЖЫСУРА",
  "vn.line.VN0263.emotion": "ПАСЛЯ ВЫБАРУ",
  "vn.line.VN0263.text": "Фармат сустрэчы змяняецца паводле рашэння Міку, але спіс фактаў, якія можна праверыць, застаецца агульным.",
  "vn.line.VN0264.speaker": "МАЮ",
  "vn.line.VN0264.emotion": "З ПАПКАЙ",
  "vn.line.VN0264.text": "Вось формы па сямі клубах і даты цэнтралізаванага мыцця. Імёны я замяніла нумарамі заяў.",
  "vn.line.VN0265.speaker": "ОНОЭ",
  "vn.line.VN0265.emotion": "ЗАСЯРОДЖАНАЯ",
  "vn.line.VN0265.text": "Лёгкая атлетыка — мыццё за суткі да знікнення. Плаванне — за двое. Тэніс — за суткі.",
  "vn.line.VN0266.speaker": "АЮКІ",
  "vn.line.VN0266.emotion": "ЗАЎВАЖАЕ РЫТМ",
  "vn.line.VN0266.text": "Баскетбол — таксама. Каратэ — таксама. Гэта ўжо не россып супадзенняў.",
  "vn.line.VN0267.speaker": "МІКУ",
  "vn.line.VN0267.emotion": "УВАЖЛІВАЯ",
  "vn.line.VN0267.text": "Усе пацверджаныя выпадкі праходзяць праз цэнтральную пральню за сорак восем гадзін да знікнення.",
  "vn.line.VN0268.speaker": "МАЮ",
  "vn.line.VN0268.emotion": "КІВАЕ",
  "vn.line.VN0268.text": "Усе сем клубаў карыстаюцца адной сэрвіснай сістэмай. Гэта першы агульны маршрут, а не агульны тып бялізны.",
  "vn.line.VN0269.speaker": "РЭЖЫСУРА",
  "vn.line.VN0269.emotion": "INSERT: LAUNDRY CALENDAR",
  "vn.line.VN0269.text": "Формы, клубныя жэтоны і каляндар мыцця раскладваюцца ў строгую сетку.",
  "vn.line.VN0270.speaker": "РЭЖЫСУРА",
  "vn.line.VN0270.emotion": "TRANSITION TO MATCH-3",
  "vn.line.VN0270.text": "Чуткі закрываюць частку пацверджаных заяў; агульны каляндар апускаецца да ніжняй мяжы поля.",
  "vn.line.VN0271.speaker": "РЭЖЫСУРА",
  "vn.line.VN0271.emotion": "INSERT: LAUNDRY CALENDAR",
  "vn.line.VN0271.text": "Пасля сартавання на дошцы застаюцца толькі пацверджаныя заявы і сем адзнак цэнтральнай пральні.",
  "vn.line.VN0272.speaker": "ОНОЭ",
  "vn.line.VN0272.emotion": "КАЛЯ ДОШКІ",
  "vn.line.VN0272.text": "Інтэрвал паўтараецца: апрацоўка, вяртанне, потым знікненне на працягу аднаго-двух дзён.",
  "vn.line.VN0273.speaker": "АЮКІ",
  "vn.line.VN0273.emotion": "АБУРАНАЯ",
  "vn.line.VN0273.text": "То бок версія пра некалькіх незалежных фетышыстаў статыстычна прайграла пральні?",
  "vn.line.VN0274.speaker": "МІКУ",
  "vn.line.VN0274.emotion": "ЦВЁРДАЯ",
  "vn.line.VN0274.text": "Версія прайграла фактам. Пральня пакуль толькі агульны маршрут.",
  "vn.line.VN0275.speaker": "ПРАДСТАЎНІК ТЭНІСА",
  "vn.line.VN0275.emotion": "СУМНЯВАЕЦЦА",
  "vn.line.VN0275.text": "У нас знік самы звычайны запасны камплект. Калі нехта выбірае паводле густу, густ у яго дзіўны.",
  "vn.line.VN0276.speaker": "МАЮ",
  "vn.line.VN0276.emotion": "ЦІШЭЙ",
  "vn.line.VN0276.text": "Менавіта таму ніякія спісы пацярпелых не выходзяць з гэтага пакоя.",
  "vn.line.VN0277.speaker": "МІКУ",
  "vn.line.VN0277.emotion": "УВАЖЛІВАЯ",
  "vn.line.VN0277.text": "Пацверджана толькі гэта: спартыўны клуб, цэнтральная пральня і паўтаральны часавы рытм.",
  "vn.line.VN0278.speaker": "СІСТЭМА",
  "vn.line.VN0278.emotion": "DOSSIER",
  "vn.line.VN0278.text": "{ADD CUE_005}",
  "vn.line.VN0279.speaker": "ОНОЭ",
  "vn.line.VN0279.emotion": "З ГРАФІКАМ",
  "vn.line.VN0279.text": "Я ўсё ж пакіну табліцу «тып бялізны / верагоднасць знікнення» як адмоўны доказ карэляцыі.",
  "vn.line.VN0280.speaker": "ПРАДСТАЎНІК КЭНДО",
  "vn.line.VN0280.emotion": "СУХА",
  "vn.line.VN0280.text": "А трохвугольнік?",
  "vn.line.VN0281.speaker": "МІКУ",
  "vn.line.VN0281.emotion": "ВЫКЛЮЧАЕ ПРАЕКТАР",
  "vn.line.VN0281.text": "Трохвугольнік тым больш застанецца ў гэтым пакоі.",
  "vn.line.VN0282.speaker": "АЮКІ",
  "vn.line.VN0282.emotion": "З УСМЕШКАЙ",
  "vn.line.VN0282.text": "Гісторыя страціла прывіда, але атрымала расклад. Я вучуся цаніць дарослыя кампрамісы.",
  "vn.line.VN0283.speaker": "МАЮ",
  "vn.line.VN0283.emotion": "ВЕТЛІВА-НАПРУЖАНАЯ",
  "vn.line.VN0283.text": "Цані іх моўчкі.",
  "vn.line.VN0284.speaker": "РЭЖЫСУРА",
  "vn.line.VN0284.emotion": "SFX: MESSAGE",
  "vn.line.VN0284.text": "Тэлефон Маю вібруе. На экране — паведамленне ад капітана баскетбольнай каманды.",
  "vn.line.VN0285.speaker": "МАЮ",
  "vn.line.VN0285.emotion": "ЧЫТАЕ",
  "vn.line.VN0285.text": "«Знік камплект з закрытай каманднай шафы. Ён пакідаў шафу толькі ў дзень цэнтралізаванага мыцця».",
  "vn.line.VN0286.speaker": "МІКУ",
  "vn.line.VN0286.emotion": "РАШУЧАЯ",
  "vn.line.VN0286.text": "Тады ў нас ёсць выпадак, дзе можна праверыць маршрут амаль без старонніх зменных.",
  "vn.line.VN0287.speaker": "ОНОЭ",
  "vn.line.VN0287.emotion": "ЗАСЯРОДЖАНАЯ",
  "vn.line.VN0287.text": "Наступны пункт — баскетбольная распранальня. Спачатку шафа, потым людзі.",
  "vn.line.VN0288.speaker": "РЭЖЫСУРА",
  "vn.line.VN0288.emotion": "EPISODE CARD",
  "vn.line.VN0288.text": "«Эпізод 5 — Заслон для злодзея»",
  "vn.storyChoice.meeting-tone.prompt": "Як Міку правядзе закрытую нараду?",
  "vn.storyChoice.meeting-tone.A.title": "Клінічна і па фактах",
  "vn.storyChoice.meeting-tone.A.effect": "Давер Оноэ +1",
  "vn.storyChoice.meeting-tone.B.title": "Зняць напружанне гумарам",
  "vn.storyChoice.meeting-tone.B.effect": "Давер Аюкі +1",
  "vn.storyChoice.meeting-tone.C.title": "Сабраць паказанні па адным",
  "vn.storyChoice.meeting-tone.C.effect": "Давер крыніц +1",

} as const satisfies MessageCatalog;

export const beCompletedCatalogPrefixes = [
  'localization',
  'common',
  'menu',
  'settings',
  'audio',
  'pwa',
] as const;
