import type { MessageCatalog } from '../MessageCatalog';

// ANM-029B builds this catalog in reviewable production scopes.
// It is intentionally NOT wired into appCatalogs until the full stable source key set is complete.
export const beCatalog = {
  'localization.language.ru': 'Руская',
  'localization.language.en': 'English',
  'localization.language.label': 'Мова',
  'localization.language.help': 'Мова інтэрфейсу захоўваецца на гэтай прыладзе асобна ад гульнявога прагрэсу.',

  'common.back': 'Назад',
  'common.navigation': 'Навігацыя',
  'common.settings': 'Налады',
  'common.on': 'ON',
  'common.off': 'OFF',
  'common.enabled': 'Уключана',
  'common.disabled': 'Выключана',
  'common.available': 'даступна',
  'common.unavailable': 'недаступна',

  'menu.eyebrow': 'SEIRAN COLLEGE · CASE 001',
  'menu.title': 'Дэтэктывы',
  'menu.titleAccent': 'класа U',
  'menu.tagline': 'Камедыйная візуальная навела × match‑3',
  'menu.heroAria': 'Міку, Оноэ і Аюкі',
  'menu.newGame': 'Новая гульня',
  'menu.continue': 'Працягнуць',
  'menu.settings': 'Налады',
  'menu.sceneNavigation': 'Навігацыя па сцэнах',
  'menu.levelLab': 'Level Lab',
  'menu.sceneStudio': 'Студыя сцэн',
  'menu.match3Campaign': 'Match-3 кампанія',
  'menu.saveDiagnostics': 'Захаванні і дыягностыка',
  'menu.scriptLines': '{count} радкоў сцэнарыя',

  'settings.eyebrow': 'CONFIG · SYSTEM',
  'settings.title': 'Налады',
  'settings.audioHeading': 'Гук і водгук',
  'settings.audioCopy': 'Музыка і SFX ствараюцца лакальна праз Web Audio і не патрабуюць загрузкі аўдыяфайлаў. Налады захоўваюцца асобна ад гульнявога прагрэсу.',
  'settings.languageHeading': 'Мова',
  'settings.installHeading': 'Усталяванне і афлайн',
  'settings.mobileContractTitle': 'Мабільны кантракт',
  'settings.mobileContractCopy': 'Гук актывуецца толькі пасля першага дотыку або націску клавішы. Калі ўкладка пераходзіць у фон, музыка прыпыняецца і бяспечна аднаўляецца пасля вяртання.',
  'settings.navigationLabel': 'НАВІГАЦЫЯ',
  'settings.mainMenu': 'Галоўнае меню',
  'settings.mainMenuMatchWarning': 'Бягучая спроба запатрабуе пацвярджэння',
  'settings.mainMenuSafe': 'Захаваны прагрэс не страціцца',

  'audio.music': 'Музыка',
  'audio.effects': 'Эфекты',
  'audio.musicVolumeAria': 'Гучнасць музыкі',
  'audio.effectsVolumeAria': 'Гучнасць эфектаў',
  'audio.mute': 'Без гуку',
  'audio.haptics': 'Тактыльны водгук',
  'audio.hapticsSupported': 'Падтрымліваецца гэтай прыладай',
  'audio.hapticsUnavailable': 'Недаступна ў гэтым браўзеры',
  'audio.previewMusic': '▶ Праверыць музыку',
  'audio.previewEffects': '✦ Праверыць SFX',
  'audio.webAudio': 'Web Audio',
  'audio.hapticsCapability': 'Тактыльны водгук',
  'audio.hapticsAvailable': 'даступны',
  'audio.hapticsFallback': 'рэжым без вібрацыі',

  'pwa.install.installed': 'Усталявана',
  'pwa.install.available': 'Можна ўсталяваць',
  'pwa.install.browserMenu': 'Праз меню браўзера',
  'pwa.online': 'анлайн',
  'pwa.offline': 'афлайн',
  'pwa.cacheFailures': '{count} памылак кэша',
  'pwa.installAction': 'Усталяваць',
  'pwa.checkUpdate': 'Праверыць абнаўленне',

  // ANM-029B2A — Belarusian Match-3 core/campaign scope.
  'match3.investigation': 'РАССЛЕДАВАННЕ {current}/{total}',
  'match3.investigationNavigation': 'Навігацыя расследавання',
  'match3.moves': 'хадоў',
  'match3.start': 'Пачаць пошук',
  'match3.emptyCell': 'Пустая клетка',
  'match3.holeCell': 'Неактыўная клетка поля',
  'match3.backToInvestigation': 'Назад да расследавання',
  'match3.objectivesAria': 'Мэты расследавання',
  'match3.objective': 'МЭТА',
  'match3.movesStageAria': 'Хады і этап',
  'match3.movesUpper': 'ХАДЫ',
  'match3.stage': 'ЭТАП {current}/{total}',
  'match3.boardAria': 'Поле 8 на 8',
  'match3.teamAria': 'Каманда расследавання',
  'match3.hint': 'ПАДКАЗКА',
  'match3.bestMove': 'Найлепшы ход',
  'match3.inputHint': 'Перацягніце фішку, правядзіце пальцам або выберыце дзве суседнія · падказка ўлічвае мэты.',
  'match3.tutorial.label': 'НАВУЧАННЕ',
  'match3.tutorial.basic-swap.title': 'Збірайце аднолькавыя прадметы',
  'match3.tutorial.basic-swap.body': 'Складзіце лінію з трох або больш аднолькавых фішак. Перацягніце фішку на суседнюю клетку або дакраніцеся да дзвюх суседніх фішак па чарзе.',
  'match3.tutorial.clear-blocker.title': 'Прыбірайце перашкоды',
  'match3.tutorial.clear-blocker.body': 'Супадзенні на клетцы з перашкодай або побач з ёй здымаюць адзін слой. Некаторыя перашкоды патрабуюць некалькіх трапленняў — працягвайце складаць камбінацыі побач.',
  'match3.tutorial.drop-ingredient.title': 'Апускайце сюжэтныя прадметы',
  'match3.tutorial.drop-ingredient.body': 'Сюжэтныя прадметы нельга мяняць месцамі. Вызваляйце клеткі пад імі, каб яны падалі ўніз, і давядзіце прадмет да ніжняга краю поля.',
  'match3.tutorial.activate-special.title': 'Актывуйце спецфішку',
  'match3.tutorial.activate-special.body': "Доўгія або фігурныя супадзенні ствараюць спецыяльныя інструменты расследавання. Калі такі інструмент з'явіцца, двойчы дакраніцеся да яго, каб адразу актываваць эфект. Спецфішкі таксама можна мяняць месцамі, а іх камбінацыі разгледзім асобна.",
  'match3.tutorial.combine-specials.title': 'Спалучайце спецфішкі',
  'match3.tutorial.combine-specials.body': "Калі дзве спецфішкі стаяць побач, памяняйце іх месцамі. Іх эфекты аб'яднаюцца ва ўзмоцнены ход расследавання, а розныя пары спецфішак могуць спрацоўваць па-рознаму.",
  'match3.tutorial.try': 'ПАСПРАБАВАЦЬ',
  'match3.evidenceFound': 'ДОКАЗ ЗНОЙДЗЕНЫ',
  'match3.continueStory': 'Працягнуць сцэну',
  'match3.result': 'Вынік',
  'match3.lossHeading': 'Версію трэба праверыць яшчэ раз',
  'match3.retry': 'Паўтарыць узровень',
  'match3.special.flash-row': 'Гарызантальная ўспышка',
  'match3.special.flash-column': 'Вертыкальная ўспышка',
  'match3.special.evidence': 'Доказ',
  'match3.special.lead': 'Зачэпка',
  'match3.special.insight': 'Азаранне',
  'match3.feedback.special': 'НАЗІРАННЕ!',
  'match3.feedback.chain': 'ЛАНЦУЖОК ×{count}',
  'match3.feedback.combo': 'КОМБА!',
  'match3.feedback.match': 'СУПАДЗЕННЕ',
  'match3.feedback.reshuffled': 'ПОЛЕ ПЕРАМЕШАНА',
  'match3.feedback.noMatch': 'НЯМА СУПАДЗЕННЯ',
  'match3.feedback.swapUnavailable': 'АБМЕН НЕДАСТУПНЫ',
  'match3.feedback.clueCollected': 'ДОКАЗ САБРАНЫ',
  'match3.feedback.outOfMoves': 'ХАДЫ СКОНЧЫЛІСЯ',
  'match3.bark.noHint': 'Поле не дае карэктнага абмену. Патрэбна перастаноўка.',
  'match3.bark.hintFound': 'Гэты абмен найлепш прасоўвае бягучыя мэты расследавання.',
  'match3.bark.edge': 'За краем поля абмену няма. Паспрабуем суседнюю клетку.',
  'match3.bark.ingredientInvalid': 'Сюжэтны прадмет трэба апусціць уніз супадзеннямі пад ім.',
  'match3.bark.blockedInvalid': 'Гэтая секцыя зачыненая. Спачатку складзём супадзенне побач.',
  'match3.bark.noMatchInvalid': 'Гэты абмен не ўтварае шэраг. Праверым суседнія катэгорыі.',
  'match3.bark.special': 'Калі паглядзець на ўсё адразу, беспарадак ператвараецца ва ўзор.',
  'match3.bark.cascade': 'Ланцужок назіранняў: {count}. Гэта ўжо амаль дэдукцыя.',
  'match3.tile.camisole': 'Тканіна',
  'match3.tile.laundryTag': 'Бірка',
  'match3.tile.panties': 'Камплект',
  'match3.tile.towel': 'Ручнік',
  'match3.tile.socks': 'Пара',
  'match3.tile.sportsBra': 'Спорт',

  'match3Campaign.eyebrow': 'MATCH-3 КАМПАНІЯ',
  'match3Campaign.title': 'Дошка спраў',
  'match3Campaign.summary': 'Праходзьце расследаванні як асобную match-3 кампанію. Яе прагрэс не звязаны з захаваннем візуальнай навелы.',
  'match3Campaign.progress': 'Пройдзена {completed}/{total}',
  'match3Campaign.complete': 'КАМПАНІЯ ПРОЙДЗЕНА · УСЕ ЎЗРОЎНІ ДАСТУПНЫЯ ДЛЯ ПАЎТОРУ',
  'match3Campaign.locked': 'ЗАЧЫНЕНА',
  'match3Campaign.completed': 'ПРОЙДЗЕНА',
  'match3Campaign.available': 'ДАСТУПНА',
  'match3Campaign.attempts': 'Спроб: {count}',
  'match3Campaign.best': 'Найлепшы вынік: засталося {moves} хадоў',
  'match3Campaign.replay': 'Паўтарыць',
  'match3Campaign.play': 'Пачаць узровень',
  'match3Campaign.backToCampaign': 'Назад у кампанію',
  'match3Campaign.stage': 'КАМПАНІЯ {current}/{total}',
  'match3Campaign.winEyebrow': 'УЗРОВЕНЬ ПРОЙДЗЕНЫ',
  'match3Campaign.lossEyebrow': 'ХАДЫ СКОНЧЫЛІСЯ',
  'match3Campaign.winHeading': 'Дошка расследавання вырашана',
  'match3Campaign.lossHeading': 'Паспрабуйце ўзровень яшчэ раз',
  'match3Campaign.resultDetail': 'Засталося хадоў: {movesLeft}. Прагрэс match-3 кампаніі захоўваецца асобна ад сюжэту.',
  'match3Campaign.nextLevel': 'Наступны ўзровень',
  'match3Campaign.retry': 'Паўтарыць узровень',

} as const satisfies MessageCatalog;

export const beCompletedCatalogPrefixes = [
  'localization',
  'common',
  'menu',
  'settings',
  'audio',
  'pwa',
] as const;
