import type { MessageCatalog } from '../MessageCatalog';

export const enCatalog = {
  'localization.language.ru': 'Русский',
  'localization.language.en': 'English',
  'localization.language.label': 'Language',
  'localization.language.help': 'Interface language is saved on this device separately from game progress.',

  'common.back': 'Back',
  'common.navigation': 'Navigation',
  'common.settings': 'Settings',
  'common.on': 'ON',
  'common.off': 'OFF',
  'common.enabled': 'Enabled',
  'common.disabled': 'Disabled',
  'common.available': 'available',
  'common.unavailable': 'unavailable',

  'menu.eyebrow': 'SEIRAN COLLEGE · CASE 001',
  'menu.title': 'Class U',
  'menu.titleAccent': 'Detectives',
  'menu.tagline': 'Comedy visual novel × match‑3',
  'menu.heroAria': 'Miku, Onoe and Ayuki',
  'menu.newGame': 'New Game',
  'menu.continue': 'Continue',
  'menu.settings': 'Settings',
  'menu.sceneNavigation': 'Scene Navigation',
  'menu.saveDiagnostics': 'Saves & Diagnostics',
  'menu.scriptLines': '{count} screenplay lines',

  'settings.eyebrow': 'CONFIG · SYSTEM',
  'settings.title': 'Settings',
  'settings.audioHeading': 'Audio & Feedback',
  'settings.audioCopy': 'Music and SFX are generated locally through Web Audio and require no audio-file downloads. These settings are stored separately from game progress.',
  'settings.languageHeading': 'Language',
  'settings.installHeading': 'Install & Offline',
  'settings.mobileContractTitle': 'Mobile contract',
  'settings.mobileContractCopy': 'Audio activates only after the first touch or key press. Music pauses when the tab is backgrounded and resumes safely when you return.',
  'settings.navigationLabel': 'NAVIGATION',
  'settings.mainMenu': 'Main Menu',
  'settings.mainMenuMatchWarning': 'The current attempt will require confirmation',
  'settings.mainMenuSafe': 'Saved progress will not be lost',

  'audio.music': 'Music',
  'audio.effects': 'Effects',
  'audio.musicVolumeAria': 'Music volume',
  'audio.effectsVolumeAria': 'Effects volume',
  'audio.mute': 'Mute',
  'audio.haptics': 'Haptics',
  'audio.hapticsSupported': 'Supported by this device',
  'audio.hapticsUnavailable': 'Unavailable in this browser',
  'audio.previewMusic': '▶ Preview music',
  'audio.previewEffects': '✦ Preview SFX',
  'audio.webAudio': 'Web Audio',
  'audio.hapticsCapability': 'Haptics',
  'audio.hapticsAvailable': 'available',
  'audio.hapticsFallback': 'fallback without vibration',

  'pwa.install.installed': 'Installed',
  'pwa.install.available': 'Ready to install',
  'pwa.install.browserMenu': 'Use browser menu',
  'pwa.online': 'online',
  'pwa.offline': 'offline',
  'pwa.cacheFailures': '{count} cache failures',
  'pwa.installAction': 'Install',
  'pwa.checkUpdate': 'Check for update',
} as const satisfies MessageCatalog;
