import type { MessageCatalog } from '../MessageCatalog';

export const enCatalog = {
  'localization.language.ru': 'Русский',
  'localization.language.en': 'English',
  'localization.language.label': 'Language',
  'localization.language.help': 'Interface language is saved on this device separately from game progress.',

  'common.back': 'Back',
  'common.navigation': 'Navigation',
  'common.settings': 'Settings',
  'common.on': 'ON',
  'common.off': 'OFF',
  'common.enabled': 'Enabled',
  'common.disabled': 'Disabled',
  'common.available': 'available',
  'common.unavailable': 'unavailable',

  'menu.eyebrow': 'SEIRAN COLLEGE · CASE 001',
  'menu.title': 'Class U',
  'menu.titleAccent': 'Detectives',
  'menu.tagline': 'Comedy visual novel × match‑3',
  'menu.heroAria': 'Miku, Onoe and Ayuki',
  'menu.newGame': 'New Game',
  'menu.continue': 'Continue',
  'menu.settings': 'Settings',
  'menu.sceneNavigation': 'Scene Navigation',
  'menu.saveDiagnostics': 'Saves & Diagnostics',
  'menu.scriptLines': '{count} screenplay lines',

  'settings.eyebrow': 'CONFIG · SYSTEM',
  'settings.title': 'Settings',
  'settings.audioHeading': 'Audio & Feedback',
  'settings.audioCopy': 'Music and SFX are generated locally through Web Audio and require no audio-file downloads. These settings are stored separately from game progress.',
  'settings.languageHeading': 'Language',
  'settings.installHeading': 'Install & Offline',
  'settings.mobileContractTitle': 'Mobile contract',
  'settings.mobileContractCopy': 'Audio activates only after the first touch or key press. Music pauses when the tab is backgrounded and resumes safely when you return.',
  'settings.navigationLabel': 'NAVIGATION',
  'settings.mainMenu': 'Main Menu',
  'settings.mainMenuMatchWarning': 'The current attempt will require confirmation',
  'settings.mainMenuSafe': 'Saved progress will not be lost',

  'audio.music': 'Music',
  'audio.effects': 'Effects',
  'audio.musicVolumeAria': 'Music volume',
  'audio.effectsVolumeAria': 'Effects volume',
  'audio.mute': 'Mute',
  'audio.haptics': 'Haptics',
  'audio.hapticsSupported': 'Supported by this device',
  'audio.hapticsUnavailable': 'Unavailable in this browser',
  'audio.previewMusic': '▶ Preview music',
  'audio.previewEffects': '✦ Preview SFX',
  'audio.webAudio': 'Web Audio',
  'audio.hapticsCapability': 'Haptics',
  'audio.hapticsAvailable': 'available',
  'audio.hapticsFallback': 'fallback without vibration',

  'pwa.install.installed': 'Installed',
  'pwa.install.available': 'Ready to install',
  'pwa.install.browserMenu': 'Use browser menu',
  'pwa.online': 'online',
  'pwa.offline': 'offline',
  'pwa.cacheFailures': '{count} cache failures',
  'pwa.installAction': 'Install',
  'pwa.checkUpdate': 'Check for update',

  'vn.chrome.openDossier': 'Open dossier',
  'vn.chrome.navigation': 'Visual novel navigation',
  'vn.chrome.history': 'Dialogue history',
  'vn.chrome.direction': 'STAGE DIRECTION',
  'vn.chrome.controls': 'Visual novel controls',
  'vn.chrome.dossierUpdated': 'DOSSIER UPDATED',
  'vn.status.saved': 'Manual slot saved',
  'vn.status.saveFailed': 'Could not save manual slot',
  'vn.status.emptySlot': 'Manual slot is empty',
  'vn.status.skipReadOnly': 'SKIP is available only for previously read lines',

  'vn.choice.header': 'Choose an approach',
  'vn.choice.prompt': 'Where do we start?',
  'vn.choice.A.title': 'Find the second victim first',
  'vn.choice.A.effect': 'Source trust +1',
  'vn.choice.B.title': 'Warn them anonymously',
  'vn.choice.B.effect': 'Rumor heat +1',
  'vn.choice.C.title': 'Report the case to administration',
  'vn.choice.C.effect': 'Onoe trust +1',

  'vn.scene.VN_SCENE_00_PROLOGUE.title': 'The Club That Barely Exists',
  'vn.scene.VN_SCENE_00_PROLOGUE.location': 'Detective Club Room',
  'vn.scene.VN_SCENE_01_E0_PRE.title': 'The Case of Class U',
  'vn.scene.VN_SCENE_01_E0_PRE.location': 'Club Room → Locker Room',
  'vn.scene.VN_SCENE_02_E0_POST.title': 'What the Thief Left Behind',
  'vn.scene.VN_SCENE_02_E0_POST.location': 'Track & Field Locker Room',
  'vn.scene.VN_SCENE_03_E1_PRE.title': 'The Room That Explains Too Little',
  'vn.scene.VN_SCENE_03_E1_PRE.location': "Kentaro's Apartment",
  'vn.scene.VN_SCENE_04_E1_POST.title': 'The Mannequin with the Best Alibi',
  'vn.scene.VN_SCENE_04_E1_POST.location': "Kentaro's Apartment",
  'vn.scene.VN_SCENE_05_E2_PRE.title': 'Wet Testimony',
  'vn.scene.VN_SCENE_05_E2_PRE.location': 'Swimming Club Locker Room',
  'vn.scene.VN_SCENE_06_E2_POST.title': 'A Tasteless Table',
  'vn.scene.VN_SCENE_06_E2_POST.location': 'Swimming Club Locker Room',
  'vn.scene.VN_SCENE_07_E3_PRE.title': 'A Pink Confession',
  'vn.scene.VN_SCENE_07_E3_PRE.location': "Norihiro's Apartment",
  'vn.scene.VN_SCENE_08_E3_POST.title': "That's Not Fabric",
  'vn.scene.VN_SCENE_08_E3_POST.location': "Norihiro's Apartment",

  'vn.line.VN0001.speaker': 'STAGE DIRECTION',
  'vn.line.VN0001.emotion': 'FADE IN',
  'vn.line.VN0001.text': 'After the bell. A narrow former storage room: a board, two chairs, a folding table, and a “Detective Club” sign taped over the word “Equipment”.',
  'vn.line.VN0002.speaker': 'MIKU (THOUGHTS)',
  'vn.line.VN0002.emotion': 'CAUTIOUS',
  'vn.line.VN0002.text': 'The brochure called this “a space for student initiatives”.',
  'vn.line.VN0003.speaker': 'MIKU (THOUGHTS)',
  'vn.line.VN0003.emotion': 'DRY',
  'vn.line.VN0003.text': 'The brochure did not mention the mop behind the curtain.',
  'vn.line.VN0004.speaker': 'ONOE',
  'vn.line.VN0004.emotion': 'FOCUSED',
  'vn.line.VN0004.text': 'Clause four: the club agrees not to conduct interrogations without the participant’s consent.',
  'vn.line.VN0005.speaker': 'AYUKI',
  'vn.line.VN0005.emotion': 'CHEERFUL',
  'vn.line.VN0005.text': 'Too negative. Write: “We respect a suspect’s right to a dramatic entrance”.',
  'vn.line.VN0006.speaker': 'ONOE',
  'vn.line.VN0006.emotion': 'WITHOUT LOOKING UP',
  'vn.line.VN0006.text': 'That is not a right.',
  'vn.line.VN0007.speaker': 'AYUKI',
  'vn.line.VN0007.emotion': 'THOUGHTFUL',
  'vn.line.VN0007.text': 'Not yet.',
  'vn.line.VN0008.speaker': 'MIKU',
  'vn.line.VN0008.emotion': 'UNCERTAIN',
  'vn.line.VN0008.text': 'Excuse me… is this the detective club meeting?',
  'vn.line.VN0009.speaker': 'AYUKI',
  'vn.line.VN0009.emotion': 'TURNS TO MIKU',
  'vn.line.VN0009.text': 'Depends. Are you a client, a witness, or our long-awaited third member?',
  'vn.line.VN0010.speaker': 'MIKU',
  'vn.line.VN0010.emotion': 'EMBARRASSED',
  'vn.line.VN0010.text': 'I thought I would just look around first.',
  'vn.line.VN0011.speaker': 'ONOE',
  'vn.line.VN0011.emotion': 'APPRAISING',
  'vn.line.VN0011.text': 'Observation is an acceptable specialization.',
  'vn.line.VN0012.speaker': 'AYUKI',
  'vn.line.VN0012.emotion': 'THEATRICAL',
  'vn.line.VN0012.text': 'Accepted unanimously.',
  'vn.line.VN0013.speaker': 'MIKU',
  'vn.line.VN0013.emotion': 'SURPRISED',
  'vn.line.VN0013.text': 'You have not voted yet.',
  'vn.line.VN0014.speaker': 'ONOE',
  'vn.line.VN0014.emotion': 'NEUTRAL',
  'vn.line.VN0014.text': 'There are two of us. Unanimity happens quickly.',
  'vn.line.VN0015.speaker': 'MIKU (THOUGHTS)',
  'vn.line.VN0015.emotion': 'IRONIC',
  'vn.line.VN0015.text': 'I came to draw a poster. Forty seconds later I had a position.',
  'vn.line.VN0016.speaker': 'AYUKI',
  'vn.line.VN0016.emotion': 'HOLDING A SHEET',
  'vn.line.VN0016.text': 'We only need a name: “The Eye of Seiran”, “Three Alibis”, or “Beauties of Deduction”.',
  'vn.line.VN0017.speaker': 'ONOE',
  'vn.line.VN0017.emotion': 'COLD',
  'vn.line.VN0017.text': 'The last name reduces our evidentiary value.',
  'vn.line.VN0018.speaker': 'MIKU',
  'vn.line.VN0018.emotion': 'LOOKS AT THE SIGN',
  'vn.line.VN0018.text': 'Does the club have official status?',
  'vn.line.VN0019.speaker': 'ONOE',
  'vn.line.VN0019.emotion': 'PAUSE',
  'vn.line.VN0019.text': 'The application is almost ready.',
  'vn.line.VN0020.speaker': 'AYUKI',
  'vn.line.VN0020.emotion': 'QUIETLY TO MIKU',
  'vn.line.VN0020.text': 'That is a chemically precise “no”.',
  'vn.line.VN0021.speaker': 'MIKU (THOUGHTS)',
  'vn.line.VN0021.emotion': 'WARY',
  'vn.line.VN0021.text': 'Apparently this club solves mysteries and administrative problems in equal proportions.',
  'vn.line.VN0022.speaker': 'STAGE DIRECTION',
  'vn.line.VN0022.emotion': 'PHONE VIBRATION',
  'vn.line.VN0022.text': 'Ayuki’s phone vibrates on the table. The three of them look at the screen.',
  'vn.history.aria': 'Dialogue history',
  'vn.history.title': 'Dialogue history',
  'vn.history.empty': 'Previously read lines will appear here.',
  'vn.history.close': 'Close',
  'vn.config.aria': 'Reading settings',
  'vn.config.title': 'Reading settings',
  'vn.config.close': 'Close',
  'vn.config.autoSpeed': 'AUTO speed',
  'vn.config.slow': 'Slow',
  'vn.config.normal': 'Normal',
  'vn.config.fast': 'Fast',
  'vn.config.textSize': 'Text size',
  'vn.config.large': 'Large',
  'vn.config.audio': 'Sound & feedback',
  'vn.config.navigation': 'NAVIGATION',
  'vn.config.mainMenu': 'Main Menu',
  'vn.config.saved': 'Current position is saved',
  'vn.config.note': 'AUTO speed and text size apply to the current session. Audio settings persist between launches. System Reduced Motion still takes priority for animations.',
  // ANM-019E1 · Dossier & ending
  'dossier.case': 'CASE 001',
  'dossier.title': 'Dossier',
  'dossier.heading': 'Serial Disappearances',
  'dossier.tab.clues': 'Clues',
  'dossier.tab.theories': 'Theories',
  'dossier.tab.timeline': 'Timeline',
  'dossier.clueNumber': 'CLUE 0{number}',
  'dossier.locked': 'Locked',
  'dossier.unlockHint': 'Win the corresponding investigation to unlock it.',
  'dossier.theoriesHeading': 'Theories Under Review',
  'character.kentaro': 'Kentaro',
  'character.norihiro': 'Norihiro',
  'dossier.kentaro.cleared': 'CLEARED BY TIMECODES',
  'dossier.kentaro.active': 'ACTIVE THEORY',
  'dossier.norihiro.cleared': 'THEORY CLOSED',
  'dossier.norihiro.pending': 'AWAITING VERIFICATION',
  'dossier.reset': 'Reset progress',
  'ending.case': 'CASE 001',
  'ending.chapterComplete': 'Chapter Complete',
  'ending.clueAlt': 'Conductive seam',
  'ending.eyebrow': 'END OF VERTICAL SLICE',
  'ending.heading': 'The first thread is found.',
  'ending.copy': 'The chapter ends at VN0249. The silver-turquoise conductive thread takes the investigation beyond an ordinary theft.',
  'ending.choice': 'Choice',
  'ending.cluesFound': 'Clues found',
  'ending.mainMenu': 'Main Menu',
  'ending.replay': 'Start Over',
  'match3.level.M3_00_LOCKER_TUTORIAL.clueTitle': 'Selective Disappearance',
  'match3.level.M3_00_LOCKER_TUTORIAL.clueSummary': 'Not everything vanished from the laundry batch; price and visibility do not explain the selection.',
  'match3.level.M3_01_PHOTO_PROPS.clueTitle': 'Verifiable Alibi',
  'match3.level.M3_01_PHOTO_PROPS.clueSummary': 'The shoot timecodes confirm Kentaro\'s alibi; the service cart remains the common link.',
  'match3.level.M3_02_POOL_LAUNDRY.clueTitle': 'Mixed Targets',
  'match3.level.M3_02_POOL_LAUNDRY.clueSummary': 'Item type, price, color, and owner do not explain the selection; the items were mixed before they were returned.',
  'match3.level.M3_03_ORDERED_APARTMENT.clueTitle': 'Silver Thread',
  'match3.level.M3_03_ORDERED_APARTMENT.clueSummary': 'Nothing was stolen, but a new conductive seam appeared beneath the service tag.',

  // ANM-019E2 · Match-3
  'character.miku': 'Miku',
  'character.onoe': 'Onoe',
  'character.ayuki': 'Ayuki',
  'character.emi': 'Emi',
  'match3.investigation': 'INVESTIGATION {current}/{total}',
  'match3.investigationNavigation': 'Investigation navigation',
  'match3.moves': 'moves',
  'match3.start': 'Start Search',
  'match3.emptyCell': 'Empty cell',
  'match3.backToInvestigation': 'Back to investigation',
  'match3.objectivesAria': 'Investigation objectives',
  'match3.objective': 'OBJECTIVE',
  'match3.movesStageAria': 'Moves and stage',
  'match3.movesUpper': 'MOVES',
  'match3.stage': 'STAGE {current}/{total}',
  'match3.boardAria': '8 by 8 board',
  'match3.teamAria': 'Investigation team',
  'match3.hint': 'HINT',
  'match3.bestMove': 'Best move',
  'match3.inputHint': 'Drag a tile, swipe, or select two adjacent cells · hints account for objectives.',
  'match3.evidenceFound': 'CLUE FOUND',
  'match3.continueStory': 'Continue Scene',
  'match3.result': 'Result',
  'match3.lossHeading': 'The theory needs another check',
  'match3.retry': 'Retry Level',
  'match3.feedback.special': 'OBSERVATION!',
  'match3.feedback.chain': 'CHAIN ×{count}',
  'match3.feedback.match': 'MATCH',
  'match3.feedback.reshuffled': 'BOARD SHUFFLED',
  'match3.feedback.noMatch': 'NO MATCH',
  'match3.feedback.swapUnavailable': 'SWAP UNAVAILABLE',
  'match3.feedback.clueCollected': 'CLUE COLLECTED',
  'match3.feedback.outOfMoves': 'OUT OF MOVES',
  'match3.bark.noHint': 'The board has no valid exchange. It needs a reshuffle.',
  'match3.bark.hintFound': 'This swap advances the current investigation objectives best.',
  'match3.bark.edge': 'There is no swap beyond the edge. Try a neighboring cell.',
  'match3.bark.ingredientInvalid': 'Story items must be dropped by making matches beneath them.',
  'match3.bark.blockedInvalid': 'This section is locked. Make a match beside it first.',
  'match3.bark.noMatchInvalid': 'That swap does not make a row. Check the neighboring categories.',
  'match3.bark.special': 'Seen all at once, the mess starts turning into a pattern.',
  'match3.bark.fiveMoves.0': 'Almost there. We need the link to the laundry.',
  'match3.bark.fiveMoves.1': 'If you lose it again, this becomes a collective alibi.',
  'match3.bark.fiveMoves.2': 'We need the cabinet. The return log is inside.',
  'match3.bark.fiveMoves.3': 'We need both objects. Without the receipt, the theory stays open.',
  'match3.bark.blockers.0': 'Clue U-1 is free. No, I did not name it.',
  'match3.bark.blockers.1': 'Dense packing. One hit opens it; the second frees the contents.',
  'match3.bark.blockers.2': 'Items from different sections are under the foam. They were mixed before the lockers.',
  'match3.bark.blockers.3': 'No stash, no accomplice. This apartment has no sense of drama.',
  'match3.bark.ingredient.0': 'The document is in the upper section. Clear a path to the bottom edge.',
  'match3.bark.ingredient.1': 'Tiny black card, enormous potential for drama.',
  'match3.bark.ingredient.2': 'The key surfaced. Metaphorically. Literally, it is moving downward.',
  'match3.bark.ingredient.3': 'We need both documents: the receipt and the towel with the altered edge.',
  'match3.bark.cascade': 'Chain of observations: {count}. That is almost deduction.',
  'match3.tile.camisole': 'Fabric',
  'match3.tile.laundryTag': 'Tag',
  'match3.tile.panties': 'Set',
  'match3.tile.towel': 'Towel',
  'match3.tile.socks': 'Pair',
  'match3.tile.sportsBra': 'Sportswear',
  'match3.ingredient.receipt': 'Receipt',
  'match3.ingredient.memoryCard': 'Memory card',
  'match3.ingredient.serviceKey': 'Service key',
  'match3.ingredient.damagedTowel': 'Towel with seam',
  'match3.clue.CUE_001': 'Laundry receipt',
  'match3.clue.CUE_002': 'Memory card',
  'match3.clue.CUE_003': 'Service key',
  'match3.clue.CUE_004': 'Conductive seam',
  'match3.level.M3_00_LOCKER_TUTORIAL.title': 'Emi\'s Locker',
  'match3.level.M3_00_LOCKER_TUTORIAL.storyAction': 'Document the locker contents and find the link to the laundry.',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.0': 'Fabric',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.1': 'Tags',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.2': 'Sets',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.3': 'Cells',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.4': 'Receipt',
  'match3.level.M3_00_LOCKER_TUTORIAL.startBark.speaker': 'Onoe',
  'match3.level.M3_00_LOCKER_TUTORIAL.startBark.text': 'Categories first. Conclusions second.',
  'match3.level.M3_00_LOCKER_TUTORIAL.winBark.speaker': 'Emi',
  'match3.level.M3_00_LOCKER_TUTORIAL.winBark.text': 'Did you find anything real?',
  'match3.level.M3_01_PHOTO_PROPS.title': 'Kentaro\'s Photo Props',
  'match3.level.M3_01_PHOTO_PROPS.storyAction': 'Sort the props by number and find the memory card with timecodes.',
  'match3.level.M3_01_PHOTO_PROPS.objective.0': 'Boxes',
  'match3.level.M3_01_PHOTO_PROPS.objective.1': 'Tags',
  'match3.level.M3_01_PHOTO_PROPS.objective.2': 'Card',
  'match3.level.M3_01_PHOTO_PROPS.startBark.speaker': 'Kentaro',
  'match3.level.M3_01_PHOTO_PROPS.startBark.text': 'Numbers first. And do not wear anything — those are props.',
  'match3.level.M3_01_PHOTO_PROPS.winBark.speaker': 'Miku',
  'match3.level.M3_01_PHOTO_PROPS.winBark.text': 'Found it. Now we look at the time, not the room.',
  'match3.level.M3_02_POOL_LAUNDRY.title': 'Wet Testimony',
  'match3.level.M3_02_POOL_LAUNDRY.storyAction': 'Reconstruct the laundry batch, clear the foam, and open the service cabinet.',
  'match3.level.M3_02_POOL_LAUNDRY.objective.0': 'Foam',
  'match3.level.M3_02_POOL_LAUNDRY.objective.1': 'Tags',
  'match3.level.M3_02_POOL_LAUNDRY.objective.2': 'Key',
  'match3.level.M3_02_POOL_LAUNDRY.startBark.speaker': 'Norihiro',
  'match3.level.M3_02_POOL_LAUNDRY.startBark.text': 'Tags first. Wet guesses take longer to dry than towels.',
  'match3.level.M3_02_POOL_LAUNDRY.winBark.speaker': 'Onoe',
  'match3.level.M3_02_POOL_LAUNDRY.winBark.text': 'The batch is reconstructed. Now compare what went missing.',
  'match3.level.M3_03_ORDERED_APARTMENT.title': 'Perfect Order',
  'match3.level.M3_03_ORDERED_APARTMENT.storyAction': 'Check the returned bag and find the item with new damage.',
  'match3.level.M3_03_ORDERED_APARTMENT.objective.0': 'Sections',
  'match3.level.M3_03_ORDERED_APARTMENT.objective.1': 'Pairs',
  'match3.level.M3_03_ORDERED_APARTMENT.objective.2': 'Receipt',
  'match3.level.M3_03_ORDERED_APARTMENT.objective.3': 'Towel',
  'match3.level.M3_03_ORDERED_APARTMENT.startBark.speaker': 'Norihiro',
  'match3.level.M3_03_ORDERED_APARTMENT.startBark.text': 'Left to right. If you disturb the order, you will restore it.',
  'match3.level.M3_03_ORDERED_APARTMENT.winBark.speaker': 'Miku',
  'match3.level.M3_03_ORDERED_APARTMENT.winBark.text': 'Nothing was stolen here. But something was added.',

} as const satisfies MessageCatalog;
