import type { MessageCatalog } from '../MessageCatalog';

export const enCatalog = {
  'localization.language.ru': 'Русский',
  'localization.language.en': 'English',
  'localization.language.label': 'Language',
  'localization.language.help': 'Interface language is saved on this device separately from game progress.',

  'common.back': 'Back',
  'common.navigation': 'Navigation',
  'common.settings': 'Settings',
  'common.on': 'ON',
  'common.off': 'OFF',
  'common.enabled': 'Enabled',
  'common.disabled': 'Disabled',
  'common.available': 'available',
  'common.unavailable': 'unavailable',

  'menu.eyebrow': 'SEIRAN COLLEGE · CASE 001',
  'menu.title': 'Class U',
  'menu.titleAccent': 'Detectives',
  'menu.tagline': 'Comedy visual novel × match‑3',
  'menu.heroAria': 'Miku, Onoe and Ayuki',
  'menu.newGame': 'New Game',
  'menu.continue': 'Continue',
  'menu.settings': 'Settings',
  'menu.sceneNavigation': 'Scene Navigation',
  'menu.saveDiagnostics': 'Saves & Diagnostics',
  'menu.scriptLines': '{count} screenplay lines',

  'settings.eyebrow': 'CONFIG · SYSTEM',
  'settings.title': 'Settings',
  'settings.audioHeading': 'Audio & Feedback',
  'settings.audioCopy': 'Music and SFX are generated locally through Web Audio and require no audio-file downloads. These settings are stored separately from game progress.',
  'settings.languageHeading': 'Language',
  'settings.installHeading': 'Install & Offline',
  'settings.mobileContractTitle': 'Mobile contract',
  'settings.mobileContractCopy': 'Audio activates only after the first touch or key press. Music pauses when the tab is backgrounded and resumes safely when you return.',
  'settings.navigationLabel': 'NAVIGATION',
  'settings.mainMenu': 'Main Menu',
  'settings.mainMenuMatchWarning': 'The current attempt will require confirmation',
  'settings.mainMenuSafe': 'Saved progress will not be lost',

  'audio.music': 'Music',
  'audio.effects': 'Effects',
  'audio.musicVolumeAria': 'Music volume',
  'audio.effectsVolumeAria': 'Effects volume',
  'audio.mute': 'Mute',
  'audio.haptics': 'Haptics',
  'audio.hapticsSupported': 'Supported by this device',
  'audio.hapticsUnavailable': 'Unavailable in this browser',
  'audio.previewMusic': '▶ Preview music',
  'audio.previewEffects': '✦ Preview SFX',
  'audio.webAudio': 'Web Audio',
  'audio.hapticsCapability': 'Haptics',
  'audio.hapticsAvailable': 'available',
  'audio.hapticsFallback': 'fallback without vibration',

  'pwa.install.installed': 'Installed',
  'pwa.install.available': 'Ready to install',
  'pwa.install.browserMenu': 'Use browser menu',
  'pwa.online': 'online',
  'pwa.offline': 'offline',
  'pwa.cacheFailures': '{count} cache failures',
  'pwa.installAction': 'Install',
  'pwa.checkUpdate': 'Check for update',

  'vn.chrome.openDossier': 'Open dossier',
  'vn.chrome.navigation': 'Visual novel navigation',
  'vn.chrome.history': 'Dialogue history',
  'vn.chrome.direction': 'STAGE DIRECTION',
  'vn.chrome.controls': 'Visual novel controls',
  'vn.chrome.dossierUpdated': 'DOSSIER UPDATED',
  'vn.status.saved': 'Manual slot saved',
  'vn.status.saveFailed': 'Could not save manual slot',
  'vn.status.emptySlot': 'Manual slot is empty',
  'vn.status.skipReadOnly': 'SKIP is available only for previously read lines',

  'vn.choice.header': 'Choose an approach',
  'vn.choice.prompt': 'Where do we start?',
  'vn.choice.A.title': 'Find the second victim first',
  'vn.choice.A.effect': 'Source trust +1',
  'vn.choice.B.title': 'Warn them anonymously',
  'vn.choice.B.effect': 'Rumor heat +1',
  'vn.choice.C.title': 'Report the case to administration',
  'vn.choice.C.effect': 'Onoe trust +1',

  'vn.scene.VN_SCENE_00_PROLOGUE.title': 'The Club That Barely Exists',
  'vn.scene.VN_SCENE_00_PROLOGUE.location': 'Detective Club Room',
  'vn.scene.VN_SCENE_01_E0_PRE.title': 'The Case of Class U',
  'vn.scene.VN_SCENE_01_E0_PRE.location': 'Club Room → Locker Room',
  'vn.scene.VN_SCENE_02_E0_POST.title': 'What the Thief Left Behind',
  'vn.scene.VN_SCENE_02_E0_POST.location': 'Track & Field Locker Room',
  'vn.scene.VN_SCENE_03_E1_PRE.title': 'The Room That Explains Too Little',
  'vn.scene.VN_SCENE_03_E1_PRE.location': "Kentaro's Apartment",
  'vn.scene.VN_SCENE_04_E1_POST.title': 'The Mannequin with the Best Alibi',
  'vn.scene.VN_SCENE_04_E1_POST.location': "Kentaro's Apartment",
  'vn.scene.VN_SCENE_05_E2_PRE.title': 'Wet Testimony',
  'vn.scene.VN_SCENE_05_E2_PRE.location': 'Swimming Club Locker Room',
  'vn.scene.VN_SCENE_06_E2_POST.title': 'A Tasteless Table',
  'vn.scene.VN_SCENE_06_E2_POST.location': 'Swimming Club Locker Room',
  'vn.scene.VN_SCENE_07_E3_PRE.title': 'A Pink Confession',
  'vn.scene.VN_SCENE_07_E3_PRE.location': "Norihiro's Apartment",
  'vn.scene.VN_SCENE_08_E3_POST.title': "That's Not Fabric",
  'vn.scene.VN_SCENE_08_E3_POST.location': "Norihiro's Apartment",

  'vn.line.VN0001.speaker': 'STAGE DIRECTION',
  'vn.line.VN0001.emotion': 'FADE IN',
  'vn.line.VN0001.text': 'After the bell. A narrow former storage room: a board, two chairs, a folding table, and a “Detective Club” sign taped over the word “Equipment”.',
  'vn.line.VN0002.speaker': 'MIKU (THOUGHTS)',
  'vn.line.VN0002.emotion': 'CAUTIOUS',
  'vn.line.VN0002.text': 'The brochure called this “a space for student initiatives”.',
  'vn.line.VN0003.speaker': 'MIKU (THOUGHTS)',
  'vn.line.VN0003.emotion': 'DRY',
  'vn.line.VN0003.text': 'The brochure did not mention the mop behind the curtain.',
  'vn.line.VN0004.speaker': 'ONOE',
  'vn.line.VN0004.emotion': 'FOCUSED',
  'vn.line.VN0004.text': 'Clause four: the club agrees not to conduct interrogations without the participant’s consent.',
  'vn.line.VN0005.speaker': 'AYUKI',
  'vn.line.VN0005.emotion': 'CHEERFUL',
  'vn.line.VN0005.text': 'Too negative. Write: “We respect a suspect’s right to a dramatic entrance”.',
  'vn.line.VN0006.speaker': 'ONOE',
  'vn.line.VN0006.emotion': 'WITHOUT LOOKING UP',
  'vn.line.VN0006.text': 'That is not a right.',
  'vn.line.VN0007.speaker': 'AYUKI',
  'vn.line.VN0007.emotion': 'THOUGHTFUL',
  'vn.line.VN0007.text': 'Not yet.',
  'vn.line.VN0008.speaker': 'MIKU',
  'vn.line.VN0008.emotion': 'UNCERTAIN',
  'vn.line.VN0008.text': 'Excuse me… is this the detective club meeting?',
  'vn.line.VN0009.speaker': 'AYUKI',
  'vn.line.VN0009.emotion': 'TURNS TO MIKU',
  'vn.line.VN0009.text': 'Depends. Are you a client, a witness, or our long-awaited third member?',
  'vn.line.VN0010.speaker': 'MIKU',
  'vn.line.VN0010.emotion': 'EMBARRASSED',
  'vn.line.VN0010.text': 'I thought I would just look around first.',
  'vn.line.VN0011.speaker': 'ONOE',
  'vn.line.VN0011.emotion': 'APPRAISING',
  'vn.line.VN0011.text': 'Observation is an acceptable specialization.',
  'vn.line.VN0012.speaker': 'AYUKI',
  'vn.line.VN0012.emotion': 'THEATRICAL',
  'vn.line.VN0012.text': 'Accepted unanimously.',
  'vn.line.VN0013.speaker': 'MIKU',
  'vn.line.VN0013.emotion': 'SURPRISED',
  'vn.line.VN0013.text': 'You have not voted yet.',
  'vn.line.VN0014.speaker': 'ONOE',
  'vn.line.VN0014.emotion': 'NEUTRAL',
  'vn.line.VN0014.text': 'There are two of us. Unanimity happens quickly.',
  'vn.line.VN0015.speaker': 'MIKU (THOUGHTS)',
  'vn.line.VN0015.emotion': 'IRONIC',
  'vn.line.VN0015.text': 'I came to draw a poster. Forty seconds later I had a position.',
  'vn.line.VN0016.speaker': 'AYUKI',
  'vn.line.VN0016.emotion': 'HOLDING A SHEET',
  'vn.line.VN0016.text': 'We only need a name: “The Eye of Seiran”, “Three Alibis”, or “Beauties of Deduction”.',
  'vn.line.VN0017.speaker': 'ONOE',
  'vn.line.VN0017.emotion': 'COLD',
  'vn.line.VN0017.text': 'The last name reduces our evidentiary value.',
  'vn.line.VN0018.speaker': 'MIKU',
  'vn.line.VN0018.emotion': 'LOOKS AT THE SIGN',
  'vn.line.VN0018.text': 'Does the club have official status?',
  'vn.line.VN0019.speaker': 'ONOE',
  'vn.line.VN0019.emotion': 'PAUSE',
  'vn.line.VN0019.text': 'The application is almost ready.',
  'vn.line.VN0020.speaker': 'AYUKI',
  'vn.line.VN0020.emotion': 'QUIETLY TO MIKU',
  'vn.line.VN0020.text': 'That is a chemically precise “no”.',
  'vn.line.VN0021.speaker': 'MIKU (THOUGHTS)',
  'vn.line.VN0021.emotion': 'WARY',
  'vn.line.VN0021.text': 'Apparently this club solves mysteries and administrative problems in equal proportions.',
  'vn.line.VN0022.speaker': 'STAGE DIRECTION',
  'vn.line.VN0022.emotion': 'PHONE VIBRATION',
  'vn.line.VN0022.text': 'Ayuki’s phone vibrates on the table. The three of them look at the screen.',
  'vn.history.aria': 'Dialogue history',
  'vn.history.title': 'Dialogue history',
  'vn.history.empty': 'Previously read lines will appear here.',
  'vn.history.close': 'Close',
  'vn.config.aria': 'Reading settings',
  'vn.config.title': 'Reading settings',
  'vn.config.close': 'Close',
  'vn.config.autoSpeed': 'AUTO speed',
  'vn.config.slow': 'Slow',
  'vn.config.normal': 'Normal',
  'vn.config.fast': 'Fast',
  'vn.config.textSize': 'Text size',
  'vn.config.large': 'Large',
  'vn.config.audio': 'Sound & feedback',
  'vn.config.navigation': 'NAVIGATION',
  'vn.config.mainMenu': 'Main Menu',
  'vn.config.saved': 'Current position is saved',
  'vn.config.note': 'AUTO speed and text size apply to the current session. Audio settings persist between launches. System Reduced Motion still takes priority for animations.',
  // ANM-019E1 · Dossier & ending
  'dossier.case': 'CASE 001',
  'dossier.title': 'Dossier',
  'dossier.heading': 'Serial Disappearances',
  'dossier.tab.clues': 'Clues',
  'dossier.tab.theories': 'Theories',
  'dossier.tab.timeline': 'Timeline',
  'dossier.clueNumber': 'CLUE 0{number}',
  'dossier.locked': 'Locked',
  'dossier.unlockHint': 'Win the corresponding investigation to unlock it.',
  'dossier.theoriesHeading': 'Theories Under Review',
  'character.kentaro': 'Kentaro',
  'character.norihiro': 'Norihiro',
  'dossier.kentaro.cleared': 'CLEARED BY TIMECODES',
  'dossier.kentaro.active': 'ACTIVE THEORY',
  'dossier.norihiro.cleared': 'THEORY CLOSED',
  'dossier.norihiro.pending': 'AWAITING VERIFICATION',
  'dossier.reset': 'Reset progress',
  'ending.case': 'CASE 001',
  'ending.chapterComplete': 'Chapter Complete',
  'ending.clueAlt': 'Conductive seam',
  'ending.eyebrow': 'END OF VERTICAL SLICE',
  'ending.heading': 'The first thread is found.',
  'ending.copy': 'The chapter ends at VN0249. The silver-turquoise conductive thread takes the investigation beyond an ordinary theft.',
  'ending.choice': 'Choice',
  'ending.cluesFound': 'Clues found',
  'ending.mainMenu': 'Main Menu',
  'ending.replay': 'Start Over',
  'match3.level.M3_00_LOCKER_TUTORIAL.clueTitle': 'Selective Disappearance',
  'match3.level.M3_00_LOCKER_TUTORIAL.clueSummary': 'Not everything vanished from the laundry batch; price and visibility do not explain the selection.',
  'match3.level.M3_01_PHOTO_PROPS.clueTitle': 'Verifiable Alibi',
  'match3.level.M3_01_PHOTO_PROPS.clueSummary': 'The shoot timecodes confirm Kentaro\'s alibi; the service cart remains the common link.',
  'match3.level.M3_02_POOL_LAUNDRY.clueTitle': 'Mixed Targets',
  'match3.level.M3_02_POOL_LAUNDRY.clueSummary': 'Item type, price, color, and owner do not explain the selection; the items were mixed before they were returned.',
  'match3.level.M3_03_ORDERED_APARTMENT.clueTitle': 'Silver Thread',
  'match3.level.M3_03_ORDERED_APARTMENT.clueSummary': 'Nothing was stolen, but a new conductive seam appeared beneath the service tag.',

} as const satisfies MessageCatalog;
