import type { MessageCatalog } from '../MessageCatalog';

const ru = {
  'match3.reaction.objectiveComplete.0': 'Одна задача закрыта. Не распыляйтесь — добираем улику.',
  'match3.reaction.objectiveComplete.1': 'Эта часть проверки закончена. Теперь только то, что подтверждает время.',
  'match3.reaction.objectiveComplete.2': 'Один этап чист. Дальше не смешивайте порядок партии.',
  'match3.reaction.objectiveComplete.3': 'Секция проверена. Остаток должен сойтись без исключений.',
  'match3.reaction.specialActivated.0': 'Вот так. Быстро, чисто и почти как настоящий план.',
  'match3.reaction.specialActivated.1': 'Эффектно. Только реквизит после этого должен остаться реквизитом.',
  'match3.reaction.specialActivated.2': 'Хороший удар по полю. Теперь используйте открывшийся проход.',
  'match3.reaction.specialActivated.3': 'Сильный ход. Не позволяйте ему разрушить порядок проверки.',
  'match3.reaction.specialCombo.0': 'Ого. Два спецприёма сразу — это уже дедукция с пиротехникой.',
  'match3.reaction.specialCombo.1': 'Такой кадр я бы оставил. Даже без фильтра.',
  'match3.reaction.specialCombo.2': 'Комбинация сработала. Запомните, что именно она открыла.',
  'match3.reaction.specialCombo.3': 'Допустимо. Если результат можно воспроизвести.',
  'match3.reaction.nearWin.0': 'Почти всё. Если квитанция здесь, она уже близко к выходу.',
  'match3.reaction.nearWin.1': 'Осталось совсем немного. Ищем не красивое — проверяемое.',
  'match3.reaction.nearWin.2': 'Картина почти восстановлена. Не потеряйте ключ в последнем шаге.',
  'match3.reaction.nearWin.3': 'Остаток минимальный. Именно сейчас мелочь чаще всего оказывается уликой.',
  'match3.reaction.danger.0': 'Два хода. Либо улика выходит сейчас, либо начинаем поиск заново.',
  'match3.reaction.danger.1': 'Два кадра до конца. Я начинаю понимать драматургию этого расследования.',
  'match3.reaction.danger.2': 'Два хода. Никаких красивых решений — только полезные.',
  'match3.reaction.danger.3': 'Два хода. Порядок больше не прощает импровизацию.',
  'match3.reaction.characterBeat.0': 'Мой шкафчик обычно выглядит менее подозрительно. Обычно.',
  'match3.reaction.characterBeat.1': 'Если найдёте ещё один странный аксессуар — он наверняка был для съёмки.',
  'match3.reaction.characterBeat.2': 'Пена скрывает ошибки хуже, чем людям кажется.',
  'match3.reaction.characterBeat.3': 'Я всё раскладывал по местам. Любое отклонение здесь имеет причину.',
  'match3.reaction.objectiveComplete.4': "Календарь становится чище. Оставляем только подтверждённые строки.",
  'match3.reaction.objectiveComplete.5': "Один блок сверки закрыт. Теперь ищем повторяющуюся сервисную деталь.",
  'match3.reaction.objectiveComplete.6': "Часть мастерской проверена. Осталось доказать, чего машина физически не могла сделать.",
  'match3.reaction.specialActivated.4': "Хорошо. Слухов стало меньше, фактов — заметнее.",
  'match3.reaction.specialActivated.5': "Секция открыта. Теперь сверяйте ярлык, а не впечатление.",
  'match3.reaction.specialActivated.6': "Чистый ход. Используйте его, чтобы разделить заказы и образцы.",
  'match3.reaction.specialCombo.4': "Вот это уже чрезвычайное совещание с полезным спецэффектом.",
  'match3.reaction.specialCombo.5': "Два спецприёма. Шкафчики официально проигрывают расследованию.",
  'match3.reaction.specialCombo.6': "Комбинация принята. Хината хотя бы не выставит нам счёт за сортировку.",
  'match3.reaction.nearWin.4': "Почти готово. Календарь уже показывает общий ритм.",
  'match3.reaction.nearWin.5': "Осталось немного. Журнал ремонта должен выйти в эту проверку.",
  'match3.reaction.nearWin.6': "Почти всё. Нужны карта и катушка — вместе они закрывают вопрос машины.",
  'match3.reaction.danger.4': "Два хода. Убираем версии, которые нельзя подтвердить.",
  'match3.reaction.danger.5': "Два хода. Проверяйте сервисные отметки, не высоту полок.",
  'match3.reaction.danger.6': "Два хода. В мастерской импровизация особенно дорого стоит.",
  'match3.reaction.characterBeat.4': "Я всё ещё считаю «Бельевого призрака» отличным внутренним названием.",
  'match3.reaction.characterBeat.5': "Моя теория роста просит официально не упоминать её в отчёте.",
  'match3.reaction.characterBeat.6': "Если бесплатная примерка считается уликой, расследование стало опасно практичным.",
} as const satisfies MessageCatalog;

const en = {
  'match3.reaction.objectiveComplete.0': 'One task is done. Stay focused — now finish extracting the clue.',
  'match3.reaction.objectiveComplete.1': 'That part of the check is complete. Now keep only what verifies the timeline.',
  'match3.reaction.objectiveComplete.2': 'One stage is clean. Do not mix up the batch order from here.',
  'match3.reaction.objectiveComplete.3': 'That section is verified. The remainder should reconcile without exceptions.',
  'match3.reaction.specialActivated.0': 'That works. Fast, clean, and almost like we planned it.',
  'match3.reaction.specialActivated.1': 'Dramatic. Just make sure the props remain props afterward.',
  'match3.reaction.specialActivated.2': 'Good hit on the board. Use the opening it created.',
  'match3.reaction.specialActivated.3': 'Strong move. Do not let it break the inspection order.',
  'match3.reaction.specialCombo.0': 'Whoa. Two specials at once — deduction with pyrotechnics.',
  'match3.reaction.specialCombo.1': 'That is a shot I would keep. No filter needed.',
  'match3.reaction.specialCombo.2': 'The combination worked. Remember exactly what it exposed.',
  'match3.reaction.specialCombo.3': 'Acceptable. Provided the result can be reproduced.',
  'match3.reaction.nearWin.0': 'Almost there. If the receipt is here, it is close to the exit now.',
  'match3.reaction.nearWin.1': 'Very little left. We are not looking for pretty — we are looking for verifiable.',
  'match3.reaction.nearWin.2': 'The picture is nearly restored. Do not lose the key on the final step.',
  'match3.reaction.nearWin.3': 'Very little remains. This is exactly when a small detail tends to become evidence.',
  'match3.reaction.danger.0': 'Two moves. Either the clue comes out now, or we restart the search.',
  'match3.reaction.danger.1': 'Two frames left. I am beginning to appreciate the drama of this investigation.',
  'match3.reaction.danger.2': 'Two moves. No elegant solutions now — only useful ones.',
  'match3.reaction.danger.3': 'Two moves. Order is no longer forgiving improvisation.',
  'match3.reaction.characterBeat.0': 'My locker usually looks less suspicious than this. Usually.',
  'match3.reaction.characterBeat.1': 'If you find another strange accessory, it was definitely for a shoot.',
  'match3.reaction.characterBeat.2': 'Foam hides mistakes less effectively than people think.',
  'match3.reaction.characterBeat.3': 'I put everything back in place. Any deviation here has a reason.',
  'match3.reaction.objectiveComplete.4': "The calendar is getting cleaner. Keep only confirmed rows.",
  'match3.reaction.objectiveComplete.5': "One verification block is done. Now find the service detail that repeats.",
  'match3.reaction.objectiveComplete.6': "Part of the workshop is verified. Now prove what the machine physically could not do.",
  'match3.reaction.specialActivated.4': "Good. Fewer rumors, clearer facts.",
  'match3.reaction.specialActivated.5': "Section open. Check the tag, not the impression.",
  'match3.reaction.specialActivated.6': "Clean move. Use it to separate orders from samples.",
  'match3.reaction.specialCombo.4': "Now that is an emergency meeting with a useful special effect.",
  'match3.reaction.specialCombo.5': "Two specials. The lockers are officially losing to the investigation.",
  'match3.reaction.specialCombo.6': "Combination accepted. At least Hinata will not bill us for sorting.",
  'match3.reaction.nearWin.4': "Almost there. The calendar is already showing a common rhythm.",
  'match3.reaction.nearWin.5': "Very little left. The repair log should come out in this check.",
  'match3.reaction.nearWin.6': "Almost everything. We need the card and spool together to settle the machine question.",
  'match3.reaction.danger.4': "Two moves. Remove any theory we cannot verify.",
  'match3.reaction.danger.5': "Two moves. Check the service marks, not shelf height.",
  'match3.reaction.danger.6': "Two moves. Improvisation is especially expensive in a workshop.",
  'match3.reaction.characterBeat.4': "I still think “Seiran Underwear Ghost” is an excellent internal title.",
  'match3.reaction.characterBeat.5': "My height theory formally requests omission from the report.",
  'match3.reaction.characterBeat.6': "If a free fitting counts as evidence, this investigation has become dangerously practical.",
} as const satisfies MessageCatalog;

export const match3ReactionCatalogs = { ru, en } as const;
