import type { MessageCatalog } from '../MessageCatalog';

const ru = {
  'match3.reaction.objectiveComplete.0': 'Одна задача закрыта. Не распыляйтесь — добираем улику.',
  'match3.reaction.objectiveComplete.1': 'Эта часть проверки закончена. Теперь только то, что подтверждает время.',
  'match3.reaction.objectiveComplete.2': 'Один этап чист. Дальше не смешивайте порядок партии.',
  'match3.reaction.objectiveComplete.3': 'Секция проверена. Остаток должен сойтись без исключений.',
  'match3.reaction.specialActivated.0': 'Вот так. Быстро, чисто и почти как настоящий план.',
  'match3.reaction.specialActivated.1': 'Эффектно. Только реквизит после этого должен остаться реквизитом.',
  'match3.reaction.specialActivated.2': 'Хороший удар по полю. Теперь используйте открывшийся проход.',
  'match3.reaction.specialActivated.3': 'Сильный ход. Не позволяйте ему разрушить порядок проверки.',
  'match3.reaction.specialCombo.0': 'Ого. Два спецприёма сразу — это уже дедукция с пиротехникой.',
  'match3.reaction.specialCombo.1': 'Такой кадр я бы оставил. Даже без фильтра.',
  'match3.reaction.specialCombo.2': 'Комбинация сработала. Запомните, что именно она открыла.',
  'match3.reaction.specialCombo.3': 'Допустимо. Если результат можно воспроизвести.',
  'match3.reaction.nearWin.0': 'Почти всё. Если квитанция здесь, она уже близко к выходу.',
  'match3.reaction.nearWin.1': 'Осталось совсем немного. Ищем не красивое — проверяемое.',
  'match3.reaction.nearWin.2': 'Картина почти восстановлена. Не потеряйте ключ в последнем шаге.',
  'match3.reaction.nearWin.3': 'Остаток минимальный. Именно сейчас мелочь чаще всего оказывается уликой.',
  'match3.reaction.danger.0': 'Два хода. Либо улика выходит сейчас, либо начинаем поиск заново.',
  'match3.reaction.danger.1': 'Два кадра до конца. Я начинаю понимать драматургию этого расследования.',
  'match3.reaction.danger.2': 'Два хода. Никаких красивых решений — только полезные.',
  'match3.reaction.danger.3': 'Два хода. Порядок больше не прощает импровизацию.',
  'match3.reaction.characterBeat.0': 'Мой шкафчик обычно выглядит менее подозрительно. Обычно.',
  'match3.reaction.characterBeat.1': 'Если найдёте ещё один странный аксессуар — он наверняка был для съёмки.',
  'match3.reaction.characterBeat.2': 'Пена скрывает ошибки хуже, чем людям кажется.',
  'match3.reaction.characterBeat.3': 'Я всё раскладывал по местам. Любое отклонение здесь имеет причину.',
  'match3.reaction.objectiveComplete.4': "Календарь становится чище. Оставляем только подтверждённые строки.",
  'match3.reaction.objectiveComplete.5': "Один блок сверки закрыт. Теперь ищем повторяющуюся сервисную деталь.",
  'match3.reaction.objectiveComplete.6': "Часть мастерской проверена. Осталось доказать, чего машина физически не могла сделать.",
  'match3.reaction.specialActivated.4': "Хорошо. Слухов стало меньше, фактов — заметнее.",
  'match3.reaction.specialActivated.5': "Секция открыта. Теперь сверяйте ярлык, а не впечатление.",
  'match3.reaction.specialActivated.6': "Чистый ход. Используйте его, чтобы разделить заказы и образцы.",
  'match3.reaction.specialCombo.4': "Вот это уже чрезвычайное совещание с полезным спецэффектом.",
  'match3.reaction.specialCombo.5': "Два спецприёма. Шкафчики официально проигрывают расследованию.",
  'match3.reaction.specialCombo.6': "Комбинация принята. Хината хотя бы не выставит нам счёт за сортировку.",
  'match3.reaction.nearWin.4': "Почти готово. Календарь уже показывает общий ритм.",
  'match3.reaction.nearWin.5': "Осталось немного. Журнал ремонта должен выйти в эту проверку.",
  'match3.reaction.nearWin.6': "Почти всё. Нужны карта и катушка — вместе они закрывают вопрос машины.",
  'match3.reaction.danger.4': "Два хода. Убираем версии, которые нельзя подтвердить.",
  'match3.reaction.danger.5': "Два хода. Проверяйте сервисные отметки, не высоту полок.",
  'match3.reaction.danger.6': "Два хода. В мастерской импровизация особенно дорого стоит.",
  'match3.reaction.characterBeat.4': "Я всё ещё считаю «Бельевого призрака» отличным внутренним названием.",
  'match3.reaction.characterBeat.5': "Моя теория роста просит официально не упоминать её в отчёте.",
  'match3.reaction.characterBeat.6': "Если бесплатная примерка считается уликой, расследование стало опасно практичным.",
  'match3.reaction.objectiveComplete.7': "Техническое совпадение подтверждено. Теперь отдельно проверяем право назначения.",
  'match3.reaction.specialActivated.7': "Чистый лабораторный ход. Смотрите, какую карточку он открыл.",
  'match3.reaction.specialCombo.7': "Два спецприёма. Даже Куросэ выглядит почти впечатлённым.",
  'match3.reaction.nearWin.7': "Почти всё. Осталось вывести спецификацию и сверить реестр.",
  'match3.reaction.danger.7': "Два хода. Совпадение нити ещё не равно доказанному назначению.",
  'match3.reaction.characterBeat.7': "Если код партии существует, он должен существовать и в приёмке. Именно это меня беспокоит.",
  'match3.reaction.objectiveComplete.8': "Один диапазон восстановлен. Проверяйте, где начинается следующий разрыв.",
  'match3.reaction.specialActivated.8': "Хорошо. Открытая секция возвращает номера в правильный порядок.",
  'match3.reaction.specialCombo.8': "Два спецприёма. Восемьдесят семь пакетов внезапно выглядят почти разумно.",
  'match3.reaction.nearWin.8': "Осталось немного. Пропуски уже складываются в целые диапазоны.",
  'match3.reaction.danger.8': "Два хода. Не сортируйте по содержимому — держите последовательность номеров.",
  'match3.reaction.characterBeat.8': "Пакет может быть неловким. Номер — никогда. Поэтому я запоминаю номера.",
  'match3.reaction.objectiveComplete.9': "Часть хозяйственного маршрута закрыта. Теперь сводим время ключа и тележки.",
  'match3.reaction.specialActivated.9': "Проход открыт. И да, носки остаются отдельной системой.",
  'match3.reaction.specialCombo.9': "Комбинация сработала. Форма U официально одобряет этот уровень хаоса.",
  'match3.reaction.nearWin.9': "Почти готово. Ключ и накладная должны встретиться в одном выводе.",
  'match3.reaction.danger.9': "Два хода. Если потеряем цепочку передачи, потеряем ночной маршрут.",
  'match3.reaction.characterBeat.9': "Шесть лет я возвращаю одинокие носки владельцам. Репутацию мне испортит не ваш протокол.",
  'match3.reaction.objectiveComplete.10': "Контрольный блок закрыт. Теперь сравниваем серебристый шов вне бельевой выборки.",
  'match3.reaction.specialActivated.10': "Хорошо. Секция открыта — смотрите на повторяющийся шов, не на владельца.",
  'match3.reaction.specialCombo.10': "Два спецприёма. Карате-клуб переживёт и более агрессивную сортировку.",
  'match3.reaction.nearWin.10': "Почти всё. Напульсник должен подтвердить, что система шире одной категории вещей.",
  'match3.reaction.danger.10': "Два хода. Не смешивайте технический критерий с личной неловкостью.",
  'match3.reaction.characterBeat.10': "Честь клуба не зависит от того, кто первым признает, что напульсник тоже был в сервисном пакете.",
  'match3.reaction.objectiveComplete.11': "Один участок маршрута подтверждён. Не теряйте номер пломбы на следующей передаче.",
  'match3.reaction.specialActivated.11': "Проход открыт. Сверяйте маршрут с манифестом, а не с красивым кадром.",
  'match3.reaction.specialCombo.11': "Две комбинации. Даже контейнер Asterion теперь выглядит менее секретно.",
  'match3.reaction.nearWin.11': "Почти готово. Пломба, карточка маршрута и манифест должны замкнуть цепочку.",
  'match3.reaction.danger.11': "Два хода. Если разорвём передачу, останется только совпадение фотографий.",
  'match3.reaction.characterBeat.11': "Я снимал двор ради света, а не ради контейнеров. Но оригинал, похоже, решил стать уликой.",
  'match3.reaction.objectiveComplete.12': "Часть шума снята. Повторяющийся радиопакет уже виден отдельно.",
  'match3.reaction.specialActivated.12': "Чистый сигнал. Теперь вытаскивайте метку, пока помехи не вернулись.",
  'match3.reaction.specialCombo.12': "Два спецприёма. ПанцуИтеру официально отказано в сверхъестественном статусе.",
  'match3.reaction.nearWin.12': "Почти всё. Осталась активная метка и имя протокола.",
  'match3.reaction.danger.12': "Два хода. Нам нужен сигнал, а не ещё одна легенда из чата.",
  'match3.reaction.characterBeat.12': "Я всё ещё оставляю один процент на демона. Научная добросовестность требует резерва.",
  'match3.reaction.objectiveComplete.13': "Один блок кодов подтверждён. Держите список участников отдельно от версии о Кубо.",
  'match3.reaction.specialActivated.13': "Стойка открыта. Теперь видно, какие ярлыки принадлежат участникам пилота.",
  'match3.reaction.specialCombo.13': "Два спецприёма. Даже броня кэндо уступает таблице.",
  'match3.reaction.nearWin.13': "Почти всё. Закрытый список должен встретиться с подтверждёнными кодами.",
  'match3.reaction.danger.13': "Два хода. Никаких выводов о посреднике без списка.",
  'match3.reaction.characterBeat.13': "Я перемещал мешки по просьбе. Содержимое не было моей зоной решения.",
  'match3.reaction.objectiveComplete.14': "Один ряд заказов восстановлен. Не затрагивайте записи посторонних клиентов.",
  'match3.reaction.specialActivated.14': "Стопка разобрана. Даты и изделия снова читаются вместе.",
  'match3.reaction.specialCombo.14': "Два спецприёма. Мама Кубо наверняка назвала бы это приемлемой сортировкой.",
  'match3.reaction.nearWin.14': "Почти готово. Квитанция и книга должны закрыть хронологию.",
  'match3.reaction.danger.14': "Два хода. Приватность клиентов не является расходным материалом.",
  'match3.reaction.characterBeat.14': "Хорошая книга заказов помнит то, что люди предпочитают забыть.",
  'match3.reaction.objectiveComplete.15': "Часть старого маршрута очищена. Теперь держите пакет и ключ-карту в одной цепочке.",
  'match3.reaction.specialActivated.15': "Проход открыт. Свежая сервисная отметка уже видна.",
  'match3.reaction.specialCombo.15': "Два спецприёма. Кот всё ещё лидирует по драматичности, но мы догоняем.",
  'match3.reaction.nearWin.15': "Почти всё. Действующий проход должен подтвердиться пакетом и картой.",
  'match3.reaction.danger.15': "Два хода. Не потеряйте связь между новым пакетом и старым корпусом.",
  'match3.reaction.characterBeat.15': "Если Рэй ещё раз принесёт улику, нам придётся завести ему карточку источника.",
  "match3.reaction.objectiveComplete.16": "Один блок подтверждён. Теперь держите время активации отдельно от версии о Рине.",
  "match3.reaction.specialActivated.16": "Сигнал чистый. Винсент может читать пакет без догадок.",
  "match3.reaction.specialCombo.16": "Два спецприёма. Розовые ленты наконец работают на расследование.",
  "match3.reaction.nearWin.16": "Почти всё. Сканер и новая активация должны встретиться в одном выводе.",
  "match3.reaction.danger.16": "Два хода. Нам нужен проверяемый сигнал, не удобная версия.",
  "match3.reaction.characterBeat.16": "Сканер ничего не знает о мотивах. Это его лучшая профессиональная черта.",
  "match3.reaction.objectiveComplete.17": "Один архивный ряд закрыт. Контрольные вещи остаются отдельно от целей.",
  "match3.reaction.specialActivated.17": "Пломба открыта. Теперь каталог можно сверить без нарушения последовательности.",
  "match3.reaction.specialCombo.17": "Два спецприёма. Даже самый аккуратный архив уступает хорошей проверке.",
  "match3.reaction.nearWin.17": "Почти готово. Каталог должен совпасть с подтверждёнными кражами целиком.",
  "match3.reaction.danger.17": "Два хода. Не превращайте сохранённые доказательства в оправдание кражи.",
  "match3.reaction.characterBeat.17": "Я записывала всё именно потому, что боялась, что иначе никто не поверит.",
  "match3.reaction.objectiveComplete.18": "Одна ложная версия снята. Теперь разделяем действия Рины и продолжение проекта.",
  "match3.reaction.specialActivated.18": "Чистый разрыв по времени. После отзыва доступа остаётся новая активность.",
  "match3.reaction.specialCombo.18": "Два спецприёма. Временная линия наконец перестала защищать удобную историю.",
  "match3.reaction.nearWin.18": "Почти всё. Осталось связать новую метку с независимым продолжением Second Skin.",
  "match3.reaction.danger.18": "Два хода. Не закрывайте дело на физическом похитителе раньше всей системы.",
  "match3.reaction.characterBeat.18": "То, что Рина хотела остановить проект, не возвращает нам право выбора задним числом.",
  "match3.reaction.objectiveComplete.19": "Один блок возврата закрыт. Приватность владельцев важнее красивого отчёта.",
  "match3.reaction.specialActivated.19": "Ячейка открыта. Код возвращает вещь владельцу, не имя — нам.",
  "match3.reaction.specialCombo.19": "Два спецприёма. Даже формальное закрытие дела может быть аккуратным.",
  "match3.reaction.nearWin.19": "Почти всё. Осталось подтвердить возврат и не превратить его в публичный список.",
  "match3.reaction.danger.19": "Два хода. Не теряем подтверждение возврата ради штампа CASE CLOSED.",
  "match3.reaction.characterBeat.19": "Я готова отвечать за то, что взяла. Но чужие имена вам для этого не нужны.",
  "match3.reaction.objectiveComplete.20": "Один слой логов сохранён. Теперь отделяем согласие на тест от согласия на скрытый сбор.",
  "match3.reaction.specialActivated.20": "Серверный шлюз открыт. Копируем данные до того, как кто-то решит их упростить.",
  "match3.reaction.specialCombo.20": "Два спецприёма. Наконец-то эффектная комбинация с юридически полезным результатом.",
  "match3.reaction.nearWin.20": "Почти всё. Резервная копия должна пережить и сервер, и чью-то карьеру.",
  "match3.reaction.danger.20": "Два хода. Без независимой копии у нас останется только слово против слова.",
  "match3.reaction.characterBeat.20": "Проект можно спасти, если правильно назвать виновного. Вопрос лишь в том, кого вы хотите назвать.",
  "match3.reaction.objectiveComplete.21": "Одно противоречие убрано. Презентация стала чище, а дело — хуже.",
  "match3.reaction.specialActivated.21": "Слайд очищен. Теперь неудобный факт почти не мешает красивой версии.",
  "match3.reaction.specialCombo.21": "Два спецприёма. Вот так и рождается презентация, которую любят начальники.",
  "match3.reaction.nearWin.21": "Почти готово. Осталось решить, сколько правды помещается на финальный слайд.",
  "match3.reaction.danger.21": "Два хода. Даже ложная версия должна быть внутренне непротиворечивой.",
  "match3.reaction.characterBeat.21": "Если вычеркнуть достаточно стрелочек, любая схема начинает выглядеть убедительно.",
} as const satisfies MessageCatalog;

const en = {
  'match3.reaction.objectiveComplete.0': 'One task is done. Stay focused — now finish extracting the clue.',
  'match3.reaction.objectiveComplete.1': 'That part of the check is complete. Now keep only what verifies the timeline.',
  'match3.reaction.objectiveComplete.2': 'One stage is clean. Do not mix up the batch order from here.',
  'match3.reaction.objectiveComplete.3': 'That section is verified. The remainder should reconcile without exceptions.',
  'match3.reaction.specialActivated.0': 'That works. Fast, clean, and almost like we planned it.',
  'match3.reaction.specialActivated.1': 'Dramatic. Just make sure the props remain props afterward.',
  'match3.reaction.specialActivated.2': 'Good hit on the board. Use the opening it created.',
  'match3.reaction.specialActivated.3': 'Strong move. Do not let it break the inspection order.',
  'match3.reaction.specialCombo.0': 'Whoa. Two specials at once — deduction with pyrotechnics.',
  'match3.reaction.specialCombo.1': 'That is a shot I would keep. No filter needed.',
  'match3.reaction.specialCombo.2': 'The combination worked. Remember exactly what it exposed.',
  'match3.reaction.specialCombo.3': 'Acceptable. Provided the result can be reproduced.',
  'match3.reaction.nearWin.0': 'Almost there. If the receipt is here, it is close to the exit now.',
  'match3.reaction.nearWin.1': 'Very little left. We are not looking for pretty — we are looking for verifiable.',
  'match3.reaction.nearWin.2': 'The picture is nearly restored. Do not lose the key on the final step.',
  'match3.reaction.nearWin.3': 'Very little remains. This is exactly when a small detail tends to become evidence.',
  'match3.reaction.danger.0': 'Two moves. Either the clue comes out now, or we restart the search.',
  'match3.reaction.danger.1': 'Two frames left. I am beginning to appreciate the drama of this investigation.',
  'match3.reaction.danger.2': 'Two moves. No elegant solutions now — only useful ones.',
  'match3.reaction.danger.3': 'Two moves. Order is no longer forgiving improvisation.',
  'match3.reaction.characterBeat.0': 'My locker usually looks less suspicious than this. Usually.',
  'match3.reaction.characterBeat.1': 'If you find another strange accessory, it was definitely for a shoot.',
  'match3.reaction.characterBeat.2': 'Foam hides mistakes less effectively than people think.',
  'match3.reaction.characterBeat.3': 'I put everything back in place. Any deviation here has a reason.',
  'match3.reaction.objectiveComplete.4': "The calendar is getting cleaner. Keep only confirmed rows.",
  'match3.reaction.objectiveComplete.5': "One verification block is done. Now find the service detail that repeats.",
  'match3.reaction.objectiveComplete.6': "Part of the workshop is verified. Now prove what the machine physically could not do.",
  'match3.reaction.specialActivated.4': "Good. Fewer rumors, clearer facts.",
  'match3.reaction.specialActivated.5': "Section open. Check the tag, not the impression.",
  'match3.reaction.specialActivated.6': "Clean move. Use it to separate orders from samples.",
  'match3.reaction.specialCombo.4': "Now that is an emergency meeting with a useful special effect.",
  'match3.reaction.specialCombo.5': "Two specials. The lockers are officially losing to the investigation.",
  'match3.reaction.specialCombo.6': "Combination accepted. At least Hinata will not bill us for sorting.",
  'match3.reaction.nearWin.4': "Almost there. The calendar is already showing a common rhythm.",
  'match3.reaction.nearWin.5': "Very little left. The repair log should come out in this check.",
  'match3.reaction.nearWin.6': "Almost everything. We need the card and spool together to settle the machine question.",
  'match3.reaction.danger.4': "Two moves. Remove any theory we cannot verify.",
  'match3.reaction.danger.5': "Two moves. Check the service marks, not shelf height.",
  'match3.reaction.danger.6': "Two moves. Improvisation is especially expensive in a workshop.",
  'match3.reaction.characterBeat.4': "I still think “Seiran Underwear Ghost” is an excellent internal title.",
  'match3.reaction.characterBeat.5': "My height theory formally requests omission from the report.",
  'match3.reaction.characterBeat.6': "If a free fitting counts as evidence, this investigation has become dangerously practical.",
  'match3.reaction.objectiveComplete.7': "The technical match is confirmed. Now verify authorization separately.",
  'match3.reaction.specialActivated.7': "Clean laboratory move. Watch which card it exposed.",
  'match3.reaction.specialCombo.7': "Two specials. Even Kurose looks almost impressed.",
  'match3.reaction.nearWin.7': "Almost done. Bring out the specification and reconcile it with the registry.",
  'match3.reaction.danger.7': "Two moves. A thread match is not the same as an authorized assignment.",
  'match3.reaction.characterBeat.7': "If the batch code exists, it should exist in receiving records. That is what bothers me.",
  'match3.reaction.objectiveComplete.8': "One range is restored. Find where the next break begins.",
  'match3.reaction.specialActivated.8': "Good. The opened section puts numbers back into sequence.",
  'match3.reaction.specialCombo.8': "Two specials. Eighty-seven packages suddenly look almost reasonable.",
  'match3.reaction.nearWin.8': "Very little left. The gaps are already forming whole ranges.",
  'match3.reaction.danger.8': "Two moves. Do not sort by contents — preserve the number sequence.",
  'match3.reaction.characterBeat.8': "A package can be embarrassing. A number never is. That is why I remember numbers.",
  'match3.reaction.objectiveComplete.9': "Part of the maintenance route is settled. Now align the key and cart timeline.",
  'match3.reaction.specialActivated.9': "Passage open. And yes, socks remain a separate system.",
  'match3.reaction.specialCombo.9': "Combination worked. Form U officially approves this level of chaos.",
  'match3.reaction.nearWin.9': "Almost there. The key and slip need to meet in one conclusion.",
  'match3.reaction.danger.9': "Two moves. Lose the handoff chain and we lose the night route.",
  'match3.reaction.characterBeat.9': "I have returned lone socks to their owners for six years. Your report is not what will ruin my reputation.",
  'match3.reaction.objectiveComplete.10': "The control block is closed. Now compare the silver stitch outside the underwear sample.",
  'match3.reaction.specialActivated.10': "Good. Section open — follow the repeating stitch, not the owner.",
  'match3.reaction.specialCombo.10': "Two specials. The karate club will survive a more aggressive sort.",
  'match3.reaction.nearWin.10': "Almost there. The wristband should prove the system reaches beyond one item category.",
  'match3.reaction.danger.10': "Two moves. Do not mix the technical criterion with personal embarrassment.",
  'match3.reaction.characterBeat.10': "The honor of the club does not depend on who first admits the wristband was in a service bag too.",
  'match3.reaction.objectiveComplete.11': "One route segment is confirmed. Do not lose the seal number at the next handoff.",
  'match3.reaction.specialActivated.11': "Passage open. Match the route to the manifest, not to the prettiest photograph.",
  'match3.reaction.specialCombo.11': "Two specials. Even an Asterion container looks less secret now.",
  'match3.reaction.nearWin.11': "Almost done. Seal, route card, and manifest must close the chain.",
  'match3.reaction.danger.11': "Two moves. Break the handoff and all we have left is a photo coincidence.",
  'match3.reaction.characterBeat.11': "I photographed the yard for the light, not the containers. The original seems to have chosen evidence anyway.",
  'match3.reaction.objectiveComplete.12': "Part of the noise is gone. The repeating radio packet is visible on its own.",
  'match3.reaction.specialActivated.12': "Clean signal. Bring the tag out before the interference returns.",
  'match3.reaction.specialCombo.12': "Two specials. The Panty Eater is officially denied supernatural status.",
  'match3.reaction.nearWin.12': "Almost everything. We still need the active tag and the protocol name.",
  'match3.reaction.danger.12': "Two moves. We need the signal, not another chat legend.",
  'match3.reaction.characterBeat.12': "I am still reserving one percent for a demon. Scientific integrity demands a margin.",
  'match3.reaction.objectiveComplete.13': "One code block is confirmed. Keep the participant list separate from the theory about Kubo.",
  'match3.reaction.specialActivated.13': "Rack open. Now we can see which tags belong to pilot participants.",
  'match3.reaction.specialCombo.13': "Two specials. Even kendo armor eventually loses to a table.",
  'match3.reaction.nearWin.13': "Almost done. The closed list must meet the confirmed codes.",
  'match3.reaction.danger.13': "Two moves. No conclusions about an intermediary without the list.",
  'match3.reaction.characterBeat.13': "I moved the bags because I was asked. Their contents were not my decision to make.",
  'match3.reaction.objectiveComplete.14': "One order row is restored. Leave unrelated client records out of it.",
  'match3.reaction.specialActivated.14': "Stack cleared. Dates and garments are readable together again.",
  'match3.reaction.specialCombo.14': "Two specials. Kubo's mother would probably call this acceptable sorting.",
  'match3.reaction.nearWin.14': "Almost done. The receipt and ledger should close the chronology.",
  'match3.reaction.danger.14': "Two moves. Client privacy is not expendable evidence.",
  'match3.reaction.characterBeat.14': "A good order book remembers what people would rather forget.",
  'match3.reaction.objectiveComplete.15': "Part of the old route is clear. Keep the package and keycard in the same chain.",
  'match3.reaction.specialActivated.15': "Passage open. A fresh service mark is already visible.",
  'match3.reaction.specialCombo.15': "Two specials. The cat still leads on drama, but we are catching up.",
  'match3.reaction.nearWin.15': "Almost there. The active passage must be confirmed by the package and card.",
  'match3.reaction.danger.15': "Two moves. Do not lose the link between the new package and the old building.",
  'match3.reaction.characterBeat.15': "If Ray brings us one more clue, we will need to issue him a source card.",
  "match3.reaction.objectiveComplete.16": "One block is confirmed. Keep activation time separate from the theory about Rina.",
  "match3.reaction.specialActivated.16": "Clean signal. Vincent can read the packet without guessing.",
  "match3.reaction.specialCombo.16": "Two specials. The pink ribbons are finally working for the investigation.",
  "match3.reaction.nearWin.16": "Almost done. The scanner and the new activation must meet in one conclusion.",
  "match3.reaction.danger.16": "Two moves. We need a verifiable signal, not a convenient theory.",
  "match3.reaction.characterBeat.16": "The scanner knows nothing about motives. That is its best professional trait.",
  "match3.reaction.objectiveComplete.17": "One archive row is closed. Control items stay separate from targets.",
  "match3.reaction.specialActivated.17": "Seal open. The catalog can now be checked without breaking sequence.",
  "match3.reaction.specialCombo.17": "Two specials. Even the neatest archive loses to a proper audit.",
  "match3.reaction.nearWin.17": "Almost done. The catalog must match the confirmed thefts completely.",
  "match3.reaction.danger.17": "Two moves. Do not turn preserved evidence into an excuse for theft.",
  "match3.reaction.characterBeat.17": "I recorded everything because I was afraid nobody would believe me otherwise.",
  "match3.reaction.objectiveComplete.18": "One false theory is gone. Now separate Rina's actions from the project's continuation.",
  "match3.reaction.specialActivated.18": "Clean break in the timeline. New activity remains after access was revoked.",
  "match3.reaction.specialCombo.18": "Two specials. The timeline has finally stopped protecting the convenient story.",
  "match3.reaction.nearWin.18": "Almost done. Link the new tag to the independent continuation of Second Skin.",
  "match3.reaction.danger.18": "Two moves. Do not close the case on the physical thief before the whole system.",
  "match3.reaction.characterBeat.18": "Rina trying to stop the project does not give us our right to choose back.",
  "match3.reaction.objectiveComplete.19": "One return block is complete. Owner privacy matters more than a clean report.",
  "match3.reaction.specialActivated.19": "Locker open. The code returns the item to its owner without returning the name to us.",
  "match3.reaction.specialCombo.19": "Two specials. Even a formal case closure can be handled carefully.",
  "match3.reaction.nearWin.19": "Almost done. Confirm the return without turning it into a public list.",
  "match3.reaction.danger.19": "Two moves. Do not lose the return confirmation for the sake of a CASE CLOSED stamp.",
  "match3.reaction.characterBeat.19": "I will answer for what I took. You do not need other people's names to make me do that.",
  "match3.reaction.objectiveComplete.20": "One log layer is preserved. Now separate consent to a test from consent to hidden collection.",
  "match3.reaction.specialActivated.20": "Server gate open. Copy the data before somebody decides to simplify it.",
  "match3.reaction.specialCombo.20": "Two specials. Finally, a dramatic combination with legally useful output.",
  "match3.reaction.nearWin.20": "Almost done. The backup needs to survive both the server and somebody's career.",
  "match3.reaction.danger.20": "Two moves. Without an independent copy, this becomes one person's word against another's.",
  "match3.reaction.characterBeat.20": "The project can be saved if the culprit is named correctly. The question is whom you want to name.",
  "match3.reaction.objectiveComplete.21": "One contradiction is removed. The presentation is cleaner and the case is worse.",
  "match3.reaction.specialActivated.21": "Slide cleaned. The inconvenient fact barely interferes with the neat version now.",
  "match3.reaction.specialCombo.21": "Two specials. This is how a presentation management loves gets made.",
  "match3.reaction.nearWin.21": "Almost ready. Decide how much truth fits on the final slide.",
  "match3.reaction.danger.21": "Two moves. Even a false version has to be internally consistent.",
  "match3.reaction.characterBeat.21": "Remove enough arrows and any diagram starts to look convincing.",
} as const satisfies MessageCatalog;

export const match3ReactionCatalogs = { ru, en } as const;
