import type { MessageCatalog } from '../MessageCatalog';

export const ruCatalog = {
  'localization.language.ru': 'Русский',
  'localization.language.en': 'English',
  'localization.language.label': 'Язык',
  'localization.language.help': 'Язык интерфейса сохраняется на этом устройстве отдельно от игрового прогресса.',

  'common.back': 'Назад',
  'common.navigation': 'Навигация',
  'common.settings': 'Настройки',
  'common.on': 'ON',
  'common.off': 'OFF',
  'common.enabled': 'Включено',
  'common.disabled': 'Выключено',
  'common.available': 'доступен',
  'common.unavailable': 'недоступен',

  'menu.eyebrow': 'SEIRAN COLLEGE · CASE 001',
  'menu.title': 'Детективы',
  'menu.titleAccent': 'класса U',
  'menu.tagline': 'Комедийная visual novel × match‑3',
  'menu.heroAria': 'Мику, Оноэ и Аюки',
  'menu.newGame': 'Новая игра',
  'menu.continue': 'Продолжить',
  'menu.settings': 'Настройки',
  'menu.sceneNavigation': 'Навигация по сценам',
  'menu.saveDiagnostics': 'Сохранения и диагностика',
  'menu.scriptLines': '{count} строк сценария',

  'settings.eyebrow': 'CONFIG · SYSTEM',
  'settings.title': 'Настройки',
  'settings.audioHeading': 'Звук и отклик',
  'settings.audioCopy': 'Музыка и SFX генерируются локально через Web Audio и не требуют загрузки аудиофайлов. Настройки сохраняются отдельно от игрового прогресса.',
  'settings.languageHeading': 'Язык',
  'settings.installHeading': 'Установка и офлайн',
  'settings.mobileContractTitle': 'Мобильный контракт',
  'settings.mobileContractCopy': 'Звук активируется только после первого касания/клавиши. При сворачивании вкладки музыка приостанавливается и безопасно возобновляется при возвращении.',
  'settings.navigationLabel': 'НАВИГАЦИЯ',
  'settings.mainMenu': 'Главное меню',
  'settings.mainMenuMatchWarning': 'Текущая попытка потребует подтверждения',
  'settings.mainMenuSafe': 'Сохранённый прогресс не потеряется',

  'audio.music': 'Музыка',
  'audio.effects': 'Эффекты',
  'audio.musicVolumeAria': 'Громкость музыки',
  'audio.effectsVolumeAria': 'Громкость эффектов',
  'audio.mute': 'Без звука',
  'audio.haptics': 'Haptics',
  'audio.hapticsSupported': 'Поддерживается устройством',
  'audio.hapticsUnavailable': 'Недоступно в этом браузере',
  'audio.previewMusic': '▶ Проверить музыку',
  'audio.previewEffects': '✦ Проверить SFX',
  'audio.webAudio': 'Web Audio',
  'audio.hapticsCapability': 'Haptics',
  'audio.hapticsAvailable': 'доступны',
  'audio.hapticsFallback': 'fallback без вибрации',

  'pwa.install.installed': 'Установлено',
  'pwa.install.available': 'Можно установить',
  'pwa.install.browserMenu': 'Через меню браузера',
  'pwa.online': 'online',
  'pwa.offline': 'offline',
  'pwa.cacheFailures': '{count} ошибок cache',
  'pwa.installAction': 'Установить',
  'pwa.checkUpdate': 'Проверить обновление',

  'vn.chrome.openDossier': 'Открыть досье',
  'vn.chrome.navigation': 'Навигация visual novel',
  'vn.chrome.history': 'История диалога',
  'vn.chrome.direction': 'ПОСТАНОВКА',
  'vn.chrome.controls': 'Управление visual novel',
  'vn.chrome.dossierUpdated': 'ДОСЬЕ ОБНОВЛЕНО',
  'vn.status.saved': 'Ручной слот сохранён',
  'vn.status.saveFailed': 'Не удалось сохранить ручной слот',
  'vn.status.emptySlot': 'Ручной слот пока пуст',
  'vn.status.skipReadOnly': 'SKIP доступен только для уже прочитанных реплик',

  'vn.choice.header': 'Выбор версии',
  'vn.choice.prompt': 'С чего начать?',
  'vn.choice.A.title': 'Сначала найдём вторую пострадавшую',
  'vn.choice.A.effect': 'Доверие источников +1',
  'vn.choice.B.title': 'Предупредим анонимно',
  'vn.choice.B.effect': 'Сила слухов +1',
  'vn.choice.C.title': 'Передадим дело администрации',
  'vn.choice.C.effect': 'Доверие Оноэ +1',

  'vn.scene.VN_SCENE_00_PROLOGUE.title': 'Клуб, которого почти нет',
  'vn.scene.VN_SCENE_00_PROLOGUE.location': 'Комната детективного клуба',
  'vn.scene.VN_SCENE_01_E0_PRE.title': 'Дело класса U',
  'vn.scene.VN_SCENE_01_E0_PRE.location': 'Комната клуба → раздевалка',
  'vn.scene.VN_SCENE_02_E0_POST.title': 'То, что вор оставил',
  'vn.scene.VN_SCENE_02_E0_POST.location': 'Раздевалка лёгкой атлетики',
  'vn.scene.VN_SCENE_03_E1_PRE.title': 'Комната, которая всё объясняет слишком плохо',
  'vn.scene.VN_SCENE_03_E1_PRE.location': 'Квартира Кэнтаро',
  'vn.scene.VN_SCENE_04_E1_POST.title': 'Манекен с лучшим алиби',
  'vn.scene.VN_SCENE_04_E1_POST.location': 'Квартира Кэнтаро',
  'vn.scene.VN_SCENE_05_E2_PRE.title': 'Мокрые показания',
  'vn.scene.VN_SCENE_05_E2_PRE.location': 'Раздевалка клуба плавания',
  'vn.scene.VN_SCENE_06_E2_POST.title': 'Таблица без вкуса',
  'vn.scene.VN_SCENE_06_E2_POST.location': 'Раздевалка клуба плавания',
  'vn.scene.VN_SCENE_07_E3_PRE.title': 'Розовое признание',
  'vn.scene.VN_SCENE_07_E3_PRE.location': 'Квартира Норихиро',
  'vn.scene.VN_SCENE_08_E3_POST.title': 'Это не ткань',
  'vn.scene.VN_SCENE_08_E3_POST.location': 'Квартира Норихиро',

  'vn.line.VN0001.speaker': 'РЕЖИССУРА',
  'vn.line.VN0001.emotion': 'FADE IN',
  'vn.line.VN0001.text': 'После звонка. Узкая комната бывшей кладовой; доска, два стула, складной стол и табличка «Детективный клуб», приклеенная поверх слова «Инвентарь».',
  'vn.line.VN0002.speaker': 'МИКУ (МЫСЛИ)',
  'vn.line.VN0002.emotion': 'ОСТОРОЖНАЯ',
  'vn.line.VN0002.text': 'В буклете это называлось «пространством для студенческих инициатив».',
  'vn.line.VN0003.speaker': 'МИКУ (МЫСЛИ)',
  'vn.line.VN0003.emotion': 'СУХО',
  'vn.line.VN0003.text': 'В буклете не было швабры за занавеской.',
  'vn.line.VN0004.speaker': 'ОНОЭ',
  'vn.line.VN0004.emotion': 'СОСРЕДОТОЧЕННАЯ',
  'vn.line.VN0004.text': 'Пункт четвёртый: клуб обязуется не проводить допросы без согласия участника.',
  'vn.line.VN0005.speaker': 'АЮКИ',
  'vn.line.VN0005.emotion': 'ВЕСЁЛАЯ',
  'vn.line.VN0005.text': 'Слишком негативно. Напиши: «Мы уважаем право подозреваемого на эффектное появление».',
  'vn.line.VN0006.speaker': 'ОНОЭ',
  'vn.line.VN0006.emotion': 'НЕ ПОДНИМАЯ ГЛАЗ',
  'vn.line.VN0006.text': 'Это не право.',
  'vn.line.VN0007.speaker': 'АЮКИ',
  'vn.line.VN0007.emotion': 'ЗАДУМЧИВАЯ',
  'vn.line.VN0007.text': 'Пока не право.',
  'vn.line.VN0008.speaker': 'МИКУ',
  'vn.line.VN0008.emotion': 'НЕУВЕРЕННАЯ',
  'vn.line.VN0008.text': 'Простите… это собрание детективного клуба?',
  'vn.line.VN0009.speaker': 'АЮКИ',
  'vn.line.VN0009.emotion': 'ПОВОРОТ К МИКУ',
  'vn.line.VN0009.text': 'Зависит. Ты клиент, свидетель или долгожданный третий участник?',
  'vn.line.VN0010.speaker': 'МИКУ',
  'vn.line.VN0010.emotion': 'СМУЩЁННАЯ',
  'vn.line.VN0010.text': 'Я думала сначала посмотреть.',
  'vn.line.VN0011.speaker': 'ОНОЭ',
  'vn.line.VN0011.emotion': 'ОЦЕНИВАЮЩАЯ',
  'vn.line.VN0011.text': 'Наблюдение — допустимая специализация.',
  'vn.line.VN0012.speaker': 'АЮКИ',
  'vn.line.VN0012.emotion': 'ТЕАТРАЛЬНАЯ',
  'vn.line.VN0012.text': 'Принята единогласно.',
  'vn.line.VN0013.speaker': 'МИКУ',
  'vn.line.VN0013.emotion': 'УДИВЛЁННАЯ',
  'vn.line.VN0013.text': 'Вы ещё не голосовали.',
  'vn.line.VN0014.speaker': 'ОНОЭ',
  'vn.line.VN0014.emotion': 'НЕЙТРАЛЬНАЯ',
  'vn.line.VN0014.text': 'Нас двое. Единогласие возникает быстро.',
  'vn.line.VN0015.speaker': 'МИКУ (МЫСЛИ)',
  'vn.line.VN0015.emotion': 'ИРОНИЧНАЯ',
  'vn.line.VN0015.text': 'Я пришла рисовать афишу. Через сорок секунд получила должность.',
  'vn.line.VN0016.speaker': 'АЮКИ',
  'vn.line.VN0016.emotion': 'С ЛИСТОМ',
  'vn.line.VN0016.text': 'Осталось выбрать название: «Око Сэйрана», «Три алиби» или «Красотки дедукции».',
  'vn.line.VN0017.speaker': 'ОНОЭ',
  'vn.line.VN0017.emotion': 'ХОЛОДНО',
  'vn.line.VN0017.text': 'Последнее название снижает нашу доказательную ценность.',
  'vn.line.VN0018.speaker': 'МИКУ',
  'vn.line.VN0018.emotion': 'РАССМАТРИВАЕТ ТАБЛИЧКУ',
  'vn.line.VN0018.text': 'А официальный статус у клуба есть?',
  'vn.line.VN0019.speaker': 'ОНОЭ',
  'vn.line.VN0019.emotion': 'ПАУЗА',
  'vn.line.VN0019.text': 'Заявление почти готово.',
  'vn.line.VN0020.speaker': 'АЮКИ',
  'vn.line.VN0020.emotion': 'ТИХО К МИКУ',
  'vn.line.VN0020.text': 'Это химически точное «нет».',
  'vn.line.VN0021.speaker': 'РЕЖИССУРА',
  'vn.line.VN0021.emotion': 'SFX: ТРИ БЫСТРЫХ СТУКА',
  'vn.line.VN0021.text': 'Дверь открывается раньше, чем Оноэ отвечает.',
  'vn.line.VN0022.speaker': 'ЭМИ',
  'vn.line.VN0022.emotion': 'ВСТРЕВОЖЕННАЯ',
  'vn.line.VN0022.text': 'Мне сказали, вы находите вещи, которые администрация предпочитает не замечать.',
  'vn.history.aria': 'История диалога',
  'vn.history.title': 'История диалога',
  'vn.history.empty': 'Здесь появятся уже прочитанные реплики.',
  'vn.history.close': 'Закрыть',
  'vn.config.aria': 'Настройки чтения',
  'vn.config.title': 'Настройки чтения',
  'vn.config.close': 'Закрыть',
  'vn.config.autoSpeed': 'Скорость AUTO',
  'vn.config.slow': 'Медленно',
  'vn.config.normal': 'Обычно',
  'vn.config.fast': 'Быстро',
  'vn.config.textSize': 'Размер текста',
  'vn.config.large': 'Крупный',
  'vn.config.audio': 'Звук и отклик',
  'vn.config.navigation': 'НАВИГАЦИЯ',
  'vn.config.mainMenu': 'Главное меню',
  'vn.config.saved': 'Текущая позиция сохранена',
  'vn.config.note': 'Скорость AUTO и размер текста действуют в текущей сессии. Audio-настройки сохраняются между запусками. Системный Reduced Motion по-прежнему имеет приоритет для анимаций.',
  // ANM-019E1 · Dossier & ending
  'dossier.case': 'ДЕЛО 001',
  'dossier.title': 'Досье',
  'dossier.heading': 'Серийные пропажи',
  'dossier.tab.clues': 'Улики',
  'dossier.tab.theories': 'Версии',
  'dossier.tab.timeline': 'Хронология',
  'dossier.clueNumber': 'УЛИКА 0{number}',
  'dossier.locked': 'Не открыта',
  'dossier.unlockHint': 'Победите в соответствующем расследовании.',
  'dossier.theoriesHeading': 'Проверяемые версии',
  'character.kentaro': 'Кэнтаро',
  'character.norihiro': 'Норихиро',
  'dossier.kentaro.cleared': 'ОПРАВДАН ТАЙМКОДАМИ',
  'dossier.kentaro.active': 'АКТИВНАЯ ВЕРСИЯ',
  'dossier.norihiro.cleared': 'ВЕРСИЯ ЗАКРЫТА',
  'dossier.norihiro.pending': 'ОЖИДАЕТ ПРОВЕРКИ',
  'dossier.reset': 'Сбросить прогресс',
  'ending.case': 'CASE 001',
  'ending.chapterComplete': 'Глава завершена',
  'ending.clueAlt': 'Проводящий шов',
  'ending.eyebrow': 'КОНЕЦ ВЕРТИКАЛЬНОГО СРЕЗА',
  'ending.heading': 'Первая нить найдена.',
  'ending.copy': 'Глава завершена на VN0249. Серебристо-бирюзовая проводящая нить выводит расследование за пределы бытовой кражи.',
  'ending.choice': 'Выбор',
  'ending.cluesFound': 'Найдено улик',
  'ending.mainMenu': 'В главное меню',
  'ending.replay': 'Начать заново',
  'match3.level.M3_00_LOCKER_TUTORIAL.clueTitle': 'Выборочная пропажа',
  'match3.level.M3_00_LOCKER_TUTORIAL.clueSummary': 'Из партии прачечной исчезли не все вещи; цена и заметность не объясняют выбор.',
  'match3.level.M3_01_PHOTO_PROPS.clueTitle': 'Проверяемое алиби',
  'match3.level.M3_01_PHOTO_PROPS.clueSummary': 'Таймкоды съёмки подтверждают алиби Кэнтаро; сервисная тележка остаётся общей связью.',
  'match3.level.M3_02_POOL_LAUNDRY.clueTitle': 'Смешанные цели',
  'match3.level.M3_02_POOL_LAUNDRY.clueSummary': 'Тип, цена, цвет и владелец вещей не объясняют выбор; вещи смешали до возврата.',
  'match3.level.M3_03_ORDERED_APARTMENT.clueTitle': 'Серебристая нить',
  'match3.level.M3_03_ORDERED_APARTMENT.clueSummary': 'Ничего не украли, но под сервисной биркой появился новый проводящий шов.',

  // ANM-019E2 · Match-3
  'character.miku': 'Мику',
  'character.onoe': 'Оноэ',
  'character.ayuki': 'Аюки',
  'character.emi': 'Эми',
  'match3.investigation': 'РАССЛЕДОВАНИЕ {current}/{total}',
  'match3.investigationNavigation': 'Навигация расследования',
  'match3.moves': 'ходов',
  'match3.start': 'Начать поиск',
  'match3.emptyCell': 'Пустая клетка',
  'match3.backToInvestigation': 'Назад к расследованию',
  'match3.objectivesAria': 'Цели расследования',
  'match3.objective': 'ЦЕЛЬ',
  'match3.movesStageAria': 'Ходы и этап',
  'match3.movesUpper': 'ХОДЫ',
  'match3.stage': 'ЭТАП {current}/{total}',
  'match3.boardAria': 'Поле 8 на 8',
  'match3.teamAria': 'Команда расследования',
  'match3.hint': 'ПОДСКАЗКА',
  'match3.bestMove': 'Лучший ход',
  'match3.inputHint': 'Перетащите фишку, свайпните или выберите две соседние · подсказка учитывает цели.',
  'match3.evidenceFound': 'УЛИКА НАЙДЕНА',
  'match3.continueStory': 'Продолжить сцену',
  'match3.result': 'Результат',
  'match3.lossHeading': 'Версия требует повторной проверки',
  'match3.retry': 'Повторить уровень',
  'match3.feedback.special': 'НАБЛЮДЕНИЕ!',
  'match3.feedback.chain': 'ЦЕПОЧКА ×{count}',
  'match3.feedback.match': 'СОВПАДЕНИЕ',
  'match3.feedback.reshuffled': 'ПОЛЕ ПЕРЕМЕШАНО',
  'match3.feedback.noMatch': 'НЕТ СОВПАДЕНИЯ',
  'match3.feedback.swapUnavailable': 'ОБМЕН НЕДОСТУПЕН',
  'match3.feedback.clueCollected': 'УЛИКА СОБРАНА',
  'match3.feedback.outOfMoves': 'ХОДЫ ЗАКОНЧИЛИСЬ',
  'match3.bark.noHint': 'Поле не даёт корректного обмена. Нужна перестановка.',
  'match3.bark.hintFound': 'Этот обмен лучше всего продвигает текущие цели расследования.',
  'match3.bark.edge': 'За краем поля обмена нет. Попробуем соседнюю клетку.',
  'match3.bark.ingredientInvalid': 'Сюжетный объект нужно опустить вниз совпадениями под ним.',
  'match3.bark.blockedInvalid': 'Эта секция заперта. Сначала соберём совпадение рядом.',
  'match3.bark.noMatchInvalid': 'Этот обмен не образует ряд. Проверим соседние категории.',
  'match3.bark.special': 'Если посмотреть на всё сразу, беспорядок превращается в узор.',
  'match3.bark.fiveMoves.0': 'Ещё немного. Нам нужна связь с прачечной.',
  'match3.bark.fiveMoves.1': 'Если вы её снова потеряете, это будет уже коллективное алиби.',
  'match3.bark.fiveMoves.2': 'Нужен шкаф. Там журнал возврата.',
  'match3.bark.fiveMoves.3': 'Нужны оба объекта. Без чека версия не закрыта.',
  'match3.bark.blockers.0': 'Улика U-1 освобождена. Нет, я не дала ей имя.',
  'match3.bark.blockers.1': 'Упаковка плотная. Один удар откроет, второй освободит содержимое.',
  'match3.bark.blockers.2': 'Под пеной вещи из разных секций. Их смешали ещё до шкафчиков.',
  'match3.bark.blockers.3': 'Ни тайника, ни сообщницы. У этой квартиры нет чувства драмы.',
  'match3.bark.ingredient.0': 'Документ в верхней секции. Освободи путь к нижнему краю.',
  'match3.bark.ingredient.1': 'Маленькая чёрная карта, огромный шанс на драму.',
  'match3.bark.ingredient.2': 'Ключ всплыл. Метафорически. Буквально он движется вниз.',
  'match3.bark.ingredient.3': 'Ищем оба документа: чек и полотенце с изменённым краем.',
  'match3.bark.cascade': 'Цепочка наблюдений: {count}. Это уже почти дедукция.',
  'match3.tile.camisole': 'Ткань',
  'match3.tile.laundryTag': 'Бирка',
  'match3.tile.panties': 'Комплект',
  'match3.tile.towel': 'Полотенце',
  'match3.tile.socks': 'Пара',
  'match3.tile.sportsBra': 'Спорт',
  'match3.ingredient.receipt': 'Квитанция',
  'match3.ingredient.memoryCard': 'Карта памяти',
  'match3.ingredient.serviceKey': 'Сервисный ключ',
  'match3.ingredient.damagedTowel': 'Полотенце со швом',
  'match3.clue.CUE_001': 'Квитанция прачечной',
  'match3.clue.CUE_002': 'Карта памяти',
  'match3.clue.CUE_003': 'Сервисный ключ',
  'match3.clue.CUE_004': 'Проводящий шов',
  'match3.level.M3_00_LOCKER_TUTORIAL.title': 'Шкафчик Эми',
  'match3.level.M3_00_LOCKER_TUTORIAL.storyAction': 'Зафиксировать содержимое шкафчика и найти связь с прачечной.',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.0': 'Ткань',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.1': 'Бирки',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.2': 'Комплекты',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.3': 'Клетки',
  'match3.level.M3_00_LOCKER_TUTORIAL.objective.4': 'Квитанция',
  'match3.level.M3_00_LOCKER_TUTORIAL.startBark.speaker': 'Оноэ',
  'match3.level.M3_00_LOCKER_TUTORIAL.startBark.text': 'Сначала категории. Потом выводы.',
  'match3.level.M3_00_LOCKER_TUTORIAL.winBark.speaker': 'Эми',
  'match3.level.M3_00_LOCKER_TUTORIAL.winBark.text': 'Нашли что-нибудь настоящее?',
  'match3.level.M3_01_PHOTO_PROPS.title': 'Фотореквизит Кэнтаро',
  'match3.level.M3_01_PHOTO_PROPS.storyAction': 'Разобрать реквизит по номерам и найти карту памяти с таймкодами.',
  'match3.level.M3_01_PHOTO_PROPS.objective.0': 'Коробки',
  'match3.level.M3_01_PHOTO_PROPS.objective.1': 'Бирки',
  'match3.level.M3_01_PHOTO_PROPS.objective.2': 'Карта',
  'match3.level.M3_01_PHOTO_PROPS.startBark.speaker': 'Кэнтаро',
  'match3.level.M3_01_PHOTO_PROPS.startBark.text': 'Сначала номера. И ничего не надевайте — это реквизит.',
  'match3.level.M3_01_PHOTO_PROPS.winBark.speaker': 'Мику',
  'match3.level.M3_01_PHOTO_PROPS.winBark.text': 'Нашла. Теперь посмотрим не на комнату, а на время.',
  'match3.level.M3_02_POOL_LAUNDRY.title': 'Мокрые показания',
  'match3.level.M3_02_POOL_LAUNDRY.storyAction': 'Восстановить партию стирки, очистить пену и открыть сервисный шкаф.',
  'match3.level.M3_02_POOL_LAUNDRY.objective.0': 'Пена',
  'match3.level.M3_02_POOL_LAUNDRY.objective.1': 'Бирки',
  'match3.level.M3_02_POOL_LAUNDRY.objective.2': 'Ключ',
  'match3.level.M3_02_POOL_LAUNDRY.startBark.speaker': 'Норихиро',
  'match3.level.M3_02_POOL_LAUNDRY.startBark.text': 'Бирки сначала. Мокрые догадки сушатся дольше полотенец.',
  'match3.level.M3_02_POOL_LAUNDRY.winBark.speaker': 'Оноэ',
  'match3.level.M3_02_POOL_LAUNDRY.winBark.text': 'Партия восстановлена. Теперь сравним пропавшее.',
  'match3.level.M3_03_ORDERED_APARTMENT.title': 'Идеальный порядок',
  'match3.level.M3_03_ORDERED_APARTMENT.storyAction': 'Проверить возвращённый мешок и найти предмет с новым повреждением.',
  'match3.level.M3_03_ORDERED_APARTMENT.objective.0': 'Секции',
  'match3.level.M3_03_ORDERED_APARTMENT.objective.1': 'Пары',
  'match3.level.M3_03_ORDERED_APARTMENT.objective.2': 'Чек',
  'match3.level.M3_03_ORDERED_APARTMENT.objective.3': 'Полотенце',
  'match3.level.M3_03_ORDERED_APARTMENT.startBark.speaker': 'Норихиро',
  'match3.level.M3_03_ORDERED_APARTMENT.startBark.text': 'Слева направо. Если нарушите порядок, вы его восстановите.',
  'match3.level.M3_03_ORDERED_APARTMENT.winBark.speaker': 'Мику',
  'match3.level.M3_03_ORDERED_APARTMENT.winBark.text': 'Здесь ничего не украли. Но кое-что добавили.',

} as const satisfies MessageCatalog;
