import type { MessageCatalog } from '../MessageCatalog';

export const ruCatalog = {
  'localization.language.ru': 'Русский',
  'localization.language.en': 'English',
  'localization.language.label': 'Язык',
  'localization.language.help': 'Язык интерфейса сохраняется на этом устройстве отдельно от игрового прогресса.',

  'common.back': 'Назад',
  'common.navigation': 'Навигация',
  'common.settings': 'Настройки',
  'common.on': 'ON',
  'common.off': 'OFF',
  'common.enabled': 'Включено',
  'common.disabled': 'Выключено',
  'common.available': 'доступен',
  'common.unavailable': 'недоступен',

  'menu.eyebrow': 'SEIRAN COLLEGE · CASE 001',
  'menu.title': 'Детективы',
  'menu.titleAccent': 'класса U',
  'menu.tagline': 'Комедийная visual novel × match‑3',
  'menu.heroAria': 'Мику, Оноэ и Аюки',
  'menu.newGame': 'Новая игра',
  'menu.continue': 'Продолжить',
  'menu.settings': 'Настройки',
  'menu.sceneNavigation': 'Навигация по сценам',
  'menu.saveDiagnostics': 'Сохранения и диагностика',
  'menu.scriptLines': '{count} строк сценария',

  'settings.eyebrow': 'CONFIG · SYSTEM',
  'settings.title': 'Настройки',
  'settings.audioHeading': 'Звук и отклик',
  'settings.audioCopy': 'Музыка и SFX генерируются локально через Web Audio и не требуют загрузки аудиофайлов. Настройки сохраняются отдельно от игрового прогресса.',
  'settings.languageHeading': 'Язык',
  'settings.installHeading': 'Установка и офлайн',
  'settings.mobileContractTitle': 'Мобильный контракт',
  'settings.mobileContractCopy': 'Звук активируется только после первого касания/клавиши. При сворачивании вкладки музыка приостанавливается и безопасно возобновляется при возвращении.',
  'settings.navigationLabel': 'НАВИГАЦИЯ',
  'settings.mainMenu': 'Главное меню',
  'settings.mainMenuMatchWarning': 'Текущая попытка потребует подтверждения',
  'settings.mainMenuSafe': 'Сохранённый прогресс не потеряется',

  'audio.music': 'Музыка',
  'audio.effects': 'Эффекты',
  'audio.musicVolumeAria': 'Громкость музыки',
  'audio.effectsVolumeAria': 'Громкость эффектов',
  'audio.mute': 'Без звука',
  'audio.haptics': 'Haptics',
  'audio.hapticsSupported': 'Поддерживается устройством',
  'audio.hapticsUnavailable': 'Недоступно в этом браузере',
  'audio.previewMusic': '▶ Проверить музыку',
  'audio.previewEffects': '✦ Проверить SFX',
  'audio.webAudio': 'Web Audio',
  'audio.hapticsCapability': 'Haptics',
  'audio.hapticsAvailable': 'доступны',
  'audio.hapticsFallback': 'fallback без вибрации',

  'pwa.install.installed': 'Установлено',
  'pwa.install.available': 'Можно установить',
  'pwa.install.browserMenu': 'Через меню браузера',
  'pwa.online': 'online',
  'pwa.offline': 'offline',
  'pwa.cacheFailures': '{count} ошибок cache',
  'pwa.installAction': 'Установить',
  'pwa.checkUpdate': 'Проверить обновление',

  'vn.chrome.openDossier': 'Открыть досье',
  'vn.chrome.navigation': 'Навигация visual novel',
  'vn.chrome.history': 'История диалога',
  'vn.chrome.direction': 'ПОСТАНОВКА',
  'vn.chrome.controls': 'Управление visual novel',
  'vn.chrome.dossierUpdated': 'ДОСЬЕ ОБНОВЛЕНО',
  'vn.status.saved': 'Ручной слот сохранён',
  'vn.status.saveFailed': 'Не удалось сохранить ручной слот',
  'vn.status.emptySlot': 'Ручной слот пока пуст',
  'vn.status.skipReadOnly': 'SKIP доступен только для уже прочитанных реплик',

  'vn.choice.header': 'Выбор версии',
  'vn.choice.prompt': 'С чего начать?',
  'vn.choice.A.title': 'Сначала найдём вторую пострадавшую',
  'vn.choice.A.effect': 'Доверие источников +1',
  'vn.choice.B.title': 'Предупредим анонимно',
  'vn.choice.B.effect': 'Сила слухов +1',
  'vn.choice.C.title': 'Передадим дело администрации',
  'vn.choice.C.effect': 'Доверие Оноэ +1',

  'vn.scene.VN_SCENE_00_PROLOGUE.title': 'Клуб, которого почти нет',
  'vn.scene.VN_SCENE_00_PROLOGUE.location': 'Комната детективного клуба',
  'vn.scene.VN_SCENE_01_E0_PRE.title': 'Дело класса U',
  'vn.scene.VN_SCENE_01_E0_PRE.location': 'Комната клуба → раздевалка',
  'vn.scene.VN_SCENE_02_E0_POST.title': 'То, что вор оставил',
  'vn.scene.VN_SCENE_02_E0_POST.location': 'Раздевалка лёгкой атлетики',
  'vn.scene.VN_SCENE_03_E1_PRE.title': 'Комната, которая всё объясняет слишком плохо',
  'vn.scene.VN_SCENE_03_E1_PRE.location': 'Квартира Кэнтаро',
  'vn.scene.VN_SCENE_04_E1_POST.title': 'Манекен с лучшим алиби',
  'vn.scene.VN_SCENE_04_E1_POST.location': 'Квартира Кэнтаро',
  'vn.scene.VN_SCENE_05_E2_PRE.title': 'Мокрые показания',
  'vn.scene.VN_SCENE_05_E2_PRE.location': 'Раздевалка клуба плавания',
  'vn.scene.VN_SCENE_06_E2_POST.title': 'Таблица без вкуса',
  'vn.scene.VN_SCENE_06_E2_POST.location': 'Раздевалка клуба плавания',
  'vn.scene.VN_SCENE_07_E3_PRE.title': 'Розовое признание',
  'vn.scene.VN_SCENE_07_E3_PRE.location': 'Квартира Норихиро',
  'vn.scene.VN_SCENE_08_E3_POST.title': 'Это не ткань',
  'vn.scene.VN_SCENE_08_E3_POST.location': 'Квартира Норихиро',
} as const satisfies MessageCatalog;
